

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "76", "89", "128", "131", "138", "139"],
		"CDFG" : "top",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "102476", "EstimateLatencyMax" : "102476",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "IO",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "24", "SubInstance" : "grp_conv1_fu_226", "Port" : "gmem0", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "131", "SubInstance" : "grp_top_Pipeline_DENSE_OUTER_DENSE_INNER_fu_317", "Port" : "gmem0", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "input_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "outputDense", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_2", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_2", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_3", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_3", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_4", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_4", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_5", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_5", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_6", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_6", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_7", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_7", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_8", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_8", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "p_ZL12conv2_weight_6", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "p_ZL12conv2_weight_6", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "p_ZL12conv2_weight_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "p_ZL12conv2_weight_4", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "p_ZL12conv2_weight_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "p_ZL12conv2_weight_3", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "p_ZL12conv2_weight_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "p_ZL12conv2_weight_0", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "p_ZL12conv2_weight_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "p_ZL12conv2_weight_1", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "p_ZL12conv2_weight_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "p_ZL12conv2_weight_2", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "p_ZL12conv2_weight_5", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "p_ZL12conv2_weight_5", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "p_ZL12conv2_weight_7", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "p_ZL12conv2_weight_7", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "p_ZL12conv2_weight_8", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_conv2_fu_255", "Port" : "p_ZL12conv2_weight_8", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "fc1_weight", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "131", "SubInstance" : "grp_top_Pipeline_DENSE_OUTER_DENSE_INNER_fu_317", "Port" : "fc1_weight", "Inst_start_state" : "10", "Inst_end_state" : "11"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputConv_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputConv_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputConv_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputConv_3_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputConv_4_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool_1_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool_2_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool_3_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool_4_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool_5_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool_6_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool_7_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputConv2_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputConv2_1_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool2_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool2_1_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool2_2_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool2_3_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool2_4_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool2_5_U", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool2_6_U", "Parent" : "0"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.outputPool2_7_U", "Parent" : "0"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226", "Parent" : "0", "Child" : ["25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "43"],
		"CDFG" : "conv1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "7085", "EstimateLatencyMax" : "7085",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "41", "SubInstance" : "grp_conv1_Pipeline_LOAD_1_fu_133", "Port" : "gmem0", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "input_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "outputConv_0", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156", "Port" : "outputConv_0", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "outputConv_1", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156", "Port" : "outputConv_1", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "outputConv_2", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156", "Port" : "outputConv_2", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "outputConv_3", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156", "Port" : "outputConv_3", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "outputConv_4", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156", "Port" : "outputConv_4", "Inst_start_state" : "11", "Inst_end_state" : "12"}]}]},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_U", "Parent" : "24"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_1_U", "Parent" : "24"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_2_U", "Parent" : "24"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_3_U", "Parent" : "24"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_4_U", "Parent" : "24"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_5_U", "Parent" : "24"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_6_U", "Parent" : "24"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_7_U", "Parent" : "24"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_8_U", "Parent" : "24"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_9_U", "Parent" : "24"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_10_U", "Parent" : "24"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_11_U", "Parent" : "24"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_12_U", "Parent" : "24"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_13_U", "Parent" : "24"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_14_U", "Parent" : "24"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.temp_15_U", "Parent" : "24"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_LOAD_1_fu_133", "Parent" : "24", "Child" : ["42"],
		"CDFG" : "conv1_Pipeline_LOAD_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "787", "EstimateLatencyMax" : "787",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "input_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "temp_15", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp_14", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp_13", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp_12", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp_11", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp_10", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp_9", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "LOAD_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "42", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_LOAD_1_fu_133.flow_control_loop_pipe_sequential_init_U", "Parent" : "41"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156", "Parent" : "24", "Child" : ["44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75"],
		"CDFG" : "conv1_Pipeline_CO_1_H_1_W_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "6287", "EstimateLatencyMax" : "6287",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "outputConv_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputConv_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputConv_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputConv_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputConv_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "temp", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_9", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_10", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_11", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_12", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_13", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "temp_15", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "CO_1_H_1_W_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter14", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter14", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "44", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.urem_8ns_4ns_3_12_1_U19", "Parent" : "43"},
	{"ID" : "45", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_33_4_8_1_1_U20", "Parent" : "43"},
	{"ID" : "46", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_33_4_8_1_1_U21", "Parent" : "43"},
	{"ID" : "47", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_33_4_8_1_1_U22", "Parent" : "43"},
	{"ID" : "48", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_33_4_8_1_1_U23", "Parent" : "43"},
	{"ID" : "49", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_33_4_8_1_1_U24", "Parent" : "43"},
	{"ID" : "50", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_33_4_8_1_1_U25", "Parent" : "43"},
	{"ID" : "51", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_33_4_8_1_1_U26", "Parent" : "43"},
	{"ID" : "52", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_33_4_8_1_1_U27", "Parent" : "43"},
	{"ID" : "53", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_33_4_8_1_1_U28", "Parent" : "43"},
	{"ID" : "54", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_17_3_4_1_1_U29", "Parent" : "43"},
	{"ID" : "55", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.mul_4s_8s_12_1_1_U30", "Parent" : "43"},
	{"ID" : "56", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_17_3_4_1_1_U31", "Parent" : "43"},
	{"ID" : "57", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.mul_13ns_15ns_27_1_1_U32", "Parent" : "43"},
	{"ID" : "58", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_17_3_2_1_1_U33", "Parent" : "43"},
	{"ID" : "59", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_17_3_3_1_1_U34", "Parent" : "43"},
	{"ID" : "60", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.mul_4s_8s_12_1_1_U35", "Parent" : "43"},
	{"ID" : "61", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_17_3_4_1_1_U36", "Parent" : "43"},
	{"ID" : "62", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.mul_4s_8s_12_1_1_U37", "Parent" : "43"},
	{"ID" : "63", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_17_3_3_1_1_U38", "Parent" : "43"},
	{"ID" : "64", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.mul_3ns_8s_11_1_1_U39", "Parent" : "43"},
	{"ID" : "65", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.mul_8s_3ns_11_1_1_U40", "Parent" : "43"},
	{"ID" : "66", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_17_3_4_1_1_U41", "Parent" : "43"},
	{"ID" : "67", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.mul_4s_8s_12_1_1_U42", "Parent" : "43"},
	{"ID" : "68", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_17_3_4_1_1_U43", "Parent" : "43"},
	{"ID" : "69", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.mul_4s_8s_12_1_1_U44", "Parent" : "43"},
	{"ID" : "70", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_17_3_4_1_1_U45", "Parent" : "43"},
	{"ID" : "71", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.mul_4s_8s_12_1_1_U46", "Parent" : "43"},
	{"ID" : "72", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.sparsemux_17_3_4_1_1_U47", "Parent" : "43"},
	{"ID" : "73", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.mul_4s_8s_12_1_1_U48", "Parent" : "43"},
	{"ID" : "74", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.mac_muladd_10ns_4ns_5ns_13_4_1_U49", "Parent" : "43"},
	{"ID" : "75", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv1_fu_226.grp_conv1_Pipeline_CO_1_H_1_W_1_fu_156.flow_control_loop_pipe_sequential_init_U", "Parent" : "43"},
	{"ID" : "76", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_pool_fu_238", "Parent" : "0", "Child" : ["77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88"],
		"CDFG" : "pool",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1586", "EstimateLatencyMax" : "1586",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "outputPool_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputPool_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputPool_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputPool_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputPool_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputPool_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputPool_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputPool_7", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "CO_LOOP_H_LOOP_W_LOOP", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter17", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter17", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_pool_fu_238.urem_8ns_4ns_3_12_1_U104", "Parent" : "76"},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_pool_fu_238.mul_4ns_11ns_13_1_1_U105", "Parent" : "76"},
	{"ID" : "79", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_pool_fu_238.mul_13ns_15ns_27_1_1_U106", "Parent" : "76"},
	{"ID" : "80", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_pool_fu_238.mul_13ns_15ns_27_1_1_U107", "Parent" : "76"},
	{"ID" : "81", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_pool_fu_238.mul_13ns_15ns_27_1_1_U108", "Parent" : "76"},
	{"ID" : "82", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_pool_fu_238.mul_13ns_15ns_27_1_1_U109", "Parent" : "76"},
	{"ID" : "83", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_pool_fu_238.sparsemux_11_3_7_1_1_U110", "Parent" : "76"},
	{"ID" : "84", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_pool_fu_238.sparsemux_11_3_7_1_1_U111", "Parent" : "76"},
	{"ID" : "85", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_pool_fu_238.sparsemux_11_3_7_1_1_U112", "Parent" : "76"},
	{"ID" : "86", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_pool_fu_238.sparsemux_11_3_7_1_1_U113", "Parent" : "76"},
	{"ID" : "87", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_pool_fu_238.mac_muladd_8ns_4ns_4ns_11_4_1_U114", "Parent" : "76"},
	{"ID" : "88", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_pool_fu_238.flow_control_loop_pipe_sequential_init_U", "Parent" : "76"},
	{"ID" : "89", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255", "Parent" : "0", "Child" : ["90", "127"],
		"CDFG" : "conv2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "85153", "EstimateLatencyMax" : "85153",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "input_0", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "input_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "input_1", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "input_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "input_2", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "input_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "input_3", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "input_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "input_4", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "input_5", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "input_5", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "input_6", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "input_6", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "input_7", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "input_7", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "outputConv_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputConv_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_2", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_2", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_3", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_3", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_4", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_4", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_5", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_5", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_6", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_6", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_7", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_7", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_8", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_8", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "p_ZL12conv2_weight_6", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "p_ZL12conv2_weight_6", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "p_ZL12conv2_weight_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "p_ZL12conv2_weight_4", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "p_ZL12conv2_weight_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "p_ZL12conv2_weight_3", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "p_ZL12conv2_weight_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "p_ZL12conv2_weight_0", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "p_ZL12conv2_weight_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "p_ZL12conv2_weight_1", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "p_ZL12conv2_weight_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "p_ZL12conv2_weight_2", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "p_ZL12conv2_weight_5", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "p_ZL12conv2_weight_5", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "p_ZL12conv2_weight_7", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "p_ZL12conv2_weight_7", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "p_ZL12conv2_weight_8", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "90", "SubInstance" : "grp_conv2_Pipeline_CI_2_fu_251", "Port" : "p_ZL12conv2_weight_8", "Inst_start_state" : "5", "Inst_end_state" : "6"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_70_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "9", "FirstState" : "ap_ST_fsm_state4", "LastState" : ["ap_ST_fsm_state9"], "QuitState" : ["ap_ST_fsm_state4"], "PreState" : ["ap_ST_fsm_state3"], "PostState" : ["ap_ST_fsm_state3"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_69_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "9", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state4"], "QuitState" : ["ap_ST_fsm_state3"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state2"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "CO_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "9", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state3"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "90", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251", "Parent" : "89", "Child" : ["91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126"],
		"CDFG" : "conv2_Pipeline_CI_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "21", "EstimateLatencyMax" : "21",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "add_ln85", "Type" : "None", "Direction" : "I"},
			{"Name" : "add_ln83", "Type" : "None", "Direction" : "I"},
			{"Name" : "add_ln83_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "add_ln82", "Type" : "None", "Direction" : "I"},
			{"Name" : "and_ln85_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln85", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "zext_ln82", "Type" : "None", "Direction" : "I"},
			{"Name" : "and_ln85_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln70_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "and_ln85_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "shl_ln", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln104", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "and_ln85", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln85_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZL12conv2_weight_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "conv2_ap_fixed_8_5_5_3_0_ap_fixed_8_5_5_3_0_partial_sums_8", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZL12conv2_weight_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZL12conv2_weight_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZL12conv2_weight_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZL12conv2_weight_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZL12conv2_weight_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZL12conv2_weight_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZL12conv2_weight_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZL12conv2_weight_8", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "CI_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter12", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter12", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "91", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.p_ZL12conv2_weight_6_U", "Parent" : "90"},
	{"ID" : "92", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.p_ZL12conv2_weight_4_U", "Parent" : "90"},
	{"ID" : "93", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.p_ZL12conv2_weight_3_U", "Parent" : "90"},
	{"ID" : "94", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.p_ZL12conv2_weight_0_U", "Parent" : "90"},
	{"ID" : "95", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.p_ZL12conv2_weight_1_U", "Parent" : "90"},
	{"ID" : "96", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.p_ZL12conv2_weight_2_U", "Parent" : "90"},
	{"ID" : "97", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.p_ZL12conv2_weight_5_U", "Parent" : "90"},
	{"ID" : "98", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.p_ZL12conv2_weight_7_U", "Parent" : "90"},
	{"ID" : "99", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.p_ZL12conv2_weight_8_U", "Parent" : "90"},
	{"ID" : "100", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_7_1_1_U134", "Parent" : "90"},
	{"ID" : "101", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_7_1_1_U135", "Parent" : "90"},
	{"ID" : "102", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_7_1_1_U136", "Parent" : "90"},
	{"ID" : "103", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_7_1_1_U137", "Parent" : "90"},
	{"ID" : "104", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_7_1_1_U138", "Parent" : "90"},
	{"ID" : "105", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_7_1_1_U139", "Parent" : "90"},
	{"ID" : "106", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_7_1_1_U140", "Parent" : "90"},
	{"ID" : "107", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_7_1_1_U141", "Parent" : "90"},
	{"ID" : "108", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_7_1_1_U142", "Parent" : "90"},
	{"ID" : "109", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_8_1_1_U143", "Parent" : "90"},
	{"ID" : "110", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.mul_4s_7ns_11_1_1_U144", "Parent" : "90"},
	{"ID" : "111", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_8_1_1_U145", "Parent" : "90"},
	{"ID" : "112", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.mul_4s_7ns_11_1_1_U146", "Parent" : "90"},
	{"ID" : "113", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_8_1_1_U147", "Parent" : "90"},
	{"ID" : "114", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.mul_4s_7ns_11_1_1_U148", "Parent" : "90"},
	{"ID" : "115", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_8_1_1_U149", "Parent" : "90"},
	{"ID" : "116", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.mul_4s_7ns_11_1_1_U150", "Parent" : "90"},
	{"ID" : "117", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.mul_4s_7ns_11_1_1_U151", "Parent" : "90"},
	{"ID" : "118", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_8_1_1_U152", "Parent" : "90"},
	{"ID" : "119", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.mul_4s_7ns_11_1_1_U153", "Parent" : "90"},
	{"ID" : "120", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_8_1_1_U154", "Parent" : "90"},
	{"ID" : "121", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.mul_4s_7ns_11_1_1_U155", "Parent" : "90"},
	{"ID" : "122", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_8_1_1_U156", "Parent" : "90"},
	{"ID" : "123", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.mul_4s_7ns_11_1_1_U157", "Parent" : "90"},
	{"ID" : "124", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.sparsemux_17_3_8_1_1_U158", "Parent" : "90"},
	{"ID" : "125", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.mac_muladd_7ns_3s_11s_12_4_1_U159", "Parent" : "90"},
	{"ID" : "126", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.grp_conv2_Pipeline_CI_2_fu_251.flow_control_loop_pipe_sequential_init_U", "Parent" : "90"},
	{"ID" : "127", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_fu_255.sparsemux_33_4_3_1_1_U210", "Parent" : "89"},
	{"ID" : "128", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_pool_1_fu_303", "Parent" : "0", "Child" : ["129", "130"],
		"CDFG" : "pool_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "790", "EstimateLatencyMax" : "790",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "outputPool_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputPool_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputPool_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputPool_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputPool_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputPool_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputPool_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "outputPool_7", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "CO_LOOP_H_LOOP_W_LOOP", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "129", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_pool_1_fu_303.mac_muladd_7ns_5ns_3ns_11_4_1_U222", "Parent" : "128"},
	{"ID" : "130", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_pool_1_fu_303.flow_control_loop_pipe_sequential_init_U", "Parent" : "128"},
	{"ID" : "131", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_Pipeline_DENSE_OUTER_DENSE_INNER_fu_317", "Parent" : "0", "Child" : ["132", "133", "134", "135", "136", "137"],
		"CDFG" : "top_Pipeline_DENSE_OUTER_DENSE_INNER",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "7847", "EstimateLatencyMax" : "7847",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "outputDense", "Type" : "None", "Direction" : "I"},
			{"Name" : "outputPool2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "outputPool2_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "outputPool2_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "outputPool2_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "outputPool2_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "outputPool2_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "outputPool2_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "outputPool2_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "fc1_weight", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "DENSE_OUTER_DENSE_INNER", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "132", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_Pipeline_DENSE_OUTER_DENSE_INNER_fu_317.fc1_weight_U", "Parent" : "131"},
	{"ID" : "133", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_Pipeline_DENSE_OUTER_DENSE_INNER_fu_317.sparsemux_21_4_2_1_1_U234", "Parent" : "131"},
	{"ID" : "134", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_Pipeline_DENSE_OUTER_DENSE_INNER_fu_317.sparsemux_17_3_7_1_1_U235", "Parent" : "131"},
	{"ID" : "135", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_Pipeline_DENSE_OUTER_DENSE_INNER_fu_317.mul_7ns_4s_11_1_1_U236", "Parent" : "131"},
	{"ID" : "136", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_Pipeline_DENSE_OUTER_DENSE_INNER_fu_317.mac_muladd_10ns_4ns_10ns_13_4_1_U237", "Parent" : "131"},
	{"ID" : "137", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_Pipeline_DENSE_OUTER_DENSE_INNER_fu_317.flow_control_loop_pipe_sequential_init_U", "Parent" : "131"},
	{"ID" : "138", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "139", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U", "Parent" : "0"}]}
