// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module top_dense_Pipeline_DENSE_OUTER_DENSE_INNER (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_address0,
        input_0_ce0,
        input_0_q0,
        input_1_address0,
        input_1_ce0,
        input_1_q0,
        input_2_address0,
        input_2_ce0,
        input_2_q0,
        input_3_address0,
        input_3_ce0,
        input_3_q0,
        input_4_address0,
        input_4_ce0,
        input_4_q0,
        input_5_address0,
        input_5_ce0,
        input_5_q0,
        input_6_address0,
        input_6_ce0,
        input_6_q0,
        input_7_address0,
        input_7_ce0,
        input_7_q0,
        input_8_address0,
        input_8_ce0,
        input_8_q0,
        input_9_address0,
        input_9_ce0,
        input_9_q0,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        outputDense
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] input_0_address0;
output   input_0_ce0;
input  [6:0] input_0_q0;
output  [6:0] input_1_address0;
output   input_1_ce0;
input  [6:0] input_1_q0;
output  [6:0] input_2_address0;
output   input_2_ce0;
input  [6:0] input_2_q0;
output  [6:0] input_3_address0;
output   input_3_ce0;
input  [6:0] input_3_q0;
output  [6:0] input_4_address0;
output   input_4_ce0;
input  [6:0] input_4_q0;
output  [6:0] input_5_address0;
output   input_5_ce0;
input  [6:0] input_5_q0;
output  [6:0] input_6_address0;
output   input_6_ce0;
input  [6:0] input_6_q0;
output  [6:0] input_7_address0;
output   input_7_ce0;
input  [6:0] input_7_q0;
output  [6:0] input_8_address0;
output   input_8_ce0;
input  [6:0] input_8_q0;
output  [6:0] input_9_address0;
output   input_9_ce0;
input  [6:0] input_9_q0;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [7:0] m_axi_gmem0_0_WDATA;
output  [0:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [7:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [63:0] outputDense;

reg ap_idle;
reg m_axi_gmem0_0_WVALID;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln15_reg_2333;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] p_ZL10fc1_weight_0_q0;
wire   [3:0] p_ZL10fc1_weight_0_q1;
wire   [3:0] p_ZL10fc1_weight_2_q0;
wire   [3:0] p_ZL10fc1_weight_2_q1;
wire   [2:0] p_ZL10fc1_weight_4_q0;
wire   [2:0] p_ZL10fc1_weight_4_q1;
wire   [3:0] p_ZL10fc1_weight_6_q0;
wire   [3:0] p_ZL10fc1_weight_6_q1;
wire   [3:0] p_ZL10fc1_weight_8_q0;
wire   [3:0] p_ZL10fc1_weight_8_q1;
wire   [2:0] p_ZL10fc1_weight_1_q0;
wire   [2:0] p_ZL10fc1_weight_1_q1;
wire   [3:0] p_ZL10fc1_weight_3_q0;
wire   [3:0] p_ZL10fc1_weight_3_q1;
wire   [3:0] p_ZL10fc1_weight_5_q0;
wire   [3:0] p_ZL10fc1_weight_5_q1;
wire   [3:0] p_ZL10fc1_weight_7_q0;
wire   [3:0] p_ZL10fc1_weight_7_q1;
wire   [3:0] p_ZL10fc1_weight_9_q0;
wire   [3:0] p_ZL10fc1_weight_9_q1;
reg    gmem0_blk_n_W;
wire    ap_block_pp0_stage0_grp1;
reg   [0:0] icmp_ln20_6_reg_2371;
reg   [0:0] icmp_ln20_6_reg_2371_pp0_iter3_reg;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln15_fu_915_p2;
reg    ap_block_state13_io_grp1;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln15_reg_2333_pp0_iter1_reg;
reg   [0:0] icmp_ln15_reg_2333_pp0_iter2_reg;
reg   [0:0] icmp_ln15_reg_2333_pp0_iter3_reg;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [9:0] select_ln15_fu_945_p3;
reg   [9:0] select_ln15_reg_2342;
reg   [9:0] select_ln15_reg_2342_pp0_iter1_reg;
wire   [0:0] or_ln15_fu_959_p2;
reg   [0:0] or_ln15_reg_2355;
reg   [0:0] or_ln15_reg_2355_pp0_iter1_reg;
reg   [0:0] or_ln15_reg_2355_pp0_iter2_reg;
wire   [3:0] select_ln15_3_fu_971_p3;
reg   [3:0] select_ln15_3_reg_2360;
reg   [3:0] select_ln15_3_reg_2360_pp0_iter1_reg;
wire   [0:0] first_iter_0_fu_979_p2;
reg   [0:0] first_iter_0_reg_2367;
reg   [0:0] first_iter_0_reg_2367_pp0_iter1_reg;
reg   [0:0] first_iter_0_reg_2367_pp0_iter2_reg;
wire   [0:0] icmp_ln20_6_fu_1006_p2;
wire    ap_block_pp0_stage2_11001;
reg   [0:0] icmp_ln20_6_reg_2371_pp0_iter1_reg;
reg   [0:0] icmp_ln20_6_reg_2371_pp0_iter2_reg;
wire   [1:0] sum_fu_1017_p23;
reg   [1:0] sum_reg_2376;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [1:0] sum_reg_2376_pp0_iter2_reg;
wire   [12:0] mul_ln27_1_fu_1067_p2;
reg   [12:0] mul_ln27_1_reg_2381;
wire   [12:0] mul_ln27_fu_1073_p2;
reg   [12:0] mul_ln27_reg_2391;
reg   [6:0] tmp_6_reg_2396;
reg   [11:0] tmp_reg_2402;
reg   [10:0] tmp_3_reg_2407;
wire   [9:0] add_ln20_fu_1118_p2;
reg   [9:0] add_ln20_reg_2413;
wire   [0:0] icmp_ln20_fu_1123_p2;
reg   [0:0] icmp_ln20_reg_2418;
reg   [0:0] icmp_ln20_reg_2418_pp0_iter2_reg;
reg   [9:0] trunc_ln3_reg_2423;
reg   [9:0] tmp_8_reg_2428;
reg   [9:0] tmp_9_reg_2433;
reg   [9:0] tmp_10_reg_2438;
wire   [9:0] add_ln20_1_fu_1253_p2;
reg   [9:0] add_ln20_1_reg_2443;
reg   [9:0] tmp_11_reg_2448;
wire   [0:0] icmp_ln20_1_fu_1283_p2;
reg   [0:0] icmp_ln20_1_reg_2453;
reg   [0:0] icmp_ln20_1_reg_2453_pp0_iter2_reg;
wire   [9:0] add_ln20_2_fu_1289_p2;
reg   [9:0] add_ln20_2_reg_2458;
wire   [0:0] icmp_ln20_2_fu_1294_p2;
reg   [0:0] icmp_ln20_2_reg_2463;
reg   [0:0] icmp_ln20_2_reg_2463_pp0_iter2_reg;
wire   [9:0] add_ln20_3_fu_1300_p2;
reg   [9:0] add_ln20_3_reg_2468;
wire   [0:0] icmp_ln20_3_fu_1305_p2;
reg   [0:0] icmp_ln20_3_reg_2473;
reg   [0:0] icmp_ln20_3_reg_2473_pp0_iter2_reg;
wire   [9:0] add_ln20_4_fu_1311_p2;
reg   [9:0] add_ln20_4_reg_2478;
wire   [0:0] icmp_ln20_4_fu_1316_p2;
reg   [0:0] icmp_ln20_4_reg_2483;
reg   [0:0] icmp_ln20_4_reg_2483_pp0_iter2_reg;
wire   [9:0] add_ln20_5_fu_1322_p2;
reg   [9:0] add_ln20_5_reg_2488;
wire   [0:0] icmp_ln20_5_fu_1327_p2;
reg   [0:0] icmp_ln20_5_reg_2493;
reg   [0:0] icmp_ln20_5_reg_2493_pp0_iter2_reg;
reg   [9:0] tmp_12_reg_2598;
reg   [9:0] tmp_13_reg_2603;
reg   [9:0] tmp_14_reg_2608;
reg   [9:0] tmp_15_reg_2613;
reg   [9:0] tmp_16_reg_2618;
wire   [2:0] trunc_ln27_fu_1514_p1;
reg   [2:0] trunc_ln27_reg_2623;
wire   [3:0] w_val_fu_1535_p13;
reg  signed [3:0] w_val_reg_2633;
wire   [3:0] w_val_1_fu_1567_p13;
reg  signed [3:0] w_val_1_reg_2643;
wire   [3:0] w_val_2_fu_1599_p13;
reg  signed [3:0] w_val_2_reg_2653;
wire   [3:0] w_val_3_fu_1631_p13;
reg  signed [3:0] w_val_3_reg_2663;
wire   [10:0] mul_ln28_fu_1698_p2;
reg   [10:0] mul_ln28_reg_2803;
wire   [10:0] mul_ln28_1_fu_1711_p2;
reg   [10:0] mul_ln28_1_reg_2808;
wire   [10:0] mul_ln28_2_fu_1724_p2;
reg   [10:0] mul_ln28_2_reg_2813;
wire   [10:0] mul_ln28_3_fu_1737_p2;
reg   [10:0] mul_ln28_3_reg_2818;
wire   [3:0] w_val_4_fu_1747_p13;
reg  signed [3:0] w_val_4_reg_2823;
reg   [6:0] input_4_load_reg_2828;
wire   [3:0] w_val_5_fu_1778_p13;
reg  signed [3:0] w_val_5_reg_2833;
reg   [6:0] input_5_load_reg_2838;
wire   [3:0] w_val_6_fu_1809_p13;
reg  signed [3:0] w_val_6_reg_2843;
reg   [6:0] input_6_load_reg_2848;
wire   [3:0] w_val_7_fu_1840_p13;
reg  signed [3:0] w_val_7_reg_2853;
reg   [6:0] input_7_load_reg_2858;
reg   [6:0] input_8_load_reg_2888;
reg   [6:0] input_9_load_reg_2918;
wire   [7:0] sum_2_fu_1980_p4;
reg   [7:0] sum_2_reg_2923;
reg   [7:0] sum_3_reg_2928;
wire   [10:0] mul_ln28_5_fu_2032_p2;
reg   [10:0] mul_ln28_5_reg_2933;
wire   [10:0] mul_ln28_6_fu_2044_p2;
reg   [10:0] mul_ln28_6_reg_2938;
wire   [10:0] mul_ln28_7_fu_2056_p2;
reg   [10:0] mul_ln28_7_reg_2943;
wire   [3:0] w_val_8_fu_2066_p13;
reg  signed [3:0] w_val_8_reg_2948;
wire   [3:0] w_val_9_fu_2097_p13;
reg  signed [3:0] w_val_9_reg_2953;
wire   [7:0] sum_8_fu_2182_p3;
reg   [7:0] sum_8_reg_2958;
reg   [7:0] sum_9_reg_2963;
wire   [10:0] mul_ln28_8_fu_2218_p2;
reg   [10:0] mul_ln28_8_reg_2968;
wire   [10:0] mul_ln28_9_fu_2230_p2;
reg   [10:0] mul_ln28_9_reg_2973;
wire   [7:0] sum_14_fu_2294_p3;
reg   [7:0] sum_14_reg_2978;
reg    ap_condition_exit_pp0_iter3_stage0;
reg   [0:0] ap_phi_mux_cmp2_new_phi_0_phi_fu_881_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [7:0] ap_phi_mux_sext_ln161_phi_fu_891_p4;
wire   [7:0] ap_phi_reg_pp0_iter3_sext_ln161_reg_888;
wire  signed [7:0] sext_ln16_fu_1887_p1;
wire   [63:0] zext_ln27_6_fu_1341_p1;
wire    ap_block_pp0_stage0_grp0;
wire   [63:0] zext_ln27_7_fu_1350_p1;
wire   [63:0] zext_ln27_8_fu_1358_p1;
wire   [63:0] zext_ln27_9_fu_1366_p1;
wire   [63:0] zext_ln16_fu_1518_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln27_10_fu_1659_p1;
wire   [63:0] zext_ln27_11_fu_1667_p1;
wire   [63:0] zext_ln27_12_fu_1675_p1;
wire   [63:0] zext_ln27_13_fu_1683_p1;
wire   [63:0] zext_ln27_14_fu_1867_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln27_15_fu_1875_p1;
wire    ap_block_pp0_stage0_01001_grp1;
reg   [9:0] i_fu_228;
wire   [9:0] i_1_fu_1001_p2;
reg   [9:0] ap_sig_allocacmp_i_load;
reg   [3:0] c_fu_232;
reg   [3:0] ap_sig_allocacmp_c_load;
reg   [9:0] indvar_flatten_fu_236;
wire   [9:0] add_ln15_fu_921_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [7:0] sum_1_fu_240;
reg    p_ZL10fc1_weight_0_ce1_local;
reg   [9:0] p_ZL10fc1_weight_0_address1_local;
reg    p_ZL10fc1_weight_0_ce0_local;
reg   [9:0] p_ZL10fc1_weight_0_address0_local;
reg    p_ZL10fc1_weight_2_ce1_local;
reg   [9:0] p_ZL10fc1_weight_2_address1_local;
reg    p_ZL10fc1_weight_2_ce0_local;
reg   [9:0] p_ZL10fc1_weight_2_address0_local;
reg    p_ZL10fc1_weight_4_ce1_local;
reg   [9:0] p_ZL10fc1_weight_4_address1_local;
reg    p_ZL10fc1_weight_4_ce0_local;
reg   [9:0] p_ZL10fc1_weight_4_address0_local;
reg    p_ZL10fc1_weight_6_ce1_local;
reg   [9:0] p_ZL10fc1_weight_6_address1_local;
reg    p_ZL10fc1_weight_6_ce0_local;
reg   [9:0] p_ZL10fc1_weight_6_address0_local;
reg    p_ZL10fc1_weight_8_ce1_local;
reg   [9:0] p_ZL10fc1_weight_8_address1_local;
reg    p_ZL10fc1_weight_8_ce0_local;
reg   [9:0] p_ZL10fc1_weight_8_address0_local;
reg    p_ZL10fc1_weight_1_ce1_local;
reg   [9:0] p_ZL10fc1_weight_1_address1_local;
reg    p_ZL10fc1_weight_1_ce0_local;
reg   [9:0] p_ZL10fc1_weight_1_address0_local;
reg    p_ZL10fc1_weight_3_ce1_local;
reg   [9:0] p_ZL10fc1_weight_3_address1_local;
reg    p_ZL10fc1_weight_3_ce0_local;
reg   [9:0] p_ZL10fc1_weight_3_address0_local;
reg    p_ZL10fc1_weight_5_ce1_local;
reg   [9:0] p_ZL10fc1_weight_5_address1_local;
reg    p_ZL10fc1_weight_5_ce0_local;
reg   [9:0] p_ZL10fc1_weight_5_address0_local;
reg    p_ZL10fc1_weight_7_ce1_local;
reg   [9:0] p_ZL10fc1_weight_7_address1_local;
reg    p_ZL10fc1_weight_7_ce0_local;
reg   [9:0] p_ZL10fc1_weight_7_address0_local;
reg    p_ZL10fc1_weight_9_ce1_local;
reg   [9:0] p_ZL10fc1_weight_9_address1_local;
reg    p_ZL10fc1_weight_9_ce0_local;
reg   [9:0] p_ZL10fc1_weight_9_address0_local;
reg    input_0_ce0_local;
reg    input_1_ce0_local;
reg    input_2_ce0_local;
reg    input_3_ce0_local;
reg    input_4_ce0_local;
reg    input_5_ce0_local;
reg    input_6_ce0_local;
reg    input_7_ce0_local;
reg    input_8_ce0_local;
reg    input_9_ce0_local;
wire   [0:0] exit_cond_91395_fu_939_p2;
wire   [0:0] xor_ln15_fu_953_p2;
wire   [3:0] add_ln15_3_fu_965_p2;
wire   [3:0] grp_fu_985_p0;
wire   [1:0] sum_fu_1017_p21;
wire   [3:0] mul_ln27_1_fu_1067_p0;
wire   [12:0] zext_ln15_fu_1064_p1;
wire   [10:0] mul_ln27_1_fu_1067_p1;
wire   [3:0] mul_ln27_fu_1073_p0;
wire   [9:0] mul_ln27_fu_1073_p1;
wire   [9:0] mul_ln20_fu_1082_p0;
wire   [11:0] mul_ln20_fu_1082_p1;
wire   [20:0] mul_ln20_fu_1082_p2;
wire   [12:0] mul_ln27_2_fu_1132_p0;
wire   [14:0] mul_ln27_2_fu_1132_p1;
wire   [26:0] mul_ln27_2_fu_1132_p2;
wire   [12:0] i_cast_fu_1148_p1;
wire   [12:0] or_ln_fu_1151_p3;
wire   [12:0] add_ln24_fu_1158_p2;
wire   [12:0] mul_ln27_3_fu_1168_p0;
wire   [14:0] mul_ln27_3_fu_1168_p1;
wire   [26:0] mul_ln27_3_fu_1168_p2;
wire   [12:0] or_ln20_1_fu_1184_p3;
wire   [12:0] add_ln24_1_fu_1191_p2;
wire   [12:0] mul_ln27_4_fu_1201_p0;
wire   [14:0] mul_ln27_4_fu_1201_p1;
wire   [26:0] mul_ln27_4_fu_1201_p2;
wire   [12:0] or_ln20_2_fu_1220_p3;
wire   [12:0] add_ln24_2_fu_1227_p2;
wire   [12:0] mul_ln27_5_fu_1237_p0;
wire   [14:0] mul_ln27_5_fu_1237_p1;
wire   [26:0] mul_ln27_5_fu_1237_p2;
wire   [12:0] zext_ln20_fu_1217_p1;
wire   [12:0] add_ln24_3_fu_1258_p2;
wire   [12:0] mul_ln27_6_fu_1267_p0;
wire   [14:0] mul_ln27_6_fu_1267_p1;
wire   [26:0] mul_ln27_6_fu_1267_p2;
wire   [9:0] zext_ln20_2_fu_1333_p1;
wire   [9:0] add_ln27_fu_1336_p2;
wire   [12:0] zext_ln16_3_fu_1374_p1;
wire   [12:0] add_ln24_4_fu_1380_p2;
wire   [12:0] mul_ln27_7_fu_1389_p0;
wire   [14:0] mul_ln27_7_fu_1389_p1;
wire   [26:0] mul_ln27_7_fu_1389_p2;
wire   [12:0] zext_ln16_4_fu_1377_p1;
wire   [12:0] add_ln24_5_fu_1408_p2;
wire   [12:0] mul_ln27_8_fu_1417_p0;
wire   [14:0] mul_ln27_8_fu_1417_p1;
wire   [26:0] mul_ln27_8_fu_1417_p2;
wire   [12:0] zext_ln16_5_fu_1405_p1;
wire   [12:0] add_ln24_6_fu_1436_p2;
wire   [12:0] mul_ln27_9_fu_1445_p0;
wire   [14:0] mul_ln27_9_fu_1445_p1;
wire   [26:0] mul_ln27_9_fu_1445_p2;
wire   [12:0] zext_ln16_6_fu_1433_p1;
wire   [12:0] add_ln24_7_fu_1464_p2;
wire   [12:0] mul_ln27_10_fu_1473_p0;
wire   [14:0] mul_ln27_10_fu_1473_p1;
wire   [26:0] mul_ln27_10_fu_1473_p2;
wire   [12:0] zext_ln16_7_fu_1461_p1;
wire   [12:0] add_ln24_8_fu_1489_p2;
wire   [12:0] mul_ln27_11_fu_1498_p0;
wire   [14:0] mul_ln27_11_fu_1498_p1;
wire   [26:0] mul_ln27_11_fu_1498_p2;
wire   [2:0] grp_fu_985_p2;
wire  signed [3:0] w_val_fu_1535_p6;
wire   [3:0] w_val_fu_1535_p11;
wire  signed [3:0] w_val_1_fu_1567_p2;
wire   [3:0] w_val_1_fu_1567_p11;
wire  signed [3:0] w_val_2_fu_1599_p6;
wire   [3:0] w_val_2_fu_1599_p11;
wire  signed [3:0] w_val_3_fu_1631_p2;
wire   [3:0] w_val_3_fu_1631_p11;
wire   [6:0] mul_ln28_fu_1698_p0;
wire   [6:0] mul_ln28_1_fu_1711_p0;
wire   [6:0] mul_ln28_2_fu_1724_p0;
wire   [6:0] mul_ln28_3_fu_1737_p0;
wire  signed [3:0] w_val_4_fu_1747_p6;
wire   [3:0] w_val_4_fu_1747_p11;
wire  signed [3:0] w_val_5_fu_1778_p2;
wire   [3:0] w_val_5_fu_1778_p11;
wire  signed [3:0] w_val_6_fu_1809_p6;
wire   [3:0] w_val_6_fu_1809_p11;
wire  signed [3:0] w_val_7_fu_1840_p2;
wire   [3:0] w_val_7_fu_1840_p11;
wire   [10:0] shl_ln_fu_1891_p3;
wire   [10:0] add_ln28_fu_1899_p2;
wire   [7:0] tmp_2_fu_1904_p4;
wire   [7:0] empty_fu_1914_p3;
wire   [10:0] shl_ln28_1_fu_1921_p3;
wire   [10:0] add_ln28_1_fu_1929_p2;
wire   [7:0] tmp_5_fu_1934_p4;
wire   [10:0] shl_ln28_2_fu_1944_p3;
wire   [10:0] add_ln28_2_fu_1952_p2;
wire   [7:0] tmp_7_fu_1957_p4;
wire   [10:0] shl_ln28_3_fu_1967_p3;
wire   [10:0] add_ln28_3_fu_1975_p2;
wire   [6:0] mul_ln28_4_fu_1996_p0;
wire   [10:0] mul_ln28_4_fu_1996_p2;
wire   [10:0] shl_ln28_4_fu_2002_p3;
wire   [10:0] add_ln28_4_fu_2010_p2;
wire   [6:0] mul_ln28_5_fu_2032_p0;
wire   [6:0] mul_ln28_6_fu_2044_p0;
wire   [6:0] mul_ln28_7_fu_2056_p0;
wire  signed [3:0] w_val_8_fu_2066_p6;
wire   [3:0] w_val_8_fu_2066_p11;
wire  signed [3:0] w_val_9_fu_2097_p2;
wire   [3:0] w_val_9_fu_2097_p11;
wire   [7:0] sum_4_fu_2124_p3;
wire   [10:0] shl_ln28_5_fu_2129_p3;
wire   [10:0] add_ln28_5_fu_2137_p2;
wire   [7:0] sum_5_fu_2142_p4;
wire   [7:0] sum_6_fu_2152_p3;
wire   [10:0] shl_ln28_6_fu_2159_p3;
wire   [10:0] add_ln28_6_fu_2167_p2;
wire   [7:0] sum_7_fu_2172_p4;
wire   [10:0] shl_ln28_7_fu_2189_p3;
wire   [10:0] add_ln28_7_fu_2197_p2;
wire   [6:0] mul_ln28_8_fu_2218_p0;
wire   [6:0] mul_ln28_9_fu_2230_p0;
wire   [7:0] sum_10_fu_2236_p3;
wire   [10:0] shl_ln28_8_fu_2241_p3;
wire   [10:0] add_ln28_8_fu_2249_p2;
wire   [7:0] sum_16_fu_2254_p4;
wire   [7:0] sum_12_fu_2264_p3;
wire   [10:0] shl_ln28_9_fu_2271_p3;
wire   [10:0] add_ln28_9_fu_2279_p2;
wire   [7:0] sum_17_fu_2284_p4;
reg    grp_fu_985_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [2:0] ap_NS_fsm;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [20:0] mul_ln20_fu_1082_p00;
wire   [26:0] mul_ln27_10_fu_1473_p00;
wire   [26:0] mul_ln27_11_fu_1498_p00;
wire   [26:0] mul_ln27_2_fu_1132_p00;
wire   [26:0] mul_ln27_3_fu_1168_p00;
wire   [26:0] mul_ln27_4_fu_1201_p00;
wire   [26:0] mul_ln27_5_fu_1237_p00;
wire   [26:0] mul_ln27_6_fu_1267_p00;
wire   [26:0] mul_ln27_7_fu_1389_p00;
wire   [26:0] mul_ln27_8_fu_1417_p00;
wire   [26:0] mul_ln27_9_fu_1445_p00;
wire   [10:0] mul_ln28_1_fu_1711_p00;
wire   [10:0] mul_ln28_2_fu_1724_p00;
wire   [10:0] mul_ln28_3_fu_1737_p00;
wire   [10:0] mul_ln28_4_fu_1996_p00;
wire   [10:0] mul_ln28_5_fu_2032_p00;
wire   [10:0] mul_ln28_6_fu_2044_p00;
wire   [10:0] mul_ln28_7_fu_2056_p00;
wire   [10:0] mul_ln28_8_fu_2218_p00;
wire   [10:0] mul_ln28_9_fu_2230_p00;
wire   [10:0] mul_ln28_fu_1698_p00;
reg    ap_condition_1877;
wire   [3:0] sum_fu_1017_p1;
wire   [3:0] sum_fu_1017_p3;
wire   [3:0] sum_fu_1017_p5;
wire   [3:0] sum_fu_1017_p7;
wire   [3:0] sum_fu_1017_p9;
wire   [3:0] sum_fu_1017_p11;
wire   [3:0] sum_fu_1017_p13;
wire   [3:0] sum_fu_1017_p15;
wire  signed [3:0] sum_fu_1017_p17;
wire  signed [3:0] sum_fu_1017_p19;
wire   [2:0] w_val_fu_1535_p1;
wire   [2:0] w_val_fu_1535_p3;
wire   [2:0] w_val_fu_1535_p5;
wire  signed [2:0] w_val_fu_1535_p7;
wire   [2:0] w_val_fu_1535_p9;
wire   [2:0] w_val_1_fu_1567_p1;
wire   [2:0] w_val_1_fu_1567_p3;
wire   [2:0] w_val_1_fu_1567_p5;
wire  signed [2:0] w_val_1_fu_1567_p7;
wire   [2:0] w_val_1_fu_1567_p9;
wire   [2:0] w_val_2_fu_1599_p1;
wire   [2:0] w_val_2_fu_1599_p3;
wire   [2:0] w_val_2_fu_1599_p5;
wire   [2:0] w_val_2_fu_1599_p7;
wire  signed [2:0] w_val_2_fu_1599_p9;
wire   [2:0] w_val_3_fu_1631_p1;
wire   [2:0] w_val_3_fu_1631_p3;
wire   [2:0] w_val_3_fu_1631_p5;
wire   [2:0] w_val_3_fu_1631_p7;
wire  signed [2:0] w_val_3_fu_1631_p9;
wire  signed [2:0] w_val_4_fu_1747_p1;
wire   [2:0] w_val_4_fu_1747_p3;
wire   [2:0] w_val_4_fu_1747_p5;
wire   [2:0] w_val_4_fu_1747_p7;
wire   [2:0] w_val_4_fu_1747_p9;
wire  signed [2:0] w_val_5_fu_1778_p1;
wire   [2:0] w_val_5_fu_1778_p3;
wire   [2:0] w_val_5_fu_1778_p5;
wire   [2:0] w_val_5_fu_1778_p7;
wire   [2:0] w_val_5_fu_1778_p9;
wire   [2:0] w_val_6_fu_1809_p1;
wire  signed [2:0] w_val_6_fu_1809_p3;
wire   [2:0] w_val_6_fu_1809_p5;
wire   [2:0] w_val_6_fu_1809_p7;
wire   [2:0] w_val_6_fu_1809_p9;
wire   [2:0] w_val_7_fu_1840_p1;
wire  signed [2:0] w_val_7_fu_1840_p3;
wire   [2:0] w_val_7_fu_1840_p5;
wire   [2:0] w_val_7_fu_1840_p7;
wire   [2:0] w_val_7_fu_1840_p9;
wire   [2:0] w_val_8_fu_2066_p1;
wire   [2:0] w_val_8_fu_2066_p3;
wire  signed [2:0] w_val_8_fu_2066_p5;
wire   [2:0] w_val_8_fu_2066_p7;
wire   [2:0] w_val_8_fu_2066_p9;
wire   [2:0] w_val_9_fu_2097_p1;
wire   [2:0] w_val_9_fu_2097_p3;
wire  signed [2:0] w_val_9_fu_2097_p5;
wire   [2:0] w_val_9_fu_2097_p7;
wire   [2:0] w_val_9_fu_2097_p9;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 i_fu_228 = 10'd0;
#0 c_fu_232 = 4'd0;
#0 indvar_flatten_fu_236 = 10'd0;
#0 sum_1_fu_240 = 8'd0;
#0 ap_done_reg = 1'b0;
end

top_dense_Pipeline_DENSE_OUTER_DENSE_INNER_p_ZL10fc1_weight_0_ROM_AUTO_1R #(
    .DataWidth( 4 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
p_ZL10fc1_weight_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10fc1_weight_0_address0_local),
    .ce0(p_ZL10fc1_weight_0_ce0_local),
    .q0(p_ZL10fc1_weight_0_q0),
    .address1(p_ZL10fc1_weight_0_address1_local),
    .ce1(p_ZL10fc1_weight_0_ce1_local),
    .q1(p_ZL10fc1_weight_0_q1)
);

top_dense_Pipeline_DENSE_OUTER_DENSE_INNER_p_ZL10fc1_weight_2_ROM_AUTO_1R #(
    .DataWidth( 4 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
p_ZL10fc1_weight_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10fc1_weight_2_address0_local),
    .ce0(p_ZL10fc1_weight_2_ce0_local),
    .q0(p_ZL10fc1_weight_2_q0),
    .address1(p_ZL10fc1_weight_2_address1_local),
    .ce1(p_ZL10fc1_weight_2_ce1_local),
    .q1(p_ZL10fc1_weight_2_q1)
);

top_dense_Pipeline_DENSE_OUTER_DENSE_INNER_p_ZL10fc1_weight_4_ROM_AUTO_1R #(
    .DataWidth( 3 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
p_ZL10fc1_weight_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10fc1_weight_4_address0_local),
    .ce0(p_ZL10fc1_weight_4_ce0_local),
    .q0(p_ZL10fc1_weight_4_q0),
    .address1(p_ZL10fc1_weight_4_address1_local),
    .ce1(p_ZL10fc1_weight_4_ce1_local),
    .q1(p_ZL10fc1_weight_4_q1)
);

top_dense_Pipeline_DENSE_OUTER_DENSE_INNER_p_ZL10fc1_weight_6_ROM_AUTO_1R #(
    .DataWidth( 4 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
p_ZL10fc1_weight_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10fc1_weight_6_address0_local),
    .ce0(p_ZL10fc1_weight_6_ce0_local),
    .q0(p_ZL10fc1_weight_6_q0),
    .address1(p_ZL10fc1_weight_6_address1_local),
    .ce1(p_ZL10fc1_weight_6_ce1_local),
    .q1(p_ZL10fc1_weight_6_q1)
);

top_dense_Pipeline_DENSE_OUTER_DENSE_INNER_p_ZL10fc1_weight_8_ROM_AUTO_1R #(
    .DataWidth( 4 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
p_ZL10fc1_weight_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10fc1_weight_8_address0_local),
    .ce0(p_ZL10fc1_weight_8_ce0_local),
    .q0(p_ZL10fc1_weight_8_q0),
    .address1(p_ZL10fc1_weight_8_address1_local),
    .ce1(p_ZL10fc1_weight_8_ce1_local),
    .q1(p_ZL10fc1_weight_8_q1)
);

top_dense_Pipeline_DENSE_OUTER_DENSE_INNER_p_ZL10fc1_weight_1_ROM_AUTO_1R #(
    .DataWidth( 3 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
p_ZL10fc1_weight_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10fc1_weight_1_address0_local),
    .ce0(p_ZL10fc1_weight_1_ce0_local),
    .q0(p_ZL10fc1_weight_1_q0),
    .address1(p_ZL10fc1_weight_1_address1_local),
    .ce1(p_ZL10fc1_weight_1_ce1_local),
    .q1(p_ZL10fc1_weight_1_q1)
);

top_dense_Pipeline_DENSE_OUTER_DENSE_INNER_p_ZL10fc1_weight_3_ROM_AUTO_1R #(
    .DataWidth( 4 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
p_ZL10fc1_weight_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10fc1_weight_3_address0_local),
    .ce0(p_ZL10fc1_weight_3_ce0_local),
    .q0(p_ZL10fc1_weight_3_q0),
    .address1(p_ZL10fc1_weight_3_address1_local),
    .ce1(p_ZL10fc1_weight_3_ce1_local),
    .q1(p_ZL10fc1_weight_3_q1)
);

top_dense_Pipeline_DENSE_OUTER_DENSE_INNER_p_ZL10fc1_weight_5_ROM_AUTO_1R #(
    .DataWidth( 4 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
p_ZL10fc1_weight_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10fc1_weight_5_address0_local),
    .ce0(p_ZL10fc1_weight_5_ce0_local),
    .q0(p_ZL10fc1_weight_5_q0),
    .address1(p_ZL10fc1_weight_5_address1_local),
    .ce1(p_ZL10fc1_weight_5_ce1_local),
    .q1(p_ZL10fc1_weight_5_q1)
);

top_dense_Pipeline_DENSE_OUTER_DENSE_INNER_p_ZL10fc1_weight_7_ROM_AUTO_1R #(
    .DataWidth( 4 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
p_ZL10fc1_weight_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10fc1_weight_7_address0_local),
    .ce0(p_ZL10fc1_weight_7_ce0_local),
    .q0(p_ZL10fc1_weight_7_q0),
    .address1(p_ZL10fc1_weight_7_address1_local),
    .ce1(p_ZL10fc1_weight_7_ce1_local),
    .q1(p_ZL10fc1_weight_7_q1)
);

top_dense_Pipeline_DENSE_OUTER_DENSE_INNER_p_ZL10fc1_weight_9_ROM_AUTO_1R #(
    .DataWidth( 4 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
p_ZL10fc1_weight_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10fc1_weight_9_address0_local),
    .ce0(p_ZL10fc1_weight_9_ce0_local),
    .q0(p_ZL10fc1_weight_9_q0),
    .address1(p_ZL10fc1_weight_9_address1_local),
    .ce1(p_ZL10fc1_weight_9_ce1_local),
    .q1(p_ZL10fc1_weight_9_q1)
);

top_urem_4ns_4ns_3_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 3 ))
urem_4ns_4ns_3_8_1_U306(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_985_p0),
    .din1(4'd5),
    .ce(grp_fu_985_ce),
    .dout(grp_fu_985_p2)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_21_4_2_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 2 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 2 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 2 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 2 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 2 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 2 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 2 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 2 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 2 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 2 ),
    .def_WIDTH( 2 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 2 ))
sparsemux_21_4_2_1_1_U307(
    .din0(2'd1),
    .din1(2'd0),
    .din2(2'd1),
    .din3(2'd3),
    .din4(2'd3),
    .din5(2'd1),
    .din6(2'd0),
    .din7(2'd0),
    .din8(2'd0),
    .din9(2'd0),
    .def(sum_fu_1017_p21),
    .sel(select_ln15_3_reg_2360_pp0_iter1_reg),
    .dout(sum_fu_1017_p23)
);

top_mul_4ns_11ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 13 ))
mul_4ns_11ns_13_1_1_U308(
    .din0(mul_ln27_1_fu_1067_p0),
    .din1(mul_ln27_1_fu_1067_p1),
    .dout(mul_ln27_1_fu_1067_p2)
);

top_mul_4ns_10ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 13 ))
mul_4ns_10ns_13_1_1_U309(
    .din0(mul_ln27_fu_1073_p0),
    .din1(mul_ln27_fu_1073_p1),
    .dout(mul_ln27_fu_1073_p2)
);

top_mul_10ns_12ns_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 21 ))
mul_10ns_12ns_21_1_1_U310(
    .din0(mul_ln20_fu_1082_p0),
    .din1(mul_ln20_fu_1082_p1),
    .dout(mul_ln20_fu_1082_p2)
);

top_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U311(
    .din0(mul_ln27_2_fu_1132_p0),
    .din1(mul_ln27_2_fu_1132_p1),
    .dout(mul_ln27_2_fu_1132_p2)
);

top_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U312(
    .din0(mul_ln27_3_fu_1168_p0),
    .din1(mul_ln27_3_fu_1168_p1),
    .dout(mul_ln27_3_fu_1168_p2)
);

top_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U313(
    .din0(mul_ln27_4_fu_1201_p0),
    .din1(mul_ln27_4_fu_1201_p1),
    .dout(mul_ln27_4_fu_1201_p2)
);

top_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U314(
    .din0(mul_ln27_5_fu_1237_p0),
    .din1(mul_ln27_5_fu_1237_p1),
    .dout(mul_ln27_5_fu_1237_p2)
);

top_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U315(
    .din0(mul_ln27_6_fu_1267_p0),
    .din1(mul_ln27_6_fu_1267_p1),
    .dout(mul_ln27_6_fu_1267_p2)
);

top_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U316(
    .din0(mul_ln27_7_fu_1389_p0),
    .din1(mul_ln27_7_fu_1389_p1),
    .dout(mul_ln27_7_fu_1389_p2)
);

top_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U317(
    .din0(mul_ln27_8_fu_1417_p0),
    .din1(mul_ln27_8_fu_1417_p1),
    .dout(mul_ln27_8_fu_1417_p2)
);

top_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U318(
    .din0(mul_ln27_9_fu_1445_p0),
    .din1(mul_ln27_9_fu_1445_p1),
    .dout(mul_ln27_9_fu_1445_p2)
);

top_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U319(
    .din0(mul_ln27_10_fu_1473_p0),
    .din1(mul_ln27_10_fu_1473_p1),
    .dout(mul_ln27_10_fu_1473_p2)
);

top_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U320(
    .din0(mul_ln27_11_fu_1498_p0),
    .din1(mul_ln27_11_fu_1498_p1),
    .dout(mul_ln27_11_fu_1498_p2)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_11_3_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 4 ),
    .CASE1( 3'h3 ),
    .din1_WIDTH( 4 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 4 ),
    .CASE3( 3'h4 ),
    .din3_WIDTH( 4 ),
    .CASE4( 3'h2 ),
    .din4_WIDTH( 4 ),
    .def_WIDTH( 4 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 4 ))
sparsemux_11_3_4_1_1_U321(
    .din0(p_ZL10fc1_weight_0_q1),
    .din1(p_ZL10fc1_weight_2_q1),
    .din2(w_val_fu_1535_p6),
    .din3(p_ZL10fc1_weight_6_q1),
    .din4(p_ZL10fc1_weight_8_q1),
    .def(w_val_fu_1535_p11),
    .sel(trunc_ln27_fu_1514_p1),
    .dout(w_val_fu_1535_p13)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_11_3_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 4 ),
    .CASE1( 3'h3 ),
    .din1_WIDTH( 4 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 4 ),
    .CASE3( 3'h4 ),
    .din3_WIDTH( 4 ),
    .CASE4( 3'h2 ),
    .din4_WIDTH( 4 ),
    .def_WIDTH( 4 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 4 ))
sparsemux_11_3_4_1_1_U322(
    .din0(w_val_1_fu_1567_p2),
    .din1(p_ZL10fc1_weight_3_q1),
    .din2(p_ZL10fc1_weight_5_q1),
    .din3(p_ZL10fc1_weight_7_q1),
    .din4(p_ZL10fc1_weight_9_q1),
    .def(w_val_1_fu_1567_p11),
    .sel(trunc_ln27_fu_1514_p1),
    .dout(w_val_1_fu_1567_p13)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_11_3_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h2 ),
    .din0_WIDTH( 4 ),
    .CASE1( 3'h0 ),
    .din1_WIDTH( 4 ),
    .CASE2( 3'h3 ),
    .din2_WIDTH( 4 ),
    .CASE3( 3'h1 ),
    .din3_WIDTH( 4 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 4 ),
    .def_WIDTH( 4 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 4 ))
sparsemux_11_3_4_1_1_U323(
    .din0(p_ZL10fc1_weight_0_q0),
    .din1(p_ZL10fc1_weight_2_q0),
    .din2(w_val_2_fu_1599_p6),
    .din3(p_ZL10fc1_weight_6_q0),
    .din4(p_ZL10fc1_weight_8_q0),
    .def(w_val_2_fu_1599_p11),
    .sel(trunc_ln27_fu_1514_p1),
    .dout(w_val_2_fu_1599_p13)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_11_3_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h2 ),
    .din0_WIDTH( 4 ),
    .CASE1( 3'h0 ),
    .din1_WIDTH( 4 ),
    .CASE2( 3'h3 ),
    .din2_WIDTH( 4 ),
    .CASE3( 3'h1 ),
    .din3_WIDTH( 4 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 4 ),
    .def_WIDTH( 4 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 4 ))
sparsemux_11_3_4_1_1_U324(
    .din0(w_val_3_fu_1631_p2),
    .din1(p_ZL10fc1_weight_3_q0),
    .din2(p_ZL10fc1_weight_5_q0),
    .din3(p_ZL10fc1_weight_7_q0),
    .din4(p_ZL10fc1_weight_9_q0),
    .def(w_val_3_fu_1631_p11),
    .sel(trunc_ln27_fu_1514_p1),
    .dout(w_val_3_fu_1631_p13)
);

top_mul_7ns_4s_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 11 ))
mul_7ns_4s_11_1_1_U325(
    .din0(mul_ln28_fu_1698_p0),
    .din1(w_val_reg_2633),
    .dout(mul_ln28_fu_1698_p2)
);

top_mul_7ns_4s_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 11 ))
mul_7ns_4s_11_1_1_U326(
    .din0(mul_ln28_1_fu_1711_p0),
    .din1(w_val_1_reg_2643),
    .dout(mul_ln28_1_fu_1711_p2)
);

top_mul_7ns_4s_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 11 ))
mul_7ns_4s_11_1_1_U327(
    .din0(mul_ln28_2_fu_1724_p0),
    .din1(w_val_2_reg_2653),
    .dout(mul_ln28_2_fu_1724_p2)
);

top_mul_7ns_4s_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 11 ))
mul_7ns_4s_11_1_1_U328(
    .din0(mul_ln28_3_fu_1737_p0),
    .din1(w_val_3_reg_2663),
    .dout(mul_ln28_3_fu_1737_p2)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_11_3_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 4 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 4 ),
    .CASE2( 3'h0 ),
    .din2_WIDTH( 4 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 4 ),
    .CASE4( 3'h1 ),
    .din4_WIDTH( 4 ),
    .def_WIDTH( 4 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 4 ))
sparsemux_11_3_4_1_1_U329(
    .din0(p_ZL10fc1_weight_0_q1),
    .din1(p_ZL10fc1_weight_2_q1),
    .din2(w_val_4_fu_1747_p6),
    .din3(p_ZL10fc1_weight_6_q1),
    .din4(p_ZL10fc1_weight_8_q1),
    .def(w_val_4_fu_1747_p11),
    .sel(trunc_ln27_reg_2623),
    .dout(w_val_4_fu_1747_p13)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_11_3_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 4 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 4 ),
    .CASE2( 3'h0 ),
    .din2_WIDTH( 4 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 4 ),
    .CASE4( 3'h1 ),
    .din4_WIDTH( 4 ),
    .def_WIDTH( 4 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 4 ))
sparsemux_11_3_4_1_1_U330(
    .din0(w_val_5_fu_1778_p2),
    .din1(p_ZL10fc1_weight_3_q1),
    .din2(p_ZL10fc1_weight_5_q1),
    .din3(p_ZL10fc1_weight_7_q1),
    .din4(p_ZL10fc1_weight_9_q1),
    .def(w_val_5_fu_1778_p11),
    .sel(trunc_ln27_reg_2623),
    .dout(w_val_5_fu_1778_p13)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_11_3_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h1 ),
    .din0_WIDTH( 4 ),
    .CASE1( 3'h4 ),
    .din1_WIDTH( 4 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 4 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 4 ),
    .CASE4( 3'h3 ),
    .din4_WIDTH( 4 ),
    .def_WIDTH( 4 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 4 ))
sparsemux_11_3_4_1_1_U331(
    .din0(p_ZL10fc1_weight_0_q0),
    .din1(p_ZL10fc1_weight_2_q0),
    .din2(w_val_6_fu_1809_p6),
    .din3(p_ZL10fc1_weight_6_q0),
    .din4(p_ZL10fc1_weight_8_q0),
    .def(w_val_6_fu_1809_p11),
    .sel(trunc_ln27_reg_2623),
    .dout(w_val_6_fu_1809_p13)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_11_3_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h1 ),
    .din0_WIDTH( 4 ),
    .CASE1( 3'h4 ),
    .din1_WIDTH( 4 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 4 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 4 ),
    .CASE4( 3'h3 ),
    .din4_WIDTH( 4 ),
    .def_WIDTH( 4 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 4 ))
sparsemux_11_3_4_1_1_U332(
    .din0(w_val_7_fu_1840_p2),
    .din1(p_ZL10fc1_weight_3_q0),
    .din2(p_ZL10fc1_weight_5_q0),
    .din3(p_ZL10fc1_weight_7_q0),
    .din4(p_ZL10fc1_weight_9_q0),
    .def(w_val_7_fu_1840_p11),
    .sel(trunc_ln27_reg_2623),
    .dout(w_val_7_fu_1840_p13)
);

top_mul_7ns_4s_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 11 ))
mul_7ns_4s_11_1_1_U333(
    .din0(mul_ln28_4_fu_1996_p0),
    .din1(w_val_4_reg_2823),
    .dout(mul_ln28_4_fu_1996_p2)
);

top_mul_7ns_4s_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 11 ))
mul_7ns_4s_11_1_1_U334(
    .din0(mul_ln28_5_fu_2032_p0),
    .din1(w_val_5_reg_2833),
    .dout(mul_ln28_5_fu_2032_p2)
);

top_mul_7ns_4s_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 11 ))
mul_7ns_4s_11_1_1_U335(
    .din0(mul_ln28_6_fu_2044_p0),
    .din1(w_val_6_reg_2843),
    .dout(mul_ln28_6_fu_2044_p2)
);

top_mul_7ns_4s_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 11 ))
mul_7ns_4s_11_1_1_U336(
    .din0(mul_ln28_7_fu_2056_p0),
    .din1(w_val_7_reg_2853),
    .dout(mul_ln28_7_fu_2056_p2)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_11_3_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h3 ),
    .din0_WIDTH( 4 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 4 ),
    .CASE2( 3'h4 ),
    .din2_WIDTH( 4 ),
    .CASE3( 3'h2 ),
    .din3_WIDTH( 4 ),
    .CASE4( 3'h0 ),
    .din4_WIDTH( 4 ),
    .def_WIDTH( 4 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 4 ))
sparsemux_11_3_4_1_1_U337(
    .din0(p_ZL10fc1_weight_0_q0),
    .din1(p_ZL10fc1_weight_2_q0),
    .din2(w_val_8_fu_2066_p6),
    .din3(p_ZL10fc1_weight_6_q0),
    .din4(p_ZL10fc1_weight_8_q0),
    .def(w_val_8_fu_2066_p11),
    .sel(trunc_ln27_reg_2623),
    .dout(w_val_8_fu_2066_p13)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_11_3_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h3 ),
    .din0_WIDTH( 4 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 4 ),
    .CASE2( 3'h4 ),
    .din2_WIDTH( 4 ),
    .CASE3( 3'h2 ),
    .din3_WIDTH( 4 ),
    .CASE4( 3'h0 ),
    .din4_WIDTH( 4 ),
    .def_WIDTH( 4 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 4 ))
sparsemux_11_3_4_1_1_U338(
    .din0(w_val_9_fu_2097_p2),
    .din1(p_ZL10fc1_weight_3_q0),
    .din2(p_ZL10fc1_weight_5_q0),
    .din3(p_ZL10fc1_weight_7_q0),
    .din4(p_ZL10fc1_weight_9_q0),
    .def(w_val_9_fu_2097_p11),
    .sel(trunc_ln27_reg_2623),
    .dout(w_val_9_fu_2097_p13)
);

top_mul_7ns_4s_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 11 ))
mul_7ns_4s_11_1_1_U339(
    .din0(mul_ln28_8_fu_2218_p0),
    .din1(w_val_8_reg_2948),
    .dout(mul_ln28_8_fu_2218_p2)
);

top_mul_7ns_4s_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 11 ))
mul_7ns_4s_11_1_1_U340(
    .din0(mul_ln28_9_fu_2230_p0),
    .din1(w_val_9_reg_2953),
    .dout(mul_ln28_9_fu_2230_p2)
);

top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter3_stage0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter3_stage0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter3_stage0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln15_fu_915_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_232 <= select_ln15_3_fu_971_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_232 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_228 <= 10'd0;
    end else if (((icmp_ln15_reg_2333 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        i_fu_228 <= i_1_fu_1001_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln15_fu_915_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_236 <= add_ln15_fu_921_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_236 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln20_1_reg_2443 <= add_ln20_1_fu_1253_p2;
        add_ln20_2_reg_2458 <= add_ln20_2_fu_1289_p2;
        add_ln20_3_reg_2468 <= add_ln20_3_fu_1300_p2;
        add_ln20_4_reg_2478 <= add_ln20_4_fu_1311_p2;
        add_ln20_5_reg_2488 <= add_ln20_5_fu_1322_p2;
        icmp_ln20_1_reg_2453 <= icmp_ln20_1_fu_1283_p2;
        icmp_ln20_1_reg_2453_pp0_iter2_reg <= icmp_ln20_1_reg_2453;
        icmp_ln20_2_reg_2463 <= icmp_ln20_2_fu_1294_p2;
        icmp_ln20_2_reg_2463_pp0_iter2_reg <= icmp_ln20_2_reg_2463;
        icmp_ln20_3_reg_2473 <= icmp_ln20_3_fu_1305_p2;
        icmp_ln20_3_reg_2473_pp0_iter2_reg <= icmp_ln20_3_reg_2473;
        icmp_ln20_4_reg_2483 <= icmp_ln20_4_fu_1316_p2;
        icmp_ln20_4_reg_2483_pp0_iter2_reg <= icmp_ln20_4_reg_2483;
        icmp_ln20_5_reg_2493 <= icmp_ln20_5_fu_1327_p2;
        icmp_ln20_5_reg_2493_pp0_iter2_reg <= icmp_ln20_5_reg_2493;
        icmp_ln20_6_reg_2371_pp0_iter1_reg <= icmp_ln20_6_reg_2371;
        icmp_ln20_6_reg_2371_pp0_iter2_reg <= icmp_ln20_6_reg_2371_pp0_iter1_reg;
        icmp_ln20_6_reg_2371_pp0_iter3_reg <= icmp_ln20_6_reg_2371_pp0_iter2_reg;
        input_4_load_reg_2828 <= input_4_q0;
        input_5_load_reg_2838 <= input_5_q0;
        input_6_load_reg_2848 <= input_6_q0;
        input_7_load_reg_2858 <= input_7_q0;
        input_8_load_reg_2888 <= input_8_q0;
        input_9_load_reg_2918 <= input_9_q0;
        mul_ln28_1_reg_2808 <= mul_ln28_1_fu_1711_p2;
        mul_ln28_2_reg_2813 <= mul_ln28_2_fu_1724_p2;
        mul_ln28_3_reg_2818 <= mul_ln28_3_fu_1737_p2;
        mul_ln28_reg_2803 <= mul_ln28_fu_1698_p2;
        sum_14_reg_2978 <= sum_14_fu_2294_p3;
        tmp_10_reg_2438 <= {{mul_ln27_5_fu_1237_p2[26:17]}};
        tmp_11_reg_2448 <= {{mul_ln27_6_fu_1267_p2[26:17]}};
        tmp_8_reg_2428 <= {{mul_ln27_3_fu_1168_p2[26:17]}};
        tmp_9_reg_2433 <= {{mul_ln27_4_fu_1201_p2[26:17]}};
        trunc_ln3_reg_2423 <= {{mul_ln27_2_fu_1132_p2[25:16]}};
        w_val_4_reg_2823 <= w_val_4_fu_1747_p13;
        w_val_5_reg_2833 <= w_val_5_fu_1778_p13;
        w_val_6_reg_2843 <= w_val_6_fu_1809_p13;
        w_val_7_reg_2853 <= w_val_7_fu_1840_p13;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln20_reg_2413 <= add_ln20_fu_1118_p2;
        icmp_ln20_reg_2418 <= icmp_ln20_fu_1123_p2;
        icmp_ln20_reg_2418_pp0_iter2_reg <= icmp_ln20_reg_2418;
        mul_ln27_1_reg_2381 <= mul_ln27_1_fu_1067_p2;
        mul_ln27_reg_2391 <= mul_ln27_fu_1073_p2;
        mul_ln28_8_reg_2968 <= mul_ln28_8_fu_2218_p2;
        mul_ln28_9_reg_2973 <= mul_ln28_9_fu_2230_p2;
        sum_8_reg_2958 <= sum_8_fu_2182_p3;
        sum_9_reg_2963 <= {{add_ln28_7_fu_2197_p2[10:3]}};
        sum_reg_2376 <= sum_fu_1017_p23;
        sum_reg_2376_pp0_iter2_reg <= sum_reg_2376;
        tmp_3_reg_2407 <= {{mul_ln27_1_fu_1067_p2[12:2]}};
        tmp_6_reg_2396 <= {{mul_ln20_fu_1082_p2[20:14]}};
        tmp_reg_2402 <= {{mul_ln27_1_fu_1067_p2[12:1]}};
        trunc_ln27_reg_2623 <= trunc_ln27_fu_1514_p1;
        w_val_1_reg_2643 <= w_val_1_fu_1567_p13;
        w_val_2_reg_2653 <= w_val_2_fu_1599_p13;
        w_val_3_reg_2663 <= w_val_3_fu_1631_p13;
        w_val_reg_2633 <= w_val_fu_1535_p13;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        first_iter_0_reg_2367 <= first_iter_0_fu_979_p2;
        first_iter_0_reg_2367_pp0_iter1_reg <= first_iter_0_reg_2367;
        first_iter_0_reg_2367_pp0_iter2_reg <= first_iter_0_reg_2367_pp0_iter1_reg;
        icmp_ln15_reg_2333 <= icmp_ln15_fu_915_p2;
        icmp_ln15_reg_2333_pp0_iter1_reg <= icmp_ln15_reg_2333;
        icmp_ln15_reg_2333_pp0_iter2_reg <= icmp_ln15_reg_2333_pp0_iter1_reg;
        icmp_ln15_reg_2333_pp0_iter3_reg <= icmp_ln15_reg_2333_pp0_iter2_reg;
        or_ln15_reg_2355 <= or_ln15_fu_959_p2;
        or_ln15_reg_2355_pp0_iter1_reg <= or_ln15_reg_2355;
        or_ln15_reg_2355_pp0_iter2_reg <= or_ln15_reg_2355_pp0_iter1_reg;
        select_ln15_3_reg_2360 <= select_ln15_3_fu_971_p3;
        select_ln15_3_reg_2360_pp0_iter1_reg <= select_ln15_3_reg_2360;
        select_ln15_reg_2342 <= select_ln15_fu_945_p3;
        select_ln15_reg_2342_pp0_iter1_reg <= select_ln15_reg_2342;
        sum_2_reg_2923 <= {{add_ln28_3_fu_1975_p2[10:3]}};
        sum_3_reg_2928 <= {{add_ln28_4_fu_2010_p2[10:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        icmp_ln20_6_reg_2371 <= icmp_ln20_6_fu_1006_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln28_5_reg_2933 <= mul_ln28_5_fu_2032_p2;
        mul_ln28_6_reg_2938 <= mul_ln28_6_fu_2044_p2;
        mul_ln28_7_reg_2943 <= mul_ln28_7_fu_2056_p2;
        tmp_12_reg_2598 <= {{mul_ln27_7_fu_1389_p2[26:17]}};
        tmp_13_reg_2603 <= {{mul_ln27_8_fu_1417_p2[26:17]}};
        tmp_14_reg_2608 <= {{mul_ln27_9_fu_1445_p2[26:17]}};
        tmp_15_reg_2613 <= {{mul_ln27_10_fu_1473_p2[26:17]}};
        tmp_16_reg_2618 <= {{mul_ln27_11_fu_1498_p2[26:17]}};
        w_val_8_reg_2948 <= w_val_8_fu_2066_p13;
        w_val_9_reg_2953 <= w_val_9_fu_2097_p13;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln15_reg_2333_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sum_1_fu_240 <= sum_14_fu_2294_p3;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_2333 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln15_reg_2333_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_1877)) begin
            ap_phi_mux_cmp2_new_phi_0_phi_fu_881_p4 = icmp_ln20_6_reg_2371;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_cmp2_new_phi_0_phi_fu_881_p4 = 1'd1;
        end else begin
            ap_phi_mux_cmp2_new_phi_0_phi_fu_881_p4 = icmp_ln20_6_reg_2371;
        end
    end else begin
        ap_phi_mux_cmp2_new_phi_0_phi_fu_881_p4 = icmp_ln20_6_reg_2371;
    end
end

always @ (*) begin
    if ((icmp_ln15_reg_2333_pp0_iter2_reg == 1'd0)) begin
        if ((first_iter_0_reg_2367_pp0_iter2_reg == 1'd1)) begin
            ap_phi_mux_sext_ln161_phi_fu_891_p4 = sext_ln16_fu_1887_p1;
        end else if ((first_iter_0_reg_2367_pp0_iter2_reg == 1'd0)) begin
            ap_phi_mux_sext_ln161_phi_fu_891_p4 = sum_1_fu_240;
        end else begin
            ap_phi_mux_sext_ln161_phi_fu_891_p4 = ap_phi_reg_pp0_iter3_sext_ln161_reg_888;
        end
    end else begin
        ap_phi_mux_sext_ln161_phi_fu_891_p4 = ap_phi_reg_pp0_iter3_sext_ln161_reg_888;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 4'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_232;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 10'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_228;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_236;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln20_6_reg_2371_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem0_blk_n_W = m_axi_gmem0_0_WREADY;
    end else begin
        gmem0_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_985_ce = 1'b1;
    end else begin
        grp_fu_985_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        input_0_ce0_local = 1'b1;
    end else begin
        input_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        input_1_ce0_local = 1'b1;
    end else begin
        input_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        input_2_ce0_local = 1'b1;
    end else begin
        input_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        input_3_ce0_local = 1'b1;
    end else begin
        input_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        input_4_ce0_local = 1'b1;
    end else begin
        input_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        input_5_ce0_local = 1'b1;
    end else begin
        input_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        input_6_ce0_local = 1'b1;
    end else begin
        input_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        input_7_ce0_local = 1'b1;
    end else begin
        input_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        input_8_ce0_local = 1'b1;
    end else begin
        input_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        input_9_ce0_local = 1'b1;
    end else begin
        input_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln20_6_reg_2371_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem0_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem0_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            p_ZL10fc1_weight_0_address0_local = zext_ln27_14_fu_1867_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_0_address0_local = zext_ln27_12_fu_1675_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_0_address0_local = zext_ln27_8_fu_1358_p1;
        end else begin
            p_ZL10fc1_weight_0_address0_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_0_address1_local = zext_ln27_10_fu_1659_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_0_address1_local = zext_ln27_6_fu_1341_p1;
        end else begin
            p_ZL10fc1_weight_0_address1_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_0_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_0_ce0_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_0_ce1_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            p_ZL10fc1_weight_1_address0_local = zext_ln27_15_fu_1875_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_1_address0_local = zext_ln27_13_fu_1683_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_1_address0_local = zext_ln27_9_fu_1366_p1;
        end else begin
            p_ZL10fc1_weight_1_address0_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_1_address1_local = zext_ln27_11_fu_1667_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_1_address1_local = zext_ln27_7_fu_1350_p1;
        end else begin
            p_ZL10fc1_weight_1_address1_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_1_ce0_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_1_ce1_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            p_ZL10fc1_weight_2_address0_local = zext_ln27_14_fu_1867_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_2_address0_local = zext_ln27_12_fu_1675_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_2_address0_local = zext_ln27_8_fu_1358_p1;
        end else begin
            p_ZL10fc1_weight_2_address0_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_2_address1_local = zext_ln27_10_fu_1659_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_2_address1_local = zext_ln27_6_fu_1341_p1;
        end else begin
            p_ZL10fc1_weight_2_address1_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_2_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_2_ce0_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_2_ce1_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            p_ZL10fc1_weight_3_address0_local = zext_ln27_15_fu_1875_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_3_address0_local = zext_ln27_13_fu_1683_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_3_address0_local = zext_ln27_9_fu_1366_p1;
        end else begin
            p_ZL10fc1_weight_3_address0_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_3_address1_local = zext_ln27_11_fu_1667_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_3_address1_local = zext_ln27_7_fu_1350_p1;
        end else begin
            p_ZL10fc1_weight_3_address1_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_3_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_3_ce0_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_3_ce1_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            p_ZL10fc1_weight_4_address0_local = zext_ln27_14_fu_1867_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_4_address0_local = zext_ln27_12_fu_1675_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_4_address0_local = zext_ln27_8_fu_1358_p1;
        end else begin
            p_ZL10fc1_weight_4_address0_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_4_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_4_address1_local = zext_ln27_10_fu_1659_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_4_address1_local = zext_ln27_6_fu_1341_p1;
        end else begin
            p_ZL10fc1_weight_4_address1_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_4_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_4_ce0_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_4_ce1_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            p_ZL10fc1_weight_5_address0_local = zext_ln27_15_fu_1875_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_5_address0_local = zext_ln27_13_fu_1683_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_5_address0_local = zext_ln27_9_fu_1366_p1;
        end else begin
            p_ZL10fc1_weight_5_address0_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_5_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_5_address1_local = zext_ln27_11_fu_1667_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_5_address1_local = zext_ln27_7_fu_1350_p1;
        end else begin
            p_ZL10fc1_weight_5_address1_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_5_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_5_ce0_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_5_ce1_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            p_ZL10fc1_weight_6_address0_local = zext_ln27_14_fu_1867_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_6_address0_local = zext_ln27_12_fu_1675_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_6_address0_local = zext_ln27_8_fu_1358_p1;
        end else begin
            p_ZL10fc1_weight_6_address0_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_6_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_6_address1_local = zext_ln27_10_fu_1659_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_6_address1_local = zext_ln27_6_fu_1341_p1;
        end else begin
            p_ZL10fc1_weight_6_address1_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_6_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_6_ce0_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_6_ce1_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            p_ZL10fc1_weight_7_address0_local = zext_ln27_15_fu_1875_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_7_address0_local = zext_ln27_13_fu_1683_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_7_address0_local = zext_ln27_9_fu_1366_p1;
        end else begin
            p_ZL10fc1_weight_7_address0_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_7_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_7_address1_local = zext_ln27_11_fu_1667_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_7_address1_local = zext_ln27_7_fu_1350_p1;
        end else begin
            p_ZL10fc1_weight_7_address1_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_7_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_7_ce0_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_7_ce1_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            p_ZL10fc1_weight_8_address0_local = zext_ln27_14_fu_1867_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_8_address0_local = zext_ln27_12_fu_1675_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_8_address0_local = zext_ln27_8_fu_1358_p1;
        end else begin
            p_ZL10fc1_weight_8_address0_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_8_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_8_address1_local = zext_ln27_10_fu_1659_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_8_address1_local = zext_ln27_6_fu_1341_p1;
        end else begin
            p_ZL10fc1_weight_8_address1_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_8_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_8_ce0_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_8_ce1_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            p_ZL10fc1_weight_9_address0_local = zext_ln27_15_fu_1875_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_9_address0_local = zext_ln27_13_fu_1683_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_9_address0_local = zext_ln27_9_fu_1366_p1;
        end else begin
            p_ZL10fc1_weight_9_address0_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_9_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL10fc1_weight_9_address1_local = zext_ln27_11_fu_1667_p1;
        end else if (((1'b0 == ap_block_pp0_stage0_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL10fc1_weight_9_address1_local = zext_ln27_7_fu_1350_p1;
        end else begin
            p_ZL10fc1_weight_9_address1_local = 'bx;
        end
    end else begin
        p_ZL10fc1_weight_9_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_9_ce0_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL10fc1_weight_9_ce1_local = 1'b1;
    end else begin
        p_ZL10fc1_weight_9_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter3_stage0) & (ap_idle_pp0_0to2 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15_3_fu_965_p2 = (ap_sig_allocacmp_c_load + 4'd1);

assign add_ln15_fu_921_p2 = (ap_sig_allocacmp_indvar_flatten_load + 10'd1);

assign add_ln20_1_fu_1253_p2 = (select_ln15_reg_2342_pp0_iter1_reg + 10'd5);

assign add_ln20_2_fu_1289_p2 = (select_ln15_reg_2342_pp0_iter1_reg + 10'd6);

assign add_ln20_3_fu_1300_p2 = (select_ln15_reg_2342_pp0_iter1_reg + 10'd7);

assign add_ln20_4_fu_1311_p2 = (select_ln15_reg_2342_pp0_iter1_reg + 10'd8);

assign add_ln20_5_fu_1322_p2 = (select_ln15_reg_2342_pp0_iter1_reg + 10'd9);

assign add_ln20_fu_1118_p2 = (select_ln15_reg_2342_pp0_iter1_reg + 10'd4);

assign add_ln24_1_fu_1191_p2 = (i_cast_fu_1148_p1 + or_ln20_1_fu_1184_p3);

assign add_ln24_2_fu_1227_p2 = (i_cast_fu_1148_p1 + or_ln20_2_fu_1220_p3);

assign add_ln24_3_fu_1258_p2 = (zext_ln20_fu_1217_p1 + mul_ln27_1_reg_2381);

assign add_ln24_4_fu_1380_p2 = (zext_ln16_3_fu_1374_p1 + mul_ln27_1_reg_2381);

assign add_ln24_5_fu_1408_p2 = (zext_ln16_4_fu_1377_p1 + mul_ln27_1_reg_2381);

assign add_ln24_6_fu_1436_p2 = (zext_ln16_5_fu_1405_p1 + mul_ln27_1_reg_2381);

assign add_ln24_7_fu_1464_p2 = (zext_ln16_6_fu_1433_p1 + mul_ln27_1_reg_2381);

assign add_ln24_8_fu_1489_p2 = (zext_ln16_7_fu_1461_p1 + mul_ln27_1_reg_2381);

assign add_ln24_fu_1158_p2 = (i_cast_fu_1148_p1 + or_ln_fu_1151_p3);

assign add_ln27_fu_1336_p2 = (zext_ln20_2_fu_1333_p1 + trunc_ln3_reg_2423);

assign add_ln28_1_fu_1929_p2 = (mul_ln28_1_reg_2808 + shl_ln28_1_fu_1921_p3);

assign add_ln28_2_fu_1952_p2 = (mul_ln28_2_reg_2813 + shl_ln28_2_fu_1944_p3);

assign add_ln28_3_fu_1975_p2 = (mul_ln28_3_reg_2818 + shl_ln28_3_fu_1967_p3);

assign add_ln28_4_fu_2010_p2 = (mul_ln28_4_fu_1996_p2 + shl_ln28_4_fu_2002_p3);

assign add_ln28_5_fu_2137_p2 = (mul_ln28_5_reg_2933 + shl_ln28_5_fu_2129_p3);

assign add_ln28_6_fu_2167_p2 = (mul_ln28_6_reg_2938 + shl_ln28_6_fu_2159_p3);

assign add_ln28_7_fu_2197_p2 = (mul_ln28_7_reg_2943 + shl_ln28_7_fu_2189_p3);

assign add_ln28_8_fu_2249_p2 = (mul_ln28_8_reg_2968 + shl_ln28_8_fu_2241_p3);

assign add_ln28_9_fu_2279_p2 = (mul_ln28_9_reg_2973 + shl_ln28_9_fu_2271_p3);

assign add_ln28_fu_1899_p2 = (mul_ln28_reg_2803 + shl_ln_fu_1891_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state13_io_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state13_io_grp1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state13_io_grp1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state13_io_grp1 = ((icmp_ln20_6_reg_2371_pp0_iter3_reg == 1'd0) & (m_axi_gmem0_0_WREADY == 1'b0));
end

always @ (*) begin
    ap_condition_1877 = ((icmp_ln15_reg_2333 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_phi_reg_pp0_iter3_sext_ln161_reg_888 = 'bx;

assign ap_ready = ap_ready_sig;

assign empty_fu_1914_p3 = ((or_ln15_reg_2355_pp0_iter2_reg[0:0] == 1'b1) ? tmp_2_fu_1904_p4 : ap_phi_mux_sext_ln161_phi_fu_891_p4);

assign exit_cond_91395_fu_939_p2 = ((ap_sig_allocacmp_i_load < 10'd784) ? 1'b1 : 1'b0);

assign first_iter_0_fu_979_p2 = ((select_ln15_fu_945_p3 == 10'd0) ? 1'b1 : 1'b0);

assign grp_fu_985_p0 = ((exit_cond_91395_fu_939_p2[0:0] == 1'b1) ? ap_sig_allocacmp_c_load : add_ln15_3_fu_965_p2);

assign i_1_fu_1001_p2 = (select_ln15_reg_2342 + 10'd10);

assign i_cast_fu_1148_p1 = select_ln15_reg_2342_pp0_iter1_reg;

assign icmp_ln15_fu_915_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 10'd790) ? 1'b1 : 1'b0);

assign icmp_ln20_1_fu_1283_p2 = ((add_ln20_1_fu_1253_p2 < 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln20_2_fu_1294_p2 = ((add_ln20_2_fu_1289_p2 < 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln20_3_fu_1305_p2 = ((add_ln20_3_fu_1300_p2 < 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln20_4_fu_1316_p2 = ((add_ln20_4_fu_1311_p2 < 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln20_5_fu_1327_p2 = ((add_ln20_5_fu_1322_p2 < 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln20_6_fu_1006_p2 = ((i_1_fu_1001_p2 < 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_1123_p2 = ((add_ln20_fu_1118_p2 < 10'd784) ? 1'b1 : 1'b0);

assign input_0_address0 = zext_ln16_fu_1518_p1;

assign input_0_ce0 = input_0_ce0_local;

assign input_1_address0 = zext_ln16_fu_1518_p1;

assign input_1_ce0 = input_1_ce0_local;

assign input_2_address0 = zext_ln16_fu_1518_p1;

assign input_2_ce0 = input_2_ce0_local;

assign input_3_address0 = zext_ln16_fu_1518_p1;

assign input_3_ce0 = input_3_ce0_local;

assign input_4_address0 = zext_ln16_fu_1518_p1;

assign input_4_ce0 = input_4_ce0_local;

assign input_5_address0 = zext_ln16_fu_1518_p1;

assign input_5_ce0 = input_5_ce0_local;

assign input_6_address0 = zext_ln16_fu_1518_p1;

assign input_6_ce0 = input_6_ce0_local;

assign input_7_address0 = zext_ln16_fu_1518_p1;

assign input_7_ce0 = input_7_ce0_local;

assign input_8_address0 = zext_ln16_fu_1518_p1;

assign input_8_ce0 = input_8_ce0_local;

assign input_9_address0 = zext_ln16_fu_1518_p1;

assign input_9_ce0 = input_9_ce0_local;

assign m_axi_gmem0_0_ARADDR = 64'd0;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 32'd0;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_ARVALID = 1'b0;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_RREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = sum_14_reg_2978;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 1'd1;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign mul_ln20_fu_1082_p0 = mul_ln20_fu_1082_p00;

assign mul_ln20_fu_1082_p00 = select_ln15_reg_2342_pp0_iter1_reg;

assign mul_ln20_fu_1082_p1 = 21'd1639;

assign mul_ln27_10_fu_1473_p0 = mul_ln27_10_fu_1473_p00;

assign mul_ln27_10_fu_1473_p00 = add_ln24_7_fu_1464_p2;

assign mul_ln27_10_fu_1473_p1 = 27'd13108;

assign mul_ln27_11_fu_1498_p0 = mul_ln27_11_fu_1498_p00;

assign mul_ln27_11_fu_1498_p00 = add_ln24_8_fu_1489_p2;

assign mul_ln27_11_fu_1498_p1 = 27'd13108;

assign mul_ln27_1_fu_1067_p0 = zext_ln15_fu_1064_p1;

assign mul_ln27_1_fu_1067_p1 = 13'd784;

assign mul_ln27_2_fu_1132_p0 = mul_ln27_2_fu_1132_p00;

assign mul_ln27_2_fu_1132_p00 = mul_ln27_reg_2391;

assign mul_ln27_2_fu_1132_p1 = 27'd13108;

assign mul_ln27_3_fu_1168_p0 = mul_ln27_3_fu_1168_p00;

assign mul_ln27_3_fu_1168_p00 = add_ln24_fu_1158_p2;

assign mul_ln27_3_fu_1168_p1 = 27'd13108;

assign mul_ln27_4_fu_1201_p0 = mul_ln27_4_fu_1201_p00;

assign mul_ln27_4_fu_1201_p00 = add_ln24_1_fu_1191_p2;

assign mul_ln27_4_fu_1201_p1 = 27'd13108;

assign mul_ln27_5_fu_1237_p0 = mul_ln27_5_fu_1237_p00;

assign mul_ln27_5_fu_1237_p00 = add_ln24_2_fu_1227_p2;

assign mul_ln27_5_fu_1237_p1 = 27'd13108;

assign mul_ln27_6_fu_1267_p0 = mul_ln27_6_fu_1267_p00;

assign mul_ln27_6_fu_1267_p00 = add_ln24_3_fu_1258_p2;

assign mul_ln27_6_fu_1267_p1 = 27'd13108;

assign mul_ln27_7_fu_1389_p0 = mul_ln27_7_fu_1389_p00;

assign mul_ln27_7_fu_1389_p00 = add_ln24_4_fu_1380_p2;

assign mul_ln27_7_fu_1389_p1 = 27'd13108;

assign mul_ln27_8_fu_1417_p0 = mul_ln27_8_fu_1417_p00;

assign mul_ln27_8_fu_1417_p00 = add_ln24_5_fu_1408_p2;

assign mul_ln27_8_fu_1417_p1 = 27'd13108;

assign mul_ln27_9_fu_1445_p0 = mul_ln27_9_fu_1445_p00;

assign mul_ln27_9_fu_1445_p00 = add_ln24_6_fu_1436_p2;

assign mul_ln27_9_fu_1445_p1 = 27'd13108;

assign mul_ln27_fu_1073_p0 = zext_ln15_fu_1064_p1;

assign mul_ln27_fu_1073_p1 = 13'd392;

assign mul_ln28_1_fu_1711_p0 = mul_ln28_1_fu_1711_p00;

assign mul_ln28_1_fu_1711_p00 = input_1_q0;

assign mul_ln28_2_fu_1724_p0 = mul_ln28_2_fu_1724_p00;

assign mul_ln28_2_fu_1724_p00 = input_2_q0;

assign mul_ln28_3_fu_1737_p0 = mul_ln28_3_fu_1737_p00;

assign mul_ln28_3_fu_1737_p00 = input_3_q0;

assign mul_ln28_4_fu_1996_p0 = mul_ln28_4_fu_1996_p00;

assign mul_ln28_4_fu_1996_p00 = input_4_load_reg_2828;

assign mul_ln28_5_fu_2032_p0 = mul_ln28_5_fu_2032_p00;

assign mul_ln28_5_fu_2032_p00 = input_5_load_reg_2838;

assign mul_ln28_6_fu_2044_p0 = mul_ln28_6_fu_2044_p00;

assign mul_ln28_6_fu_2044_p00 = input_6_load_reg_2848;

assign mul_ln28_7_fu_2056_p0 = mul_ln28_7_fu_2056_p00;

assign mul_ln28_7_fu_2056_p00 = input_7_load_reg_2858;

assign mul_ln28_8_fu_2218_p0 = mul_ln28_8_fu_2218_p00;

assign mul_ln28_8_fu_2218_p00 = input_8_load_reg_2888;

assign mul_ln28_9_fu_2230_p0 = mul_ln28_9_fu_2230_p00;

assign mul_ln28_9_fu_2230_p00 = input_9_load_reg_2918;

assign mul_ln28_fu_1698_p0 = mul_ln28_fu_1698_p00;

assign mul_ln28_fu_1698_p00 = input_0_q0;

assign or_ln15_fu_959_p2 = (xor_ln15_fu_953_p2 | ap_phi_mux_cmp2_new_phi_0_phi_fu_881_p4);

assign or_ln20_1_fu_1184_p3 = {{tmp_3_reg_2407}, {2'd2}};

assign or_ln20_2_fu_1220_p3 = {{tmp_3_reg_2407}, {2'd3}};

assign or_ln_fu_1151_p3 = {{tmp_reg_2402}, {1'd1}};

assign select_ln15_3_fu_971_p3 = ((exit_cond_91395_fu_939_p2[0:0] == 1'b1) ? ap_sig_allocacmp_c_load : add_ln15_3_fu_965_p2);

assign select_ln15_fu_945_p3 = ((exit_cond_91395_fu_939_p2[0:0] == 1'b1) ? ap_sig_allocacmp_i_load : 10'd0);

assign sext_ln16_fu_1887_p1 = $signed(sum_reg_2376_pp0_iter2_reg);

assign shl_ln28_1_fu_1921_p3 = {{empty_fu_1914_p3}, {3'd0}};

assign shl_ln28_2_fu_1944_p3 = {{tmp_5_fu_1934_p4}, {3'd0}};

assign shl_ln28_3_fu_1967_p3 = {{tmp_7_fu_1957_p4}, {3'd0}};

assign shl_ln28_4_fu_2002_p3 = {{sum_2_fu_1980_p4}, {3'd0}};

assign shl_ln28_5_fu_2129_p3 = {{sum_4_fu_2124_p3}, {3'd0}};

assign shl_ln28_6_fu_2159_p3 = {{sum_6_fu_2152_p3}, {3'd0}};

assign shl_ln28_7_fu_2189_p3 = {{sum_8_fu_2182_p3}, {3'd0}};

assign shl_ln28_8_fu_2241_p3 = {{sum_10_fu_2236_p3}, {3'd0}};

assign shl_ln28_9_fu_2271_p3 = {{sum_12_fu_2264_p3}, {3'd0}};

assign shl_ln_fu_1891_p3 = {{ap_phi_mux_sext_ln161_phi_fu_891_p4}, {3'd0}};

assign sum_10_fu_2236_p3 = ((icmp_ln20_3_reg_2473_pp0_iter2_reg[0:0] == 1'b1) ? sum_9_reg_2963 : sum_8_reg_2958);

assign sum_12_fu_2264_p3 = ((icmp_ln20_4_reg_2483_pp0_iter2_reg[0:0] == 1'b1) ? sum_16_fu_2254_p4 : sum_10_fu_2236_p3);

assign sum_14_fu_2294_p3 = ((icmp_ln20_5_reg_2493_pp0_iter2_reg[0:0] == 1'b1) ? sum_17_fu_2284_p4 : sum_12_fu_2264_p3);

assign sum_16_fu_2254_p4 = {{add_ln28_8_fu_2249_p2[10:3]}};

assign sum_17_fu_2284_p4 = {{add_ln28_9_fu_2279_p2[10:3]}};

assign sum_2_fu_1980_p4 = {{add_ln28_3_fu_1975_p2[10:3]}};

assign sum_4_fu_2124_p3 = ((icmp_ln20_reg_2418_pp0_iter2_reg[0:0] == 1'b1) ? sum_3_reg_2928 : sum_2_reg_2923);

assign sum_5_fu_2142_p4 = {{add_ln28_5_fu_2137_p2[10:3]}};

assign sum_6_fu_2152_p3 = ((icmp_ln20_1_reg_2453_pp0_iter2_reg[0:0] == 1'b1) ? sum_5_fu_2142_p4 : sum_4_fu_2124_p3);

assign sum_7_fu_2172_p4 = {{add_ln28_6_fu_2167_p2[10:3]}};

assign sum_8_fu_2182_p3 = ((icmp_ln20_2_reg_2463_pp0_iter2_reg[0:0] == 1'b1) ? sum_7_fu_2172_p4 : sum_6_fu_2152_p3);

assign sum_fu_1017_p21 = 'bx;

assign tmp_2_fu_1904_p4 = {{add_ln28_fu_1899_p2[10:3]}};

assign tmp_5_fu_1934_p4 = {{add_ln28_1_fu_1929_p2[10:3]}};

assign tmp_7_fu_1957_p4 = {{add_ln28_2_fu_1952_p2[10:3]}};

assign trunc_ln27_fu_1514_p1 = grp_fu_985_p2[2:0];

assign w_val_1_fu_1567_p11 = 'bx;

assign w_val_1_fu_1567_p2 = $signed(p_ZL10fc1_weight_1_q1);

assign w_val_2_fu_1599_p11 = 'bx;

assign w_val_2_fu_1599_p6 = $signed(p_ZL10fc1_weight_4_q0);

assign w_val_3_fu_1631_p11 = 'bx;

assign w_val_3_fu_1631_p2 = $signed(p_ZL10fc1_weight_1_q0);

assign w_val_4_fu_1747_p11 = 'bx;

assign w_val_4_fu_1747_p6 = $signed(p_ZL10fc1_weight_4_q1);

assign w_val_5_fu_1778_p11 = 'bx;

assign w_val_5_fu_1778_p2 = $signed(p_ZL10fc1_weight_1_q1);

assign w_val_6_fu_1809_p11 = 'bx;

assign w_val_6_fu_1809_p6 = $signed(p_ZL10fc1_weight_4_q0);

assign w_val_7_fu_1840_p11 = 'bx;

assign w_val_7_fu_1840_p2 = $signed(p_ZL10fc1_weight_1_q0);

assign w_val_8_fu_2066_p11 = 'bx;

assign w_val_8_fu_2066_p6 = $signed(p_ZL10fc1_weight_4_q0);

assign w_val_9_fu_2097_p11 = 'bx;

assign w_val_9_fu_2097_p2 = $signed(p_ZL10fc1_weight_1_q0);

assign w_val_fu_1535_p11 = 'bx;

assign w_val_fu_1535_p6 = $signed(p_ZL10fc1_weight_4_q1);

assign xor_ln15_fu_953_p2 = (exit_cond_91395_fu_939_p2 ^ 1'd1);

assign zext_ln15_fu_1064_p1 = select_ln15_3_reg_2360_pp0_iter1_reg;

assign zext_ln16_3_fu_1374_p1 = add_ln20_1_reg_2443;

assign zext_ln16_4_fu_1377_p1 = add_ln20_2_reg_2458;

assign zext_ln16_5_fu_1405_p1 = add_ln20_3_reg_2468;

assign zext_ln16_6_fu_1433_p1 = add_ln20_4_reg_2478;

assign zext_ln16_7_fu_1461_p1 = add_ln20_5_reg_2488;

assign zext_ln16_fu_1518_p1 = tmp_6_reg_2396;

assign zext_ln20_2_fu_1333_p1 = tmp_6_reg_2396;

assign zext_ln20_fu_1217_p1 = add_ln20_reg_2413;

assign zext_ln27_10_fu_1659_p1 = tmp_11_reg_2448;

assign zext_ln27_11_fu_1667_p1 = tmp_12_reg_2598;

assign zext_ln27_12_fu_1675_p1 = tmp_13_reg_2603;

assign zext_ln27_13_fu_1683_p1 = tmp_14_reg_2608;

assign zext_ln27_14_fu_1867_p1 = tmp_15_reg_2613;

assign zext_ln27_15_fu_1875_p1 = tmp_16_reg_2618;

assign zext_ln27_6_fu_1341_p1 = add_ln27_fu_1336_p2;

assign zext_ln27_7_fu_1350_p1 = tmp_8_reg_2428;

assign zext_ln27_8_fu_1358_p1 = tmp_9_reg_2433;

assign zext_ln27_9_fu_1366_p1 = tmp_10_reg_2438;

endmodule //top_dense_Pipeline_DENSE_OUTER_DENSE_INNER
