// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module top_conv1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        input_r,
        outputConv_0_address0,
        outputConv_0_ce0,
        outputConv_0_we0,
        outputConv_0_d0,
        outputConv_1_address0,
        outputConv_1_ce0,
        outputConv_1_we0,
        outputConv_1_d0,
        outputConv_2_address0,
        outputConv_2_ce0,
        outputConv_2_we0,
        outputConv_2_d0,
        outputConv_3_address0,
        outputConv_3_ce0,
        outputConv_3_we0,
        outputConv_3_d0,
        outputConv_4_address0,
        outputConv_4_ce0,
        outputConv_4_we0,
        outputConv_4_d0,
        outputConv_5_address0,
        outputConv_5_ce0,
        outputConv_5_we0,
        outputConv_5_d0,
        outputConv_6_address0,
        outputConv_6_ce0,
        outputConv_6_we0,
        outputConv_6_d0,
        outputConv_7_address0,
        outputConv_7_ce0,
        outputConv_7_we0,
        outputConv_7_d0
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [7:0] m_axi_gmem0_0_WDATA;
output  [0:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [7:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [63:0] input_r;
output  [9:0] outputConv_0_address0;
output   outputConv_0_ce0;
output   outputConv_0_we0;
output  [6:0] outputConv_0_d0;
output  [9:0] outputConv_1_address0;
output   outputConv_1_ce0;
output   outputConv_1_we0;
output  [6:0] outputConv_1_d0;
output  [9:0] outputConv_2_address0;
output   outputConv_2_ce0;
output   outputConv_2_we0;
output  [6:0] outputConv_2_d0;
output  [9:0] outputConv_3_address0;
output   outputConv_3_ce0;
output   outputConv_3_we0;
output  [6:0] outputConv_3_d0;
output  [9:0] outputConv_4_address0;
output   outputConv_4_ce0;
output   outputConv_4_we0;
output  [6:0] outputConv_4_d0;
output  [9:0] outputConv_5_address0;
output   outputConv_5_ce0;
output   outputConv_5_we0;
output  [6:0] outputConv_5_d0;
output  [9:0] outputConv_6_address0;
output   outputConv_6_ce0;
output   outputConv_6_we0;
output  [6:0] outputConv_6_d0;
output  [9:0] outputConv_7_address0;
output   outputConv_7_ce0;
output   outputConv_7_we0;
output  [6:0] outputConv_7_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem0_0_ARVALID;
reg[63:0] m_axi_gmem0_0_ARADDR;
reg[0:0] m_axi_gmem0_0_ARID;
reg[31:0] m_axi_gmem0_0_ARLEN;
reg[2:0] m_axi_gmem0_0_ARSIZE;
reg[1:0] m_axi_gmem0_0_ARBURST;
reg[1:0] m_axi_gmem0_0_ARLOCK;
reg[3:0] m_axi_gmem0_0_ARCACHE;
reg[2:0] m_axi_gmem0_0_ARPROT;
reg[3:0] m_axi_gmem0_0_ARQOS;
reg[3:0] m_axi_gmem0_0_ARREGION;
reg[0:0] m_axi_gmem0_0_ARUSER;
reg m_axi_gmem0_0_RREADY;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem0_blk_n_AR;
reg   [6:0] temp_address0;
reg    temp_ce0;
reg    temp_we0;
wire   [7:0] temp_q0;
reg    temp_ce1;
wire   [7:0] temp_q1;
reg   [6:0] temp_1_address0;
reg    temp_1_ce0;
reg    temp_1_we0;
wire   [7:0] temp_1_q0;
reg    temp_1_ce1;
wire   [7:0] temp_1_q1;
reg   [6:0] temp_2_address0;
reg    temp_2_ce0;
reg    temp_2_we0;
wire   [7:0] temp_2_q0;
reg    temp_2_ce1;
wire   [7:0] temp_2_q1;
reg   [6:0] temp_3_address0;
reg    temp_3_ce0;
reg    temp_3_we0;
wire   [7:0] temp_3_q0;
reg    temp_3_ce1;
wire   [7:0] temp_3_q1;
reg   [6:0] temp_4_address0;
reg    temp_4_ce0;
reg    temp_4_we0;
wire   [7:0] temp_4_q0;
reg    temp_4_ce1;
wire   [7:0] temp_4_q1;
reg   [6:0] temp_5_address0;
reg    temp_5_ce0;
reg    temp_5_we0;
wire   [7:0] temp_5_q0;
reg    temp_5_ce1;
wire   [7:0] temp_5_q1;
reg   [6:0] temp_6_address0;
reg    temp_6_ce0;
reg    temp_6_we0;
wire   [7:0] temp_6_q0;
reg    temp_6_ce1;
wire   [7:0] temp_6_q1;
reg   [6:0] temp_7_address0;
reg    temp_7_ce0;
reg    temp_7_we0;
wire   [7:0] temp_7_q0;
reg    temp_7_ce1;
wire   [7:0] temp_7_q1;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_ap_start;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_ap_done;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_ap_idle;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_ap_ready;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWID;
wire   [31:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWUSER;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_WVALID;
wire   [7:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_WDATA;
wire   [0:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_WSTRB;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_WID;
wire   [0:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_WUSER;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARID;
wire   [31:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARUSER;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_RREADY;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_BREADY;
wire   [6:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_7_address0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_7_ce0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_7_we0;
wire   [7:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_7_d0;
wire   [6:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_6_address0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_6_ce0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_6_we0;
wire   [7:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_6_d0;
wire   [6:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_5_address0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_5_ce0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_5_we0;
wire   [7:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_5_d0;
wire   [6:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_4_address0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_4_ce0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_4_we0;
wire   [7:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_4_d0;
wire   [6:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_3_address0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_3_ce0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_3_we0;
wire   [7:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_3_d0;
wire   [6:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_2_address0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_2_ce0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_2_we0;
wire   [7:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_2_d0;
wire   [6:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_1_address0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_1_ce0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_1_we0;
wire   [7:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_1_d0;
wire   [6:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_address0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_ce0;
wire    grp_conv1_Pipeline_LOAD_1_fu_113_temp_we0;
wire   [7:0] grp_conv1_Pipeline_LOAD_1_fu_113_temp_d0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_start;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_done;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_idle;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_ready;
wire   [9:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_7_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_7_ce0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_7_we0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_7_d0;
wire   [9:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_6_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_6_ce0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_6_we0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_6_d0;
wire   [9:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_5_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_5_ce0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_5_we0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_5_d0;
wire   [9:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_4_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_4_ce0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_4_we0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_4_d0;
wire   [9:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_3_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_3_ce0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_3_we0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_3_d0;
wire   [9:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_2_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_2_ce0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_2_we0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_2_d0;
wire   [9:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_1_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_1_ce0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_1_we0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_1_d0;
wire   [9:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_0_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_0_ce0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_0_we0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_0_d0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_ce0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_address1;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_ce1;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_1_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_1_ce0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_1_address1;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_1_ce1;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_2_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_2_ce0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_2_address1;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_2_ce1;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_3_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_3_ce0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_3_address1;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_3_ce1;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_4_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_4_ce0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_4_address1;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_4_ce1;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_5_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_5_ce0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_5_address1;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_5_ce1;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_6_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_6_ce0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_6_address1;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_6_ce1;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_7_address0;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_7_ce0;
wire   [6:0] grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_7_address1;
wire    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_7_ce1;
reg    grp_conv1_Pipeline_LOAD_1_fu_113_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 grp_conv1_Pipeline_LOAD_1_fu_113_ap_start_reg = 1'b0;
#0 grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_start_reg = 1'b0;
end

top_conv1_temp_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 98 ),
    .AddressWidth( 7 ))
temp_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_address0),
    .ce0(temp_ce0),
    .we0(temp_we0),
    .d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_d0),
    .q0(temp_q0),
    .address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_address1),
    .ce1(temp_ce1),
    .q1(temp_q1)
);

top_conv1_temp_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 98 ),
    .AddressWidth( 7 ))
temp_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_1_address0),
    .ce0(temp_1_ce0),
    .we0(temp_1_we0),
    .d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_1_d0),
    .q0(temp_1_q0),
    .address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_1_address1),
    .ce1(temp_1_ce1),
    .q1(temp_1_q1)
);

top_conv1_temp_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 98 ),
    .AddressWidth( 7 ))
temp_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_2_address0),
    .ce0(temp_2_ce0),
    .we0(temp_2_we0),
    .d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_2_d0),
    .q0(temp_2_q0),
    .address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_2_address1),
    .ce1(temp_2_ce1),
    .q1(temp_2_q1)
);

top_conv1_temp_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 98 ),
    .AddressWidth( 7 ))
temp_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_3_address0),
    .ce0(temp_3_ce0),
    .we0(temp_3_we0),
    .d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_3_d0),
    .q0(temp_3_q0),
    .address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_3_address1),
    .ce1(temp_3_ce1),
    .q1(temp_3_q1)
);

top_conv1_temp_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 98 ),
    .AddressWidth( 7 ))
temp_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_4_address0),
    .ce0(temp_4_ce0),
    .we0(temp_4_we0),
    .d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_4_d0),
    .q0(temp_4_q0),
    .address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_4_address1),
    .ce1(temp_4_ce1),
    .q1(temp_4_q1)
);

top_conv1_temp_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 98 ),
    .AddressWidth( 7 ))
temp_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_5_address0),
    .ce0(temp_5_ce0),
    .we0(temp_5_we0),
    .d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_5_d0),
    .q0(temp_5_q0),
    .address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_5_address1),
    .ce1(temp_5_ce1),
    .q1(temp_5_q1)
);

top_conv1_temp_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 98 ),
    .AddressWidth( 7 ))
temp_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_6_address0),
    .ce0(temp_6_ce0),
    .we0(temp_6_we0),
    .d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_6_d0),
    .q0(temp_6_q0),
    .address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_6_address1),
    .ce1(temp_6_ce1),
    .q1(temp_6_q1)
);

top_conv1_temp_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 98 ),
    .AddressWidth( 7 ))
temp_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_7_address0),
    .ce0(temp_7_ce0),
    .we0(temp_7_we0),
    .d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_7_d0),
    .q0(temp_7_q0),
    .address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_7_address1),
    .ce1(temp_7_ce1),
    .q1(temp_7_q1)
);

top_conv1_Pipeline_LOAD_1 grp_conv1_Pipeline_LOAD_1_fu_113(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv1_Pipeline_LOAD_1_fu_113_ap_start),
    .ap_done(grp_conv1_Pipeline_LOAD_1_fu_113_ap_done),
    .ap_idle(grp_conv1_Pipeline_LOAD_1_fu_113_ap_idle),
    .ap_ready(grp_conv1_Pipeline_LOAD_1_fu_113_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(1'b0),
    .m_axi_gmem0_0_AWADDR(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(1'b0),
    .m_axi_gmem0_0_WDATA(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(m_axi_gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(m_axi_gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(m_axi_gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(m_axi_gmem0_0_RLAST),
    .m_axi_gmem0_0_RID(m_axi_gmem0_0_RID),
    .m_axi_gmem0_0_RFIFONUM(m_axi_gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(m_axi_gmem0_0_RUSER),
    .m_axi_gmem0_0_RRESP(m_axi_gmem0_0_RRESP),
    .m_axi_gmem0_0_BVALID(1'b0),
    .m_axi_gmem0_0_BREADY(grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .input_r(input_r),
    .temp_7_address0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_7_address0),
    .temp_7_ce0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_7_ce0),
    .temp_7_we0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_7_we0),
    .temp_7_d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_7_d0),
    .temp_6_address0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_6_address0),
    .temp_6_ce0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_6_ce0),
    .temp_6_we0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_6_we0),
    .temp_6_d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_6_d0),
    .temp_5_address0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_5_address0),
    .temp_5_ce0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_5_ce0),
    .temp_5_we0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_5_we0),
    .temp_5_d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_5_d0),
    .temp_4_address0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_4_address0),
    .temp_4_ce0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_4_ce0),
    .temp_4_we0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_4_we0),
    .temp_4_d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_4_d0),
    .temp_3_address0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_3_address0),
    .temp_3_ce0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_3_ce0),
    .temp_3_we0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_3_we0),
    .temp_3_d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_3_d0),
    .temp_2_address0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_2_address0),
    .temp_2_ce0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_2_ce0),
    .temp_2_we0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_2_we0),
    .temp_2_d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_2_d0),
    .temp_1_address0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_1_address0),
    .temp_1_ce0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_1_ce0),
    .temp_1_we0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_1_we0),
    .temp_1_d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_1_d0),
    .temp_address0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_address0),
    .temp_ce0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_ce0),
    .temp_we0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_we0),
    .temp_d0(grp_conv1_Pipeline_LOAD_1_fu_113_temp_d0)
);

top_conv1_Pipeline_CO_1_H_1_W_1 grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_start),
    .ap_done(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_done),
    .ap_idle(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_idle),
    .ap_ready(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_ready),
    .outputConv_7_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_7_address0),
    .outputConv_7_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_7_ce0),
    .outputConv_7_we0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_7_we0),
    .outputConv_7_d0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_7_d0),
    .outputConv_6_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_6_address0),
    .outputConv_6_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_6_ce0),
    .outputConv_6_we0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_6_we0),
    .outputConv_6_d0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_6_d0),
    .outputConv_5_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_5_address0),
    .outputConv_5_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_5_ce0),
    .outputConv_5_we0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_5_we0),
    .outputConv_5_d0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_5_d0),
    .outputConv_4_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_4_address0),
    .outputConv_4_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_4_ce0),
    .outputConv_4_we0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_4_we0),
    .outputConv_4_d0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_4_d0),
    .outputConv_3_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_3_address0),
    .outputConv_3_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_3_ce0),
    .outputConv_3_we0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_3_we0),
    .outputConv_3_d0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_3_d0),
    .outputConv_2_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_2_address0),
    .outputConv_2_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_2_ce0),
    .outputConv_2_we0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_2_we0),
    .outputConv_2_d0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_2_d0),
    .outputConv_1_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_1_address0),
    .outputConv_1_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_1_ce0),
    .outputConv_1_we0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_1_we0),
    .outputConv_1_d0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_1_d0),
    .outputConv_0_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_0_address0),
    .outputConv_0_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_0_ce0),
    .outputConv_0_we0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_0_we0),
    .outputConv_0_d0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_0_d0),
    .temp_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_address0),
    .temp_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_ce0),
    .temp_q0(temp_q0),
    .temp_address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_address1),
    .temp_ce1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_ce1),
    .temp_q1(temp_q1),
    .temp_1_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_1_address0),
    .temp_1_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_1_ce0),
    .temp_1_q0(temp_1_q0),
    .temp_1_address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_1_address1),
    .temp_1_ce1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_1_ce1),
    .temp_1_q1(temp_1_q1),
    .temp_2_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_2_address0),
    .temp_2_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_2_ce0),
    .temp_2_q0(temp_2_q0),
    .temp_2_address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_2_address1),
    .temp_2_ce1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_2_ce1),
    .temp_2_q1(temp_2_q1),
    .temp_3_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_3_address0),
    .temp_3_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_3_ce0),
    .temp_3_q0(temp_3_q0),
    .temp_3_address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_3_address1),
    .temp_3_ce1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_3_ce1),
    .temp_3_q1(temp_3_q1),
    .temp_4_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_4_address0),
    .temp_4_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_4_ce0),
    .temp_4_q0(temp_4_q0),
    .temp_4_address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_4_address1),
    .temp_4_ce1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_4_ce1),
    .temp_4_q1(temp_4_q1),
    .temp_5_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_5_address0),
    .temp_5_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_5_ce0),
    .temp_5_q0(temp_5_q0),
    .temp_5_address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_5_address1),
    .temp_5_ce1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_5_ce1),
    .temp_5_q1(temp_5_q1),
    .temp_6_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_6_address0),
    .temp_6_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_6_ce0),
    .temp_6_q0(temp_6_q0),
    .temp_6_address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_6_address1),
    .temp_6_ce1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_6_ce1),
    .temp_6_q1(temp_6_q1),
    .temp_7_address0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_7_address0),
    .temp_7_ce0(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_7_ce0),
    .temp_7_q0(temp_7_q0),
    .temp_7_address1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_7_address1),
    .temp_7_ce1(grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_7_ce1),
    .temp_7_q1(temp_7_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_start_reg <= 1'b1;
        end else if ((grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_ready == 1'b1)) begin
            grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv1_Pipeline_LOAD_1_fu_113_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_conv1_Pipeline_LOAD_1_fu_113_ap_start_reg <= 1'b1;
        end else if ((grp_conv1_Pipeline_LOAD_1_fu_113_ap_ready == 1'b1)) begin
            grp_conv1_Pipeline_LOAD_1_fu_113_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((grp_conv1_Pipeline_LOAD_1_fu_113_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem0_0_ARREADY == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        gmem0_blk_n_AR = m_axi_gmem0_0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem0_0_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem0_0_ARADDR = input_r;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_0_ARADDR = grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARADDR;
    end else begin
        m_axi_gmem0_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_0_ARBURST = grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARBURST;
    end else begin
        m_axi_gmem0_0_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_0_ARCACHE = grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARCACHE;
    end else begin
        m_axi_gmem0_0_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_0_ARID = grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARID;
    end else begin
        m_axi_gmem0_0_ARID = 1'd0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem0_0_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem0_0_ARLEN = 64'd784;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_0_ARLEN = grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARLEN;
    end else begin
        m_axi_gmem0_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_0_ARLOCK = grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARLOCK;
    end else begin
        m_axi_gmem0_0_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_0_ARPROT = grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARPROT;
    end else begin
        m_axi_gmem0_0_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_0_ARQOS = grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARQOS;
    end else begin
        m_axi_gmem0_0_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_0_ARREGION = grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARREGION;
    end else begin
        m_axi_gmem0_0_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_0_ARSIZE = grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARSIZE;
    end else begin
        m_axi_gmem0_0_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_0_ARUSER = grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARUSER;
    end else begin
        m_axi_gmem0_0_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem0_0_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem0_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_0_ARVALID = grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_ARVALID;
    end else begin
        m_axi_gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_0_RREADY = grp_conv1_Pipeline_LOAD_1_fu_113_m_axi_gmem0_0_RREADY;
    end else begin
        m_axi_gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_1_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_1_address0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_1_address0;
    end else begin
        temp_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_1_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_1_ce0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_1_ce0;
    end else begin
        temp_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_1_ce1 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_1_ce1;
    end else begin
        temp_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_1_we0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_1_we0;
    end else begin
        temp_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_2_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_2_address0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_2_address0;
    end else begin
        temp_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_2_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_2_ce0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_2_ce0;
    end else begin
        temp_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_2_ce1 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_2_ce1;
    end else begin
        temp_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_2_we0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_2_we0;
    end else begin
        temp_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_3_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_3_address0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_3_address0;
    end else begin
        temp_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_3_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_3_ce0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_3_ce0;
    end else begin
        temp_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_3_ce1 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_3_ce1;
    end else begin
        temp_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_3_we0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_3_we0;
    end else begin
        temp_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_4_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_4_address0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_4_address0;
    end else begin
        temp_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_4_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_4_ce0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_4_ce0;
    end else begin
        temp_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_4_ce1 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_4_ce1;
    end else begin
        temp_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_4_we0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_4_we0;
    end else begin
        temp_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_5_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_5_address0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_5_address0;
    end else begin
        temp_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_5_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_5_ce0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_5_ce0;
    end else begin
        temp_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_5_ce1 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_5_ce1;
    end else begin
        temp_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_5_we0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_5_we0;
    end else begin
        temp_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_6_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_6_address0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_6_address0;
    end else begin
        temp_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_6_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_6_ce0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_6_ce0;
    end else begin
        temp_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_6_ce1 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_6_ce1;
    end else begin
        temp_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_6_we0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_6_we0;
    end else begin
        temp_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_7_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_7_address0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_7_address0;
    end else begin
        temp_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_7_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_7_ce0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_7_ce0;
    end else begin
        temp_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_7_ce1 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_7_ce1;
    end else begin
        temp_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_7_we0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_7_we0;
    end else begin
        temp_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_address0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_address0;
    end else begin
        temp_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_ce0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_ce0;
    end else begin
        temp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_ce1 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_temp_ce1;
    end else begin
        temp_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_we0 = grp_conv1_Pipeline_LOAD_1_fu_113_temp_we0;
    end else begin
        temp_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((m_axi_gmem0_0_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_conv1_Pipeline_LOAD_1_fu_113_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_start = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_ap_start_reg;

assign grp_conv1_Pipeline_LOAD_1_fu_113_ap_start = grp_conv1_Pipeline_LOAD_1_fu_113_ap_start_reg;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = 8'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 1'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign outputConv_0_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_0_address0;

assign outputConv_0_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_0_ce0;

assign outputConv_0_d0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_0_d0;

assign outputConv_0_we0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_0_we0;

assign outputConv_1_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_1_address0;

assign outputConv_1_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_1_ce0;

assign outputConv_1_d0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_1_d0;

assign outputConv_1_we0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_1_we0;

assign outputConv_2_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_2_address0;

assign outputConv_2_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_2_ce0;

assign outputConv_2_d0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_2_d0;

assign outputConv_2_we0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_2_we0;

assign outputConv_3_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_3_address0;

assign outputConv_3_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_3_ce0;

assign outputConv_3_d0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_3_d0;

assign outputConv_3_we0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_3_we0;

assign outputConv_4_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_4_address0;

assign outputConv_4_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_4_ce0;

assign outputConv_4_d0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_4_d0;

assign outputConv_4_we0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_4_we0;

assign outputConv_5_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_5_address0;

assign outputConv_5_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_5_ce0;

assign outputConv_5_d0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_5_d0;

assign outputConv_5_we0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_5_we0;

assign outputConv_6_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_6_address0;

assign outputConv_6_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_6_ce0;

assign outputConv_6_d0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_6_d0;

assign outputConv_6_we0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_6_we0;

assign outputConv_7_address0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_7_address0;

assign outputConv_7_ce0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_7_ce0;

assign outputConv_7_d0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_7_d0;

assign outputConv_7_we0 = grp_conv1_Pipeline_CO_1_H_1_W_1_fu_128_outputConv_7_we0;

endmodule //top_conv1
