// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module top_pool (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_address0,
        input_0_ce0,
        input_0_q0,
        input_1_address0,
        input_1_ce0,
        input_1_q0,
        input_2_address0,
        input_2_ce0,
        input_2_q0,
        input_3_address0,
        input_3_ce0,
        input_3_q0,
        input_4_address0,
        input_4_ce0,
        input_4_q0,
        input_5_address0,
        input_5_ce0,
        input_5_q0,
        input_6_address0,
        input_6_ce0,
        input_6_q0,
        input_7_address0,
        input_7_ce0,
        input_7_q0,
        outputPool_0_address0,
        outputPool_0_ce0,
        outputPool_0_we0,
        outputPool_0_d0,
        outputPool_1_address0,
        outputPool_1_ce0,
        outputPool_1_we0,
        outputPool_1_d0,
        outputPool_2_address0,
        outputPool_2_ce0,
        outputPool_2_we0,
        outputPool_2_d0,
        outputPool_3_address0,
        outputPool_3_ce0,
        outputPool_3_we0,
        outputPool_3_d0,
        outputPool_4_address0,
        outputPool_4_ce0,
        outputPool_4_we0,
        outputPool_4_d0,
        outputPool_5_address0,
        outputPool_5_ce0,
        outputPool_5_we0,
        outputPool_5_d0,
        outputPool_6_address0,
        outputPool_6_ce0,
        outputPool_6_we0,
        outputPool_6_d0,
        outputPool_7_address0,
        outputPool_7_ce0,
        outputPool_7_we0,
        outputPool_7_d0,
        outputPool_8_address0,
        outputPool_8_ce0,
        outputPool_8_we0,
        outputPool_8_d0,
        outputPool_9_address0,
        outputPool_9_ce0,
        outputPool_9_we0,
        outputPool_9_d0,
        outputPool_10_address0,
        outputPool_10_ce0,
        outputPool_10_we0,
        outputPool_10_d0,
        outputPool_11_address0,
        outputPool_11_ce0,
        outputPool_11_we0,
        outputPool_11_d0,
        outputPool_12_address0,
        outputPool_12_ce0,
        outputPool_12_we0,
        outputPool_12_d0,
        outputPool_13_address0,
        outputPool_13_ce0,
        outputPool_13_we0,
        outputPool_13_d0,
        outputPool_14_address0,
        outputPool_14_ce0,
        outputPool_14_we0,
        outputPool_14_d0,
        outputPool_15_address0,
        outputPool_15_ce0,
        outputPool_15_we0,
        outputPool_15_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] input_0_address0;
output   input_0_ce0;
input  [6:0] input_0_q0;
output  [9:0] input_1_address0;
output   input_1_ce0;
input  [6:0] input_1_q0;
output  [9:0] input_2_address0;
output   input_2_ce0;
input  [6:0] input_2_q0;
output  [9:0] input_3_address0;
output   input_3_ce0;
input  [6:0] input_3_q0;
output  [9:0] input_4_address0;
output   input_4_ce0;
input  [6:0] input_4_q0;
output  [9:0] input_5_address0;
output   input_5_ce0;
input  [6:0] input_5_q0;
output  [9:0] input_6_address0;
output   input_6_ce0;
input  [6:0] input_6_q0;
output  [9:0] input_7_address0;
output   input_7_ce0;
input  [6:0] input_7_q0;
output  [6:0] outputPool_0_address0;
output   outputPool_0_ce0;
output   outputPool_0_we0;
output  [6:0] outputPool_0_d0;
output  [6:0] outputPool_1_address0;
output   outputPool_1_ce0;
output   outputPool_1_we0;
output  [6:0] outputPool_1_d0;
output  [6:0] outputPool_2_address0;
output   outputPool_2_ce0;
output   outputPool_2_we0;
output  [6:0] outputPool_2_d0;
output  [6:0] outputPool_3_address0;
output   outputPool_3_ce0;
output   outputPool_3_we0;
output  [6:0] outputPool_3_d0;
output  [6:0] outputPool_4_address0;
output   outputPool_4_ce0;
output   outputPool_4_we0;
output  [6:0] outputPool_4_d0;
output  [6:0] outputPool_5_address0;
output   outputPool_5_ce0;
output   outputPool_5_we0;
output  [6:0] outputPool_5_d0;
output  [6:0] outputPool_6_address0;
output   outputPool_6_ce0;
output   outputPool_6_we0;
output  [6:0] outputPool_6_d0;
output  [6:0] outputPool_7_address0;
output   outputPool_7_ce0;
output   outputPool_7_we0;
output  [6:0] outputPool_7_d0;
output  [6:0] outputPool_8_address0;
output   outputPool_8_ce0;
output   outputPool_8_we0;
output  [6:0] outputPool_8_d0;
output  [6:0] outputPool_9_address0;
output   outputPool_9_ce0;
output   outputPool_9_we0;
output  [6:0] outputPool_9_d0;
output  [6:0] outputPool_10_address0;
output   outputPool_10_ce0;
output   outputPool_10_we0;
output  [6:0] outputPool_10_d0;
output  [6:0] outputPool_11_address0;
output   outputPool_11_ce0;
output   outputPool_11_we0;
output  [6:0] outputPool_11_d0;
output  [6:0] outputPool_12_address0;
output   outputPool_12_ce0;
output   outputPool_12_we0;
output  [6:0] outputPool_12_d0;
output  [6:0] outputPool_13_address0;
output   outputPool_13_ce0;
output   outputPool_13_we0;
output  [6:0] outputPool_13_d0;
output  [6:0] outputPool_14_address0;
output   outputPool_14_ce0;
output   outputPool_14_we0;
output  [6:0] outputPool_14_d0;
output  [6:0] outputPool_15_address0;
output   outputPool_15_ce0;
output   outputPool_15_we0;
output  [6:0] outputPool_15_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln15_fu_595_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln16_fu_610_p2;
reg   [0:0] icmp_ln16_reg_1223;
reg   [0:0] icmp_ln16_reg_1223_pp0_iter1_reg;
wire   [3:0] select_ln15_2_fu_622_p3;
reg   [3:0] select_ln15_2_reg_1230;
reg   [3:0] select_ln15_2_reg_1230_pp0_iter1_reg;
wire   [2:0] trunc_ln16_fu_634_p1;
reg   [2:0] trunc_ln16_reg_1240;
reg   [2:0] trunc_ln16_reg_1240_pp0_iter1_reg;
wire   [3:0] w_mid2_fu_708_p3;
reg   [3:0] w_mid2_reg_1245;
wire   [6:0] tmp_fu_752_p2;
reg   [6:0] tmp_reg_1251;
wire   [1:0] trunc_ln17_fu_788_p1;
reg   [1:0] trunc_ln17_reg_1264;
reg   [1:0] trunc_ln17_reg_1264_pp0_iter3_reg;
reg   [1:0] lshr_ln_reg_1272;
wire   [3:0] trunc_ln33_fu_963_p1;
reg   [3:0] trunc_ln33_reg_1357;
reg   [3:0] trunc_ln33_reg_1357_pp0_iter4_reg;
reg   [6:0] lshr_ln1_reg_1361;
reg   [6:0] lshr_ln1_reg_1361_pp0_iter4_reg;
wire   [6:0] max_val_5_fu_1063_p3;
reg   [6:0] max_val_5_reg_1366;
wire   [6:0] val_10_fu_1071_p11;
reg   [6:0] val_10_reg_1372;
wire   [6:0] val_6_fu_1094_p11;
reg   [6:0] val_6_reg_1378;
wire   [63:0] zext_ln29_5_fu_881_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln29_6_fu_908_p1;
wire   [63:0] zext_ln29_7_fu_949_p1;
wire   [63:0] zext_ln33_4_fu_1155_p1;
reg   [3:0] w_fu_168;
wire   [3:0] add_ln17_fu_802_p2;
wire    ap_loop_init;
reg   [3:0] h_fu_172;
wire   [3:0] select_ln16_fu_716_p3;
reg   [7:0] indvar_flatten_fu_176;
wire   [7:0] select_ln16_2_fu_644_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [3:0] co_fu_180;
reg   [3:0] ap_sig_allocacmp_co_load;
reg   [10:0] indvar_flatten12_fu_184;
wire   [10:0] add_ln15_fu_601_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten12_load;
reg    input_0_ce0_local;
reg   [9:0] input_0_address0_local;
reg    input_2_ce0_local;
reg   [9:0] input_2_address0_local;
reg    input_4_ce0_local;
reg   [9:0] input_4_address0_local;
reg    input_6_ce0_local;
reg   [9:0] input_6_address0_local;
reg    input_1_ce0_local;
reg   [9:0] input_1_address0_local;
reg    input_3_ce0_local;
reg   [9:0] input_3_address0_local;
reg    input_5_ce0_local;
reg   [9:0] input_5_address0_local;
reg    input_7_ce0_local;
reg   [9:0] input_7_address0_local;
reg    outputPool_14_we0_local;
wire   [6:0] max_val_8_fu_1132_p3;
reg    outputPool_14_ce0_local;
reg    outputPool_13_we0_local;
reg    outputPool_13_ce0_local;
reg    outputPool_12_we0_local;
reg    outputPool_12_ce0_local;
reg    outputPool_11_we0_local;
reg    outputPool_11_ce0_local;
reg    outputPool_10_we0_local;
reg    outputPool_10_ce0_local;
reg    outputPool_9_we0_local;
reg    outputPool_9_ce0_local;
reg    outputPool_8_we0_local;
reg    outputPool_8_ce0_local;
reg    outputPool_7_we0_local;
reg    outputPool_7_ce0_local;
reg    outputPool_6_we0_local;
reg    outputPool_6_ce0_local;
reg    outputPool_5_we0_local;
reg    outputPool_5_ce0_local;
reg    outputPool_4_we0_local;
reg    outputPool_4_ce0_local;
reg    outputPool_3_we0_local;
reg    outputPool_3_ce0_local;
reg    outputPool_2_we0_local;
reg    outputPool_2_ce0_local;
reg    outputPool_1_we0_local;
reg    outputPool_1_ce0_local;
reg    outputPool_0_we0_local;
reg    outputPool_0_ce0_local;
reg    outputPool_15_we0_local;
reg    outputPool_15_ce0_local;
wire   [3:0] add_ln15_2_fu_616_p2;
wire   [7:0] add_ln16_2_fu_638_p2;
wire   [0:0] icmp_ln17_fu_685_p2;
wire   [0:0] xor_ln15_fu_680_p2;
wire   [3:0] select_ln15_fu_673_p3;
wire   [0:0] and_ln15_fu_691_p2;
wire   [0:0] empty_fu_703_p2;
wire   [3:0] add_ln16_fu_697_p2;
wire   [4:0] tmp_2_fu_731_p3;
wire   [6:0] p_shl2_fu_724_p3;
wire   [6:0] zext_ln16_fu_738_p1;
wire   [6:0] zext_ln16_2_fu_748_p1;
wire   [6:0] sub_ln16_fu_742_p2;
wire   [6:0] tmp_4_fu_766_p3;
wire   [9:0] p_shl4_fu_758_p3;
wire   [9:0] zext_ln27_fu_774_p1;
wire   [9:0] sub_ln27_fu_778_p2;
wire   [7:0] tmp_3_fu_828_p3;
wire   [10:0] p_shl3_fu_821_p3;
wire   [10:0] zext_ln33_3_fu_835_p1;
wire   [9:0] p_shl_fu_845_p3;
wire   [9:0] zext_ln33_2_fu_818_p1;
wire   [4:0] shl_ln_fu_861_p3;
wire   [9:0] zext_ln29_4_fu_872_p1;
wire   [9:0] sub_ln29_fu_852_p2;
wire   [9:0] add_ln29_fu_875_p2;
wire   [12:0] zext_ln29_fu_868_p1;
wire   [12:0] grp_fu_1174_p3;
(* use_dsp = "no" *) wire   [12:0] add_ln27_7_fu_893_p2;
wire   [9:0] lshr_ln29_4_fu_898_p4;
wire   [11:0] tmp_1_fu_916_p4;
wire   [12:0] or_ln1_fu_925_p3;
wire   [12:0] add_ln27_8_fu_933_p2;
wire   [9:0] lshr_ln29_5_fu_939_p4;
wire   [10:0] zext_ln17_fu_858_p1;
wire   [10:0] sub_ln33_fu_839_p2;
wire   [10:0] add_ln33_fu_957_p2;
wire   [6:0] val_9_fu_1011_p9;
wire   [6:0] val_fu_1034_p9;
wire   [6:0] val_fu_1034_p11;
wire   [6:0] val_9_fu_1011_p11;
wire   [0:0] icmp_ln30_fu_1057_p2;
wire   [6:0] val_10_fu_1071_p9;
wire   [6:0] val_6_fu_1094_p9;
wire   [0:0] icmp_ln30_3_fu_1117_p2;
wire   [6:0] max_val_7_fu_1121_p3;
wire   [0:0] icmp_ln30_4_fu_1127_p2;
wire   [9:0] grp_fu_1174_p0;
wire   [3:0] grp_fu_1174_p1;
wire   [9:0] grp_fu_1174_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [12:0] grp_fu_1174_p10;
wire   [12:0] grp_fu_1174_p20;
wire   [1:0] val_9_fu_1011_p1;
wire   [1:0] val_9_fu_1011_p3;
wire  signed [1:0] val_9_fu_1011_p5;
wire  signed [1:0] val_9_fu_1011_p7;
wire   [1:0] val_fu_1034_p1;
wire   [1:0] val_fu_1034_p3;
wire  signed [1:0] val_fu_1034_p5;
wire  signed [1:0] val_fu_1034_p7;
wire  signed [1:0] val_10_fu_1071_p1;
wire  signed [1:0] val_10_fu_1071_p3;
wire   [1:0] val_10_fu_1071_p5;
wire   [1:0] val_10_fu_1071_p7;
wire  signed [1:0] val_6_fu_1094_p1;
wire  signed [1:0] val_6_fu_1094_p3;
wire   [1:0] val_6_fu_1094_p5;
wire   [1:0] val_6_fu_1094_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 w_fu_168 = 4'd0;
#0 h_fu_172 = 4'd0;
#0 indvar_flatten_fu_176 = 8'd0;
#0 co_fu_180 = 4'd0;
#0 indvar_flatten12_fu_184 = 11'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) top_sparsemux_9_2_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 7 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 7 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 7 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 7 ),
    .def_WIDTH( 7 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
sparsemux_9_2_7_1_1_U93(
    .din0(input_0_q0),
    .din1(input_2_q0),
    .din2(input_4_q0),
    .din3(input_6_q0),
    .def(val_9_fu_1011_p9),
    .sel(trunc_ln17_reg_1264_pp0_iter3_reg),
    .dout(val_9_fu_1011_p11)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_9_2_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 7 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 7 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 7 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 7 ),
    .def_WIDTH( 7 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
sparsemux_9_2_7_1_1_U94(
    .din0(input_1_q0),
    .din1(input_3_q0),
    .din2(input_5_q0),
    .din3(input_7_q0),
    .def(val_fu_1034_p9),
    .sel(trunc_ln17_reg_1264_pp0_iter3_reg),
    .dout(val_fu_1034_p11)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_9_2_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 7 ),
    .CASE1( 2'h3 ),
    .din1_WIDTH( 7 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 7 ),
    .CASE3( 2'h1 ),
    .din3_WIDTH( 7 ),
    .def_WIDTH( 7 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
sparsemux_9_2_7_1_1_U95(
    .din0(input_0_q0),
    .din1(input_2_q0),
    .din2(input_4_q0),
    .din3(input_6_q0),
    .def(val_10_fu_1071_p9),
    .sel(trunc_ln17_reg_1264_pp0_iter3_reg),
    .dout(val_10_fu_1071_p11)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_9_2_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 7 ),
    .CASE1( 2'h3 ),
    .din1_WIDTH( 7 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 7 ),
    .CASE3( 2'h1 ),
    .din3_WIDTH( 7 ),
    .def_WIDTH( 7 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
sparsemux_9_2_7_1_1_U96(
    .din0(input_1_q0),
    .din1(input_3_q0),
    .din2(input_5_q0),
    .din3(input_7_q0),
    .def(val_6_fu_1094_p9),
    .sel(trunc_ln17_reg_1264_pp0_iter3_reg),
    .dout(val_6_fu_1094_p11)
);

top_mac_muladd_10ns_4ns_10ns_13_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 13 ))
mac_muladd_10ns_4ns_10ns_13_4_1_U97(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1174_p0),
    .din1(grp_fu_1174_p1),
    .din2(grp_fu_1174_p2),
    .ce(1'b1),
    .dout(grp_fu_1174_p3)
);

top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln15_fu_595_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            co_fu_180 <= select_ln15_2_fu_622_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            co_fu_180 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            h_fu_172 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            h_fu_172 <= select_ln16_fu_716_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln15_fu_595_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten12_fu_184 <= add_ln15_fu_601_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten12_fu_184 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln15_fu_595_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_176 <= select_ln16_2_fu_644_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_176 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            w_fu_168 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            w_fu_168 <= add_ln17_fu_802_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln16_reg_1223 <= icmp_ln16_fu_610_p2;
        icmp_ln16_reg_1223_pp0_iter1_reg <= icmp_ln16_reg_1223;
        select_ln15_2_reg_1230 <= select_ln15_2_fu_622_p3;
        select_ln15_2_reg_1230_pp0_iter1_reg <= select_ln15_2_reg_1230;
        trunc_ln16_reg_1240 <= trunc_ln16_fu_634_p1;
        trunc_ln16_reg_1240_pp0_iter1_reg <= trunc_ln16_reg_1240;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        lshr_ln1_reg_1361 <= {{add_ln33_fu_957_p2[10:4]}};
        lshr_ln1_reg_1361_pp0_iter4_reg <= lshr_ln1_reg_1361;
        lshr_ln_reg_1272 <= {{w_mid2_fu_708_p3[3:2]}};
        max_val_5_reg_1366 <= max_val_5_fu_1063_p3;
        tmp_reg_1251 <= tmp_fu_752_p2;
        trunc_ln17_reg_1264 <= trunc_ln17_fu_788_p1;
        trunc_ln17_reg_1264_pp0_iter3_reg <= trunc_ln17_reg_1264;
        trunc_ln33_reg_1357 <= trunc_ln33_fu_963_p1;
        trunc_ln33_reg_1357_pp0_iter4_reg <= trunc_ln33_reg_1357;
        val_10_reg_1372 <= val_10_fu_1071_p11;
        val_6_reg_1378 <= val_6_fu_1094_p11;
        w_mid2_reg_1245 <= w_mid2_fu_708_p3;
    end
end

always @ (*) begin
    if (((icmp_ln15_fu_595_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_co_load = 4'd0;
    end else begin
        ap_sig_allocacmp_co_load = co_fu_180;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten12_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten12_load = indvar_flatten12_fu_184;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_176;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((trunc_ln17_reg_1264 == 2'd2)) begin
            input_0_address0_local = zext_ln29_6_fu_908_p1;
        end else if ((trunc_ln17_reg_1264 == 2'd0)) begin
            input_0_address0_local = zext_ln29_5_fu_881_p1;
        end else begin
            input_0_address0_local = 'bx;
        end
    end else begin
        input_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln17_reg_1264 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln17_reg_1264 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        input_0_ce0_local = 1'b1;
    end else begin
        input_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((trunc_ln17_reg_1264 == 2'd2)) begin
            input_1_address0_local = zext_ln29_7_fu_949_p1;
        end else if ((trunc_ln17_reg_1264 == 2'd0)) begin
            input_1_address0_local = zext_ln29_5_fu_881_p1;
        end else begin
            input_1_address0_local = 'bx;
        end
    end else begin
        input_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln17_reg_1264 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln17_reg_1264 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        input_1_ce0_local = 1'b1;
    end else begin
        input_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((trunc_ln17_reg_1264 == 2'd3)) begin
            input_2_address0_local = zext_ln29_6_fu_908_p1;
        end else if ((trunc_ln17_reg_1264 == 2'd1)) begin
            input_2_address0_local = zext_ln29_5_fu_881_p1;
        end else begin
            input_2_address0_local = 'bx;
        end
    end else begin
        input_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln17_reg_1264 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln17_reg_1264 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        input_2_ce0_local = 1'b1;
    end else begin
        input_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((trunc_ln17_reg_1264 == 2'd3)) begin
            input_3_address0_local = zext_ln29_7_fu_949_p1;
        end else if ((trunc_ln17_reg_1264 == 2'd1)) begin
            input_3_address0_local = zext_ln29_5_fu_881_p1;
        end else begin
            input_3_address0_local = 'bx;
        end
    end else begin
        input_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln17_reg_1264 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln17_reg_1264 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        input_3_ce0_local = 1'b1;
    end else begin
        input_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((trunc_ln17_reg_1264 == 2'd0)) begin
            input_4_address0_local = zext_ln29_6_fu_908_p1;
        end else if ((trunc_ln17_reg_1264 == 2'd2)) begin
            input_4_address0_local = zext_ln29_5_fu_881_p1;
        end else begin
            input_4_address0_local = 'bx;
        end
    end else begin
        input_4_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln17_reg_1264 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln17_reg_1264 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        input_4_ce0_local = 1'b1;
    end else begin
        input_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((trunc_ln17_reg_1264 == 2'd0)) begin
            input_5_address0_local = zext_ln29_7_fu_949_p1;
        end else if ((trunc_ln17_reg_1264 == 2'd2)) begin
            input_5_address0_local = zext_ln29_5_fu_881_p1;
        end else begin
            input_5_address0_local = 'bx;
        end
    end else begin
        input_5_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln17_reg_1264 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln17_reg_1264 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        input_5_ce0_local = 1'b1;
    end else begin
        input_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((trunc_ln17_reg_1264 == 2'd1)) begin
            input_6_address0_local = zext_ln29_6_fu_908_p1;
        end else if ((trunc_ln17_reg_1264 == 2'd3)) begin
            input_6_address0_local = zext_ln29_5_fu_881_p1;
        end else begin
            input_6_address0_local = 'bx;
        end
    end else begin
        input_6_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln17_reg_1264 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln17_reg_1264 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        input_6_ce0_local = 1'b1;
    end else begin
        input_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((trunc_ln17_reg_1264 == 2'd1)) begin
            input_7_address0_local = zext_ln29_7_fu_949_p1;
        end else if ((trunc_ln17_reg_1264 == 2'd3)) begin
            input_7_address0_local = zext_ln29_5_fu_881_p1;
        end else begin
            input_7_address0_local = 'bx;
        end
    end else begin
        input_7_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln17_reg_1264 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln17_reg_1264 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        input_7_ce0_local = 1'b1;
    end else begin
        input_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_0_ce0_local = 1'b1;
    end else begin
        outputPool_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_0_we0_local = 1'b1;
    end else begin
        outputPool_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_10_ce0_local = 1'b1;
    end else begin
        outputPool_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_10_we0_local = 1'b1;
    end else begin
        outputPool_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_11_ce0_local = 1'b1;
    end else begin
        outputPool_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_11_we0_local = 1'b1;
    end else begin
        outputPool_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_12_ce0_local = 1'b1;
    end else begin
        outputPool_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_12_we0_local = 1'b1;
    end else begin
        outputPool_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_13_ce0_local = 1'b1;
    end else begin
        outputPool_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_13_we0_local = 1'b1;
    end else begin
        outputPool_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_14_ce0_local = 1'b1;
    end else begin
        outputPool_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_14_we0_local = 1'b1;
    end else begin
        outputPool_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_15_ce0_local = 1'b1;
    end else begin
        outputPool_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_15_we0_local = 1'b1;
    end else begin
        outputPool_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_1_ce0_local = 1'b1;
    end else begin
        outputPool_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_1_we0_local = 1'b1;
    end else begin
        outputPool_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_2_ce0_local = 1'b1;
    end else begin
        outputPool_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_2_we0_local = 1'b1;
    end else begin
        outputPool_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_3_ce0_local = 1'b1;
    end else begin
        outputPool_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_3_we0_local = 1'b1;
    end else begin
        outputPool_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_4_ce0_local = 1'b1;
    end else begin
        outputPool_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_4_we0_local = 1'b1;
    end else begin
        outputPool_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_5_ce0_local = 1'b1;
    end else begin
        outputPool_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_5_we0_local = 1'b1;
    end else begin
        outputPool_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_6_ce0_local = 1'b1;
    end else begin
        outputPool_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_6_we0_local = 1'b1;
    end else begin
        outputPool_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_7_ce0_local = 1'b1;
    end else begin
        outputPool_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_7_we0_local = 1'b1;
    end else begin
        outputPool_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_8_ce0_local = 1'b1;
    end else begin
        outputPool_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_8_we0_local = 1'b1;
    end else begin
        outputPool_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_9_ce0_local = 1'b1;
    end else begin
        outputPool_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln33_reg_1357_pp0_iter4_reg == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        outputPool_9_we0_local = 1'b1;
    end else begin
        outputPool_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15_2_fu_616_p2 = (ap_sig_allocacmp_co_load + 4'd1);

assign add_ln15_fu_601_p2 = (ap_sig_allocacmp_indvar_flatten12_load + 11'd1);

assign add_ln16_2_fu_638_p2 = (ap_sig_allocacmp_indvar_flatten_load + 8'd1);

assign add_ln16_fu_697_p2 = (select_ln15_fu_673_p3 + 4'd1);

assign add_ln17_fu_802_p2 = (w_mid2_fu_708_p3 + 4'd1);

assign add_ln27_7_fu_893_p2 = (zext_ln29_fu_868_p1 + grp_fu_1174_p3);

assign add_ln27_8_fu_933_p2 = (zext_ln29_fu_868_p1 + or_ln1_fu_925_p3);

assign add_ln29_fu_875_p2 = (zext_ln29_4_fu_872_p1 + sub_ln29_fu_852_p2);

assign add_ln33_fu_957_p2 = (zext_ln17_fu_858_p1 + sub_ln33_fu_839_p2);

assign and_ln15_fu_691_p2 = (xor_ln15_fu_680_p2 & icmp_ln17_fu_685_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_703_p2 = (icmp_ln16_reg_1223_pp0_iter1_reg | and_ln15_fu_691_p2);

assign grp_fu_1174_p0 = 13'd784;

assign grp_fu_1174_p1 = grp_fu_1174_p10;

assign grp_fu_1174_p10 = select_ln15_2_fu_622_p3;

assign grp_fu_1174_p2 = grp_fu_1174_p20;

assign grp_fu_1174_p20 = sub_ln27_fu_778_p2;

assign icmp_ln15_fu_595_p2 = ((ap_sig_allocacmp_indvar_flatten12_load == 11'd1568) ? 1'b1 : 1'b0);

assign icmp_ln16_fu_610_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 8'd196) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_685_p2 = ((w_fu_168 == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln30_3_fu_1117_p2 = ((val_10_reg_1372 > max_val_5_reg_1366) ? 1'b1 : 1'b0);

assign icmp_ln30_4_fu_1127_p2 = ((val_6_reg_1378 > max_val_7_fu_1121_p3) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_1057_p2 = ((val_fu_1034_p11 > val_9_fu_1011_p11) ? 1'b1 : 1'b0);

assign input_0_address0 = input_0_address0_local;

assign input_0_ce0 = input_0_ce0_local;

assign input_1_address0 = input_1_address0_local;

assign input_1_ce0 = input_1_ce0_local;

assign input_2_address0 = input_2_address0_local;

assign input_2_ce0 = input_2_ce0_local;

assign input_3_address0 = input_3_address0_local;

assign input_3_ce0 = input_3_ce0_local;

assign input_4_address0 = input_4_address0_local;

assign input_4_ce0 = input_4_ce0_local;

assign input_5_address0 = input_5_address0_local;

assign input_5_ce0 = input_5_ce0_local;

assign input_6_address0 = input_6_address0_local;

assign input_6_ce0 = input_6_ce0_local;

assign input_7_address0 = input_7_address0_local;

assign input_7_ce0 = input_7_ce0_local;

assign lshr_ln29_4_fu_898_p4 = {{add_ln27_7_fu_893_p2[12:3]}};

assign lshr_ln29_5_fu_939_p4 = {{add_ln27_8_fu_933_p2[12:3]}};

assign max_val_5_fu_1063_p3 = ((icmp_ln30_fu_1057_p2[0:0] == 1'b1) ? val_fu_1034_p11 : val_9_fu_1011_p11);

assign max_val_7_fu_1121_p3 = ((icmp_ln30_3_fu_1117_p2[0:0] == 1'b1) ? val_10_reg_1372 : max_val_5_reg_1366);

assign max_val_8_fu_1132_p3 = ((icmp_ln30_4_fu_1127_p2[0:0] == 1'b1) ? val_6_reg_1378 : max_val_7_fu_1121_p3);

assign or_ln1_fu_925_p3 = {{tmp_1_fu_916_p4}, {1'd1}};

assign outputPool_0_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_0_ce0 = outputPool_0_ce0_local;

assign outputPool_0_d0 = max_val_8_fu_1132_p3;

assign outputPool_0_we0 = outputPool_0_we0_local;

assign outputPool_10_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_10_ce0 = outputPool_10_ce0_local;

assign outputPool_10_d0 = max_val_8_fu_1132_p3;

assign outputPool_10_we0 = outputPool_10_we0_local;

assign outputPool_11_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_11_ce0 = outputPool_11_ce0_local;

assign outputPool_11_d0 = max_val_8_fu_1132_p3;

assign outputPool_11_we0 = outputPool_11_we0_local;

assign outputPool_12_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_12_ce0 = outputPool_12_ce0_local;

assign outputPool_12_d0 = max_val_8_fu_1132_p3;

assign outputPool_12_we0 = outputPool_12_we0_local;

assign outputPool_13_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_13_ce0 = outputPool_13_ce0_local;

assign outputPool_13_d0 = max_val_8_fu_1132_p3;

assign outputPool_13_we0 = outputPool_13_we0_local;

assign outputPool_14_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_14_ce0 = outputPool_14_ce0_local;

assign outputPool_14_d0 = max_val_8_fu_1132_p3;

assign outputPool_14_we0 = outputPool_14_we0_local;

assign outputPool_15_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_15_ce0 = outputPool_15_ce0_local;

assign outputPool_15_d0 = max_val_8_fu_1132_p3;

assign outputPool_15_we0 = outputPool_15_we0_local;

assign outputPool_1_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_1_ce0 = outputPool_1_ce0_local;

assign outputPool_1_d0 = max_val_8_fu_1132_p3;

assign outputPool_1_we0 = outputPool_1_we0_local;

assign outputPool_2_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_2_ce0 = outputPool_2_ce0_local;

assign outputPool_2_d0 = max_val_8_fu_1132_p3;

assign outputPool_2_we0 = outputPool_2_we0_local;

assign outputPool_3_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_3_ce0 = outputPool_3_ce0_local;

assign outputPool_3_d0 = max_val_8_fu_1132_p3;

assign outputPool_3_we0 = outputPool_3_we0_local;

assign outputPool_4_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_4_ce0 = outputPool_4_ce0_local;

assign outputPool_4_d0 = max_val_8_fu_1132_p3;

assign outputPool_4_we0 = outputPool_4_we0_local;

assign outputPool_5_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_5_ce0 = outputPool_5_ce0_local;

assign outputPool_5_d0 = max_val_8_fu_1132_p3;

assign outputPool_5_we0 = outputPool_5_we0_local;

assign outputPool_6_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_6_ce0 = outputPool_6_ce0_local;

assign outputPool_6_d0 = max_val_8_fu_1132_p3;

assign outputPool_6_we0 = outputPool_6_we0_local;

assign outputPool_7_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_7_ce0 = outputPool_7_ce0_local;

assign outputPool_7_d0 = max_val_8_fu_1132_p3;

assign outputPool_7_we0 = outputPool_7_we0_local;

assign outputPool_8_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_8_ce0 = outputPool_8_ce0_local;

assign outputPool_8_d0 = max_val_8_fu_1132_p3;

assign outputPool_8_we0 = outputPool_8_we0_local;

assign outputPool_9_address0 = zext_ln33_4_fu_1155_p1;

assign outputPool_9_ce0 = outputPool_9_ce0_local;

assign outputPool_9_d0 = max_val_8_fu_1132_p3;

assign outputPool_9_we0 = outputPool_9_we0_local;

assign p_shl2_fu_724_p3 = {{trunc_ln16_reg_1240_pp0_iter1_reg}, {4'd0}};

assign p_shl3_fu_821_p3 = {{tmp_reg_1251}, {4'd0}};

assign p_shl4_fu_758_p3 = {{select_ln16_fu_716_p3}, {6'd32}};

assign p_shl_fu_845_p3 = {{tmp_reg_1251}, {3'd0}};

assign select_ln15_2_fu_622_p3 = ((icmp_ln16_fu_610_p2[0:0] == 1'b1) ? add_ln15_2_fu_616_p2 : ap_sig_allocacmp_co_load);

assign select_ln15_fu_673_p3 = ((icmp_ln16_reg_1223_pp0_iter1_reg[0:0] == 1'b1) ? 4'd0 : h_fu_172);

assign select_ln16_2_fu_644_p3 = ((icmp_ln16_fu_610_p2[0:0] == 1'b1) ? 8'd1 : add_ln16_2_fu_638_p2);

assign select_ln16_fu_716_p3 = ((and_ln15_fu_691_p2[0:0] == 1'b1) ? add_ln16_fu_697_p2 : select_ln15_fu_673_p3);

assign shl_ln_fu_861_p3 = {{w_mid2_reg_1245}, {1'd0}};

assign sub_ln16_fu_742_p2 = (p_shl2_fu_724_p3 - zext_ln16_fu_738_p1);

assign sub_ln27_fu_778_p2 = (p_shl4_fu_758_p3 - zext_ln27_fu_774_p1);

assign sub_ln29_fu_852_p2 = (p_shl_fu_845_p3 - zext_ln33_2_fu_818_p1);

assign sub_ln33_fu_839_p2 = (p_shl3_fu_821_p3 - zext_ln33_3_fu_835_p1);

assign tmp_1_fu_916_p4 = {{grp_fu_1174_p3[12:1]}};

assign tmp_2_fu_731_p3 = {{select_ln15_2_reg_1230_pp0_iter1_reg}, {1'd0}};

assign tmp_3_fu_828_p3 = {{tmp_reg_1251}, {1'd0}};

assign tmp_4_fu_766_p3 = {{select_ln16_fu_716_p3}, {3'd4}};

assign tmp_fu_752_p2 = (zext_ln16_2_fu_748_p1 + sub_ln16_fu_742_p2);

assign trunc_ln16_fu_634_p1 = select_ln15_2_fu_622_p3[2:0];

assign trunc_ln17_fu_788_p1 = w_mid2_fu_708_p3[1:0];

assign trunc_ln33_fu_963_p1 = add_ln33_fu_957_p2[3:0];

assign val_10_fu_1071_p9 = 'bx;

assign val_6_fu_1094_p9 = 'bx;

assign val_9_fu_1011_p9 = 'bx;

assign val_fu_1034_p9 = 'bx;

assign w_mid2_fu_708_p3 = ((empty_fu_703_p2[0:0] == 1'b1) ? 4'd0 : w_fu_168);

assign xor_ln15_fu_680_p2 = (icmp_ln16_reg_1223_pp0_iter1_reg ^ 1'd1);

assign zext_ln16_2_fu_748_p1 = select_ln16_fu_716_p3;

assign zext_ln16_fu_738_p1 = tmp_2_fu_731_p3;

assign zext_ln17_fu_858_p1 = w_mid2_reg_1245;

assign zext_ln27_fu_774_p1 = tmp_4_fu_766_p3;

assign zext_ln29_4_fu_872_p1 = lshr_ln_reg_1272;

assign zext_ln29_5_fu_881_p1 = add_ln29_fu_875_p2;

assign zext_ln29_6_fu_908_p1 = lshr_ln29_4_fu_898_p4;

assign zext_ln29_7_fu_949_p1 = lshr_ln29_5_fu_939_p4;

assign zext_ln29_fu_868_p1 = shl_ln_fu_861_p3;

assign zext_ln33_2_fu_818_p1 = tmp_reg_1251;

assign zext_ln33_3_fu_835_p1 = tmp_3_fu_828_p3;

assign zext_ln33_4_fu_1155_p1 = lshr_ln1_reg_1361_pp0_iter4_reg;

endmodule //top_pool
