-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_conv1_Pipeline_LOAD_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    input_r : IN STD_LOGIC_VECTOR (63 downto 0);
    temp_15_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_15_ce1 : OUT STD_LOGIC;
    temp_15_we1 : OUT STD_LOGIC;
    temp_15_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_14_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_14_ce1 : OUT STD_LOGIC;
    temp_14_we1 : OUT STD_LOGIC;
    temp_14_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_13_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_13_ce1 : OUT STD_LOGIC;
    temp_13_we1 : OUT STD_LOGIC;
    temp_13_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_12_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_12_ce1 : OUT STD_LOGIC;
    temp_12_we1 : OUT STD_LOGIC;
    temp_12_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_11_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_11_ce1 : OUT STD_LOGIC;
    temp_11_we1 : OUT STD_LOGIC;
    temp_11_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_10_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_10_ce1 : OUT STD_LOGIC;
    temp_10_we1 : OUT STD_LOGIC;
    temp_10_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_9_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_9_ce1 : OUT STD_LOGIC;
    temp_9_we1 : OUT STD_LOGIC;
    temp_9_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_8_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_8_ce1 : OUT STD_LOGIC;
    temp_8_we1 : OUT STD_LOGIC;
    temp_8_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_7_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_7_ce1 : OUT STD_LOGIC;
    temp_7_we1 : OUT STD_LOGIC;
    temp_7_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_6_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_6_ce1 : OUT STD_LOGIC;
    temp_6_we1 : OUT STD_LOGIC;
    temp_6_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_5_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_5_ce1 : OUT STD_LOGIC;
    temp_5_we1 : OUT STD_LOGIC;
    temp_5_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_4_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_4_ce1 : OUT STD_LOGIC;
    temp_4_we1 : OUT STD_LOGIC;
    temp_4_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_3_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_3_ce1 : OUT STD_LOGIC;
    temp_3_we1 : OUT STD_LOGIC;
    temp_3_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_2_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_2_ce1 : OUT STD_LOGIC;
    temp_2_we1 : OUT STD_LOGIC;
    temp_2_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_1_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_1_ce1 : OUT STD_LOGIC;
    temp_1_we1 : OUT STD_LOGIC;
    temp_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    temp_ce1 : OUT STD_LOGIC;
    temp_we1 : OUT STD_LOGIC;
    temp_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of top_conv1_Pipeline_LOAD_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv10_310 : STD_LOGIC_VECTOR (9 downto 0) := "1100010000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln31_fu_419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal trunc_ln31_fu_437_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln31_reg_525 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln31_reg_525_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal lshr_ln_reg_529 : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln_reg_529_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal gmem0_addr_read_reg_534 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln31_fu_490_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal i_fu_124 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln31_fu_425_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_6 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal temp_14_we1_local : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal temp_14_ce1_local : STD_LOGIC;
    signal temp_13_we1_local : STD_LOGIC;
    signal temp_13_ce1_local : STD_LOGIC;
    signal temp_12_we1_local : STD_LOGIC;
    signal temp_12_ce1_local : STD_LOGIC;
    signal temp_11_we1_local : STD_LOGIC;
    signal temp_11_ce1_local : STD_LOGIC;
    signal temp_10_we1_local : STD_LOGIC;
    signal temp_10_ce1_local : STD_LOGIC;
    signal temp_9_we1_local : STD_LOGIC;
    signal temp_9_ce1_local : STD_LOGIC;
    signal temp_8_we1_local : STD_LOGIC;
    signal temp_8_ce1_local : STD_LOGIC;
    signal temp_7_we1_local : STD_LOGIC;
    signal temp_7_ce1_local : STD_LOGIC;
    signal temp_6_we1_local : STD_LOGIC;
    signal temp_6_ce1_local : STD_LOGIC;
    signal temp_5_we1_local : STD_LOGIC;
    signal temp_5_ce1_local : STD_LOGIC;
    signal temp_4_we1_local : STD_LOGIC;
    signal temp_4_ce1_local : STD_LOGIC;
    signal temp_3_we1_local : STD_LOGIC;
    signal temp_3_ce1_local : STD_LOGIC;
    signal temp_2_we1_local : STD_LOGIC;
    signal temp_2_ce1_local : STD_LOGIC;
    signal temp_1_we1_local : STD_LOGIC;
    signal temp_1_ce1_local : STD_LOGIC;
    signal temp_we1_local : STD_LOGIC;
    signal temp_ce1_local : STD_LOGIC;
    signal temp_15_we1_local : STD_LOGIC;
    signal temp_15_ce1_local : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln31_fu_419_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_124 <= add_ln31_fu_425_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_124 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                lshr_ln_reg_529 <= ap_sig_allocacmp_i_6(9 downto 4);
                lshr_ln_reg_529_pp0_iter1_reg <= lshr_ln_reg_529;
                trunc_ln31_reg_525 <= trunc_ln31_fu_437_p1;
                trunc_ln31_reg_525_pp0_iter1_reg <= trunc_ln31_reg_525;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                gmem0_addr_read_reg_534 <= m_axi_gmem0_0_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln31_fu_425_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_6) + unsigned(ap_const_lv10_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem0_0_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem0_0_RVALID)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((m_axi_gmem0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem0_0_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln31_fu_419_p2)
    begin
        if (((icmp_ln31_fu_419_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_6_assign_proc : process(ap_CS_fsm_pp0_stage0, i_fu_124, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_6 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_i_6 <= i_fu_124;
        end if; 
    end process;


    gmem0_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem0_0_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem0_blk_n_R <= m_axi_gmem0_0_RVALID;
        else 
            gmem0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln31_fu_419_p2 <= "1" when (ap_sig_allocacmp_i_6 = ap_const_lv10_310) else "0";
    m_axi_gmem0_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem0_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_0_WDATA <= ap_const_lv8_0;
    m_axi_gmem0_0_WID <= ap_const_lv1_0;
    m_axi_gmem0_0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem0_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_WVALID <= ap_const_logic_0;
    temp_10_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_10_ce1 <= temp_10_ce1_local;

    temp_10_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_10_ce1_local <= ap_const_logic_1;
        else 
            temp_10_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_10_d1 <= gmem0_addr_read_reg_534;
    temp_10_we1 <= temp_10_we1_local;

    temp_10_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_A))) then 
            temp_10_we1_local <= ap_const_logic_1;
        else 
            temp_10_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_11_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_11_ce1 <= temp_11_ce1_local;

    temp_11_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_11_ce1_local <= ap_const_logic_1;
        else 
            temp_11_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_11_d1 <= gmem0_addr_read_reg_534;
    temp_11_we1 <= temp_11_we1_local;

    temp_11_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_B))) then 
            temp_11_we1_local <= ap_const_logic_1;
        else 
            temp_11_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_12_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_12_ce1 <= temp_12_ce1_local;

    temp_12_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_12_ce1_local <= ap_const_logic_1;
        else 
            temp_12_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_12_d1 <= gmem0_addr_read_reg_534;
    temp_12_we1 <= temp_12_we1_local;

    temp_12_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_C))) then 
            temp_12_we1_local <= ap_const_logic_1;
        else 
            temp_12_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_13_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_13_ce1 <= temp_13_ce1_local;

    temp_13_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_13_ce1_local <= ap_const_logic_1;
        else 
            temp_13_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_13_d1 <= gmem0_addr_read_reg_534;
    temp_13_we1 <= temp_13_we1_local;

    temp_13_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_D))) then 
            temp_13_we1_local <= ap_const_logic_1;
        else 
            temp_13_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_14_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_14_ce1 <= temp_14_ce1_local;

    temp_14_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_14_ce1_local <= ap_const_logic_1;
        else 
            temp_14_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_14_d1 <= gmem0_addr_read_reg_534;
    temp_14_we1 <= temp_14_we1_local;

    temp_14_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_E))) then 
            temp_14_we1_local <= ap_const_logic_1;
        else 
            temp_14_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_15_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_15_ce1 <= temp_15_ce1_local;

    temp_15_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_15_ce1_local <= ap_const_logic_1;
        else 
            temp_15_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_15_d1 <= gmem0_addr_read_reg_534;
    temp_15_we1 <= temp_15_we1_local;

    temp_15_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_F))) then 
            temp_15_we1_local <= ap_const_logic_1;
        else 
            temp_15_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_1_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_1_ce1 <= temp_1_ce1_local;

    temp_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_1_ce1_local <= ap_const_logic_1;
        else 
            temp_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_1_d1 <= gmem0_addr_read_reg_534;
    temp_1_we1 <= temp_1_we1_local;

    temp_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_1))) then 
            temp_1_we1_local <= ap_const_logic_1;
        else 
            temp_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_2_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_2_ce1 <= temp_2_ce1_local;

    temp_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_2_ce1_local <= ap_const_logic_1;
        else 
            temp_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_2_d1 <= gmem0_addr_read_reg_534;
    temp_2_we1 <= temp_2_we1_local;

    temp_2_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_2))) then 
            temp_2_we1_local <= ap_const_logic_1;
        else 
            temp_2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_3_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_3_ce1 <= temp_3_ce1_local;

    temp_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_3_ce1_local <= ap_const_logic_1;
        else 
            temp_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_3_d1 <= gmem0_addr_read_reg_534;
    temp_3_we1 <= temp_3_we1_local;

    temp_3_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_3))) then 
            temp_3_we1_local <= ap_const_logic_1;
        else 
            temp_3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_4_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_4_ce1 <= temp_4_ce1_local;

    temp_4_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_4_ce1_local <= ap_const_logic_1;
        else 
            temp_4_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_4_d1 <= gmem0_addr_read_reg_534;
    temp_4_we1 <= temp_4_we1_local;

    temp_4_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_4))) then 
            temp_4_we1_local <= ap_const_logic_1;
        else 
            temp_4_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_5_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_5_ce1 <= temp_5_ce1_local;

    temp_5_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_5_ce1_local <= ap_const_logic_1;
        else 
            temp_5_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_5_d1 <= gmem0_addr_read_reg_534;
    temp_5_we1 <= temp_5_we1_local;

    temp_5_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_5))) then 
            temp_5_we1_local <= ap_const_logic_1;
        else 
            temp_5_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_6_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_6_ce1 <= temp_6_ce1_local;

    temp_6_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_6_ce1_local <= ap_const_logic_1;
        else 
            temp_6_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_6_d1 <= gmem0_addr_read_reg_534;
    temp_6_we1 <= temp_6_we1_local;

    temp_6_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_6))) then 
            temp_6_we1_local <= ap_const_logic_1;
        else 
            temp_6_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_7_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_7_ce1 <= temp_7_ce1_local;

    temp_7_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_7_ce1_local <= ap_const_logic_1;
        else 
            temp_7_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_7_d1 <= gmem0_addr_read_reg_534;
    temp_7_we1 <= temp_7_we1_local;

    temp_7_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_7))) then 
            temp_7_we1_local <= ap_const_logic_1;
        else 
            temp_7_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_8_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_8_ce1 <= temp_8_ce1_local;

    temp_8_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_8_ce1_local <= ap_const_logic_1;
        else 
            temp_8_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_8_d1 <= gmem0_addr_read_reg_534;
    temp_8_we1 <= temp_8_we1_local;

    temp_8_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_8))) then 
            temp_8_we1_local <= ap_const_logic_1;
        else 
            temp_8_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_9_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_9_ce1 <= temp_9_ce1_local;

    temp_9_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_9_ce1_local <= ap_const_logic_1;
        else 
            temp_9_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_9_d1 <= gmem0_addr_read_reg_534;
    temp_9_we1 <= temp_9_we1_local;

    temp_9_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_9))) then 
            temp_9_we1_local <= ap_const_logic_1;
        else 
            temp_9_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_address1 <= zext_ln31_fu_490_p1(6 - 1 downto 0);
    temp_ce1 <= temp_ce1_local;

    temp_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            temp_ce1_local <= ap_const_logic_1;
        else 
            temp_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_d1 <= gmem0_addr_read_reg_534;
    temp_we1 <= temp_we1_local;

    temp_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, trunc_ln31_reg_525_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln31_reg_525_pp0_iter1_reg = ap_const_lv4_0))) then 
            temp_we1_local <= ap_const_logic_1;
        else 
            temp_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln31_fu_437_p1 <= ap_sig_allocacmp_i_6(4 - 1 downto 0);
    zext_ln31_fu_490_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_reg_529_pp0_iter1_reg),64));
end behav;
