-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity top_conv2_Pipeline_CI_2_p_ZL12conv2_weight_13_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 4; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 72
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);
 
          address2        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce2             : in std_logic; 
          q2              : out std_logic_vector(DataWidth-1 downto 0);
 
          address3        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce3             : in std_logic; 
          q3              : out std_logic_vector(DataWidth-1 downto 0);
 
          address4        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce4             : in std_logic; 
          q4              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of top_conv2_Pipeline_CI_2_p_ZL12conv2_weight_13_ROM_AUTO_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address2_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address3_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address4_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0010", 1 => "1110", 2 => "1111", 3 => "0001", 
    4 => "1100", 5 => "0000", 6 => "0001", 7 => "0001", 
    8 => "0000", 9 => "1111", 10 => "0000", 11 => "1110", 
    12 => "0000", 13 => "0000", 14 => "0000", 15 => "0010", 
    16 => "0001", 17 => "1111", 18 => "0001", 19 => "0000", 
    20 => "1111", 21 => "0011", 22 => "0001", 23 => "1110", 
    24 => "0101", 25 => "0001", 26 => "1110", 27 => "0100", 
    28 => "1110", 29 => "0000", 30 => "0101", 31 => "0001", 
    32 => "0000", 33 => "1110", 34 => "1111", 35 => "0001", 
    36 => "0000", 37 => "1110", 38 => "0010", 39 => "1111", 
    40 => "0010", 41 => "0000", 42 => "0001", 43 => "0000", 
    44 => "0000", 45 => "0001", 46 => "0001", 47 => "0000", 
    48 => "1100", 49 => "1110", 50 => "0001", 51 => "0001", 
    52 => "0000", 53 => "0010", 54 => "1110", 55 => "1111", 
    56 => "0001", 57 => "0010", 58 => "0000", 59 => "0000", 
    60 => "1101", 61 => "1111", 62 => "1111", 63 => "1110", 
    64 => "1011", 65 => "1111", 66 => "1111", 67 => "1111", 
    68 => "0000", 69 => "1111", 70 => "1111", 71 => "0001");

signal mem1 : mem_array := (
    0 => "0010", 1 => "1110", 2 => "1111", 3 => "0001", 
    4 => "1100", 5 => "0000", 6 => "0001", 7 => "0001", 
    8 => "0000", 9 => "1111", 10 => "0000", 11 => "1110", 
    12 => "0000", 13 => "0000", 14 => "0000", 15 => "0010", 
    16 => "0001", 17 => "1111", 18 => "0001", 19 => "0000", 
    20 => "1111", 21 => "0011", 22 => "0001", 23 => "1110", 
    24 => "0101", 25 => "0001", 26 => "1110", 27 => "0100", 
    28 => "1110", 29 => "0000", 30 => "0101", 31 => "0001", 
    32 => "0000", 33 => "1110", 34 => "1111", 35 => "0001", 
    36 => "0000", 37 => "1110", 38 => "0010", 39 => "1111", 
    40 => "0010", 41 => "0000", 42 => "0001", 43 => "0000", 
    44 => "0000", 45 => "0001", 46 => "0001", 47 => "0000", 
    48 => "1100", 49 => "1110", 50 => "0001", 51 => "0001", 
    52 => "0000", 53 => "0010", 54 => "1110", 55 => "1111", 
    56 => "0001", 57 => "0010", 58 => "0000", 59 => "0000", 
    60 => "1101", 61 => "1111", 62 => "1111", 63 => "1110", 
    64 => "1011", 65 => "1111", 66 => "1111", 67 => "1111", 
    68 => "0000", 69 => "1111", 70 => "1111", 71 => "0001");

signal mem2 : mem_array := (
    0 => "0010", 1 => "1110", 2 => "1111", 3 => "0001", 
    4 => "1100", 5 => "0000", 6 => "0001", 7 => "0001", 
    8 => "0000", 9 => "1111", 10 => "0000", 11 => "1110", 
    12 => "0000", 13 => "0000", 14 => "0000", 15 => "0010", 
    16 => "0001", 17 => "1111", 18 => "0001", 19 => "0000", 
    20 => "1111", 21 => "0011", 22 => "0001", 23 => "1110", 
    24 => "0101", 25 => "0001", 26 => "1110", 27 => "0100", 
    28 => "1110", 29 => "0000", 30 => "0101", 31 => "0001", 
    32 => "0000", 33 => "1110", 34 => "1111", 35 => "0001", 
    36 => "0000", 37 => "1110", 38 => "0010", 39 => "1111", 
    40 => "0010", 41 => "0000", 42 => "0001", 43 => "0000", 
    44 => "0000", 45 => "0001", 46 => "0001", 47 => "0000", 
    48 => "1100", 49 => "1110", 50 => "0001", 51 => "0001", 
    52 => "0000", 53 => "0010", 54 => "1110", 55 => "1111", 
    56 => "0001", 57 => "0010", 58 => "0000", 59 => "0000", 
    60 => "1101", 61 => "1111", 62 => "1111", 63 => "1110", 
    64 => "1011", 65 => "1111", 66 => "1111", 67 => "1111", 
    68 => "0000", 69 => "1111", 70 => "1111", 71 => "0001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_2: process (address2) 
begin
      address2_tmp <= address2;
--synthesis translate_off
      if (CONV_INTEGER(address2) > AddressRange-1) then
           address2_tmp <= (others => '0');
      else 
           address2_tmp <= address2;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_3: process (address3) 
begin
      address3_tmp <= address3;
--synthesis translate_off
      if (CONV_INTEGER(address3) > AddressRange-1) then
           address3_tmp <= (others => '0');
      else 
           address3_tmp <= address3;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_4: process (address4) 
begin
      address4_tmp <= address4;
--synthesis translate_off
      if (CONV_INTEGER(address4) > AddressRange-1) then
           address4_tmp <= (others => '0');
      else 
           address4_tmp <= address4;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;
 
        if (ce2 = '1') then  
            q2 <= mem1(CONV_INTEGER(address2_tmp)); 
        end if;
 
        if (ce3 = '1') then  
            q3 <= mem1(CONV_INTEGER(address3_tmp)); 
        end if;
 
        if (ce4 = '1') then  
            q4 <= mem2(CONV_INTEGER(address4_tmp)); 
        end if;

end if;
end process;

end rtl;

