// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module top_pool_Pipeline_CO_LOOP_H_LOOP_W_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        outputPool,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_address0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_ce0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_q0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_address1,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_ce1,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_q1,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_address0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_ce0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_q0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_address1,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_ce1,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_q1,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_address0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_ce0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_q0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_address1,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_ce1,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_q1,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_address0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_ce0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_q0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_address1,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_ce1,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_q1,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_address0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_ce0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_q0,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_address1,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_ce1,
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [7:0] m_axi_gmem0_0_WDATA;
output  [0:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [7:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [63:0] outputPool;
output  [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_address0;
output   pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_ce0;
input  [7:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_q0;
output  [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_address1;
output   pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_ce1;
input  [7:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_q1;
output  [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_address0;
output   pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_ce0;
input  [7:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_q0;
output  [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_address1;
output   pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_ce1;
input  [7:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_q1;
output  [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_address0;
output   pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_ce0;
input  [7:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_q0;
output  [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_address1;
output   pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_ce1;
input  [7:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_q1;
output  [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_address0;
output   pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_ce0;
input  [7:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_q0;
output  [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_address1;
output   pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_ce1;
input  [7:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_q1;
output  [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_address0;
output   pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_ce0;
input  [7:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_q0;
output  [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_address1;
output   pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_ce1;
input  [7:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_q1;

reg ap_idle;
reg m_axi_gmem0_0_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln23_fu_385_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_W;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [3:0] select_ln23_1_fu_452_p3;
reg   [3:0] select_ln23_1_reg_1054;
reg   [3:0] select_ln23_1_reg_1054_pp0_iter2_reg;
reg   [3:0] select_ln23_1_reg_1054_pp0_iter3_reg;
reg   [3:0] select_ln23_1_reg_1054_pp0_iter4_reg;
reg   [3:0] select_ln23_1_reg_1054_pp0_iter5_reg;
reg   [3:0] select_ln23_1_reg_1054_pp0_iter6_reg;
reg   [3:0] select_ln23_1_reg_1054_pp0_iter7_reg;
reg   [3:0] select_ln23_1_reg_1054_pp0_iter8_reg;
reg   [3:0] select_ln23_1_reg_1054_pp0_iter9_reg;
reg   [3:0] select_ln23_1_reg_1054_pp0_iter10_reg;
reg   [3:0] select_ln23_1_reg_1054_pp0_iter11_reg;
wire   [3:0] w_mid2_fu_472_p3;
reg   [3:0] w_mid2_reg_1059;
reg   [3:0] w_mid2_reg_1059_pp0_iter2_reg;
reg   [3:0] w_mid2_reg_1059_pp0_iter3_reg;
reg   [3:0] w_mid2_reg_1059_pp0_iter4_reg;
reg   [3:0] w_mid2_reg_1059_pp0_iter5_reg;
reg   [3:0] w_mid2_reg_1059_pp0_iter6_reg;
reg   [3:0] w_mid2_reg_1059_pp0_iter7_reg;
reg   [3:0] w_mid2_reg_1059_pp0_iter8_reg;
reg   [3:0] w_mid2_reg_1059_pp0_iter9_reg;
reg   [3:0] w_mid2_reg_1059_pp0_iter10_reg;
reg   [3:0] w_mid2_reg_1059_pp0_iter11_reg;
reg   [3:0] w_mid2_reg_1059_pp0_iter12_reg;
wire   [3:0] select_ln24_fu_480_p3;
reg   [3:0] select_ln24_reg_1065;
wire   [5:0] add_ln34_1_fu_504_p2;
reg   [5:0] add_ln34_1_reg_1072;
wire   [9:0] sub_ln34_1_fu_592_p2;
reg   [9:0] sub_ln34_1_reg_1077;
reg   [9:0] sub_ln34_1_reg_1077_pp0_iter3_reg;
reg   [9:0] sub_ln34_1_reg_1077_pp0_iter4_reg;
reg   [9:0] sub_ln34_1_reg_1077_pp0_iter5_reg;
reg   [9:0] sub_ln34_1_reg_1077_pp0_iter6_reg;
reg   [9:0] sub_ln34_1_reg_1077_pp0_iter7_reg;
reg   [9:0] sub_ln34_1_reg_1077_pp0_iter8_reg;
reg   [9:0] sub_ln34_1_reg_1077_pp0_iter9_reg;
reg   [9:0] sub_ln34_1_reg_1077_pp0_iter10_reg;
reg   [9:0] sub_ln34_1_reg_1077_pp0_iter11_reg;
wire   [4:0] shl_ln_fu_598_p3;
reg   [4:0] shl_ln_reg_1083;
reg   [4:0] shl_ln_reg_1083_pp0_iter3_reg;
reg   [4:0] shl_ln_reg_1083_pp0_iter4_reg;
reg   [4:0] shl_ln_reg_1083_pp0_iter5_reg;
reg   [4:0] shl_ln_reg_1083_pp0_iter6_reg;
reg   [4:0] shl_ln_reg_1083_pp0_iter7_reg;
reg   [4:0] shl_ln_reg_1083_pp0_iter8_reg;
reg   [4:0] shl_ln_reg_1083_pp0_iter9_reg;
reg   [4:0] shl_ln_reg_1083_pp0_iter10_reg;
reg   [4:0] shl_ln_reg_1083_pp0_iter11_reg;
reg   [4:0] shl_ln_reg_1083_pp0_iter12_reg;
wire   [12:0] add_ln34_fu_643_p2;
reg   [12:0] add_ln34_reg_1093;
wire   [12:0] add_ln34_3_fu_658_p2;
reg   [12:0] add_ln34_3_reg_1099;
reg   [10:0] tmp_1_reg_1105;
wire   [2:0] trunc_ln36_fu_692_p1;
reg   [2:0] trunc_ln36_reg_1110;
reg   [2:0] trunc_ln36_reg_1110_pp0_iter14_reg;
reg   [2:0] trunc_ln36_reg_1110_pp0_iter15_reg;
reg   [10:0] tmp_2_reg_1118;
reg   [10:0] tmp_3_reg_1123;
reg   [10:0] tmp_4_reg_1128;
reg   [10:0] tmp_4_reg_1128_pp0_iter14_reg;
wire   [6:0] max_val_1_fu_843_p3;
reg   [6:0] max_val_1_reg_1208;
wire   [7:0] val_fu_851_p13;
reg   [7:0] val_reg_1214;
wire   [6:0] trunc_ln36_2_fu_878_p1;
reg   [6:0] trunc_ln36_2_reg_1219;
wire   [7:0] val_5_fu_882_p13;
reg   [7:0] val_5_reg_1224;
wire   [6:0] trunc_ln36_3_fu_909_p1;
reg   [6:0] trunc_ln36_3_reg_1229;
wire   [6:0] max_val_5_fu_992_p3;
reg   [6:0] max_val_5_reg_1259;
wire   [63:0] zext_ln36_fu_782_p1;
wire   [63:0] zext_ln36_3_fu_790_p1;
wire   [63:0] zext_ln36_5_fu_798_p1;
wire   [63:0] zext_ln36_6_fu_913_p1;
wire    ap_block_pp0_stage0_01001_grp1;
reg   [3:0] w_fu_118;
wire   [3:0] add_ln25_fu_510_p2;
wire    ap_loop_init;
reg   [3:0] h_fu_122;
reg   [7:0] indvar_flatten_fu_126;
wire   [7:0] select_ln24_1_fu_522_p3;
reg   [3:0] co_fu_130;
reg   [10:0] indvar_flatten12_fu_134;
wire   [10:0] add_ln23_fu_391_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten12_load;
wire    ap_block_pp0_stage0;
reg    pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_ce1_local;
reg   [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_address1_local;
reg    pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_ce0_local;
reg    pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_ce1_local;
reg   [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_address1_local;
reg    pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_ce0_local;
reg    pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_ce1_local;
reg   [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_address1_local;
reg    pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_ce0_local;
reg    pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_ce1_local;
reg   [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_address1_local;
reg    pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_ce0_local;
reg    pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_ce1_local;
reg   [10:0] pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_address1_local;
reg    pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_ce0_local;
wire   [0:0] icmp_ln24_fu_414_p2;
wire   [0:0] icmp_ln25_fu_434_p2;
wire   [0:0] xor_ln23_fu_428_p2;
wire   [3:0] add_ln23_1_fu_446_p2;
wire   [3:0] select_ln23_fu_420_p3;
wire   [0:0] and_ln23_fu_440_p2;
wire   [0:0] empty_fu_466_p2;
wire   [3:0] add_ln24_fu_460_p2;
wire   [2:0] trunc_ln34_fu_492_p1;
wire   [5:0] p_shl1_fu_496_p3;
wire   [5:0] zext_ln34_fu_488_p1;
wire   [7:0] add_ln24_1_fu_516_p2;
wire   [4:0] tmp_fu_560_p3;
wire   [6:0] p_shl2_fu_553_p3;
wire   [6:0] zext_ln34_2_fu_567_p1;
wire   [6:0] sub_ln34_fu_571_p2;
wire   [9:0] p_shl_fu_581_p3;
wire   [9:0] zext_ln34_4_fu_588_p1;
wire   [6:0] zext_ln34_1_fu_550_p1;
wire   [6:0] zext_ln34_8_fu_605_p1;
wire   [6:0] add_ln34_4_fu_609_p2;
wire   [7:0] zext_ln34_9_fu_615_p1;
wire   [7:0] zext_ln34_3_fu_577_p1;
wire   [7:0] grp_fu_625_p0;
wire   [3:0] grp_fu_625_p1;
wire   [3:0] mul_ln24_fu_634_p0;
wire   [10:0] mul_ln24_fu_634_p1;
wire   [12:0] zext_ln34_5_fu_640_p1;
wire   [12:0] mul_ln24_fu_634_p2;
wire   [9:0] add_ln34_2_fu_649_p2;
wire   [12:0] zext_ln34_6_fu_654_p1;
wire   [12:0] zext_ln34_7_fu_664_p1;
wire   [12:0] add_ln34_6_fu_667_p2;
wire   [12:0] mul_ln36_fu_676_p0;
wire   [14:0] mul_ln36_fu_676_p1;
wire   [26:0] mul_ln36_fu_676_p2;
wire   [2:0] grp_fu_625_p2;
wire   [4:0] or_ln_fu_696_p3;
wire   [12:0] zext_ln34_10_fu_703_p1;
wire   [12:0] add_ln34_7_fu_707_p2;
wire   [12:0] mul_ln36_1_fu_716_p0;
wire   [14:0] mul_ln36_1_fu_716_p1;
wire   [26:0] mul_ln36_1_fu_716_p2;
wire   [12:0] add_ln34_8_fu_732_p2;
wire   [12:0] mul_ln36_2_fu_741_p0;
wire   [14:0] mul_ln36_2_fu_741_p1;
wire   [26:0] mul_ln36_2_fu_741_p2;
wire   [12:0] add_ln34_9_fu_757_p2;
wire   [12:0] mul_ln36_3_fu_766_p0;
wire   [14:0] mul_ln36_3_fu_766_p1;
wire   [26:0] mul_ln36_3_fu_766_p2;
wire   [7:0] val_4_fu_806_p11;
wire   [7:0] val_4_fu_806_p13;
wire   [0:0] icmp_ln37_fu_837_p2;
wire   [6:0] trunc_ln36_1_fu_833_p1;
wire   [7:0] val_fu_851_p11;
wire   [7:0] val_5_fu_882_p11;
wire   [7:0] zext_ln28_fu_921_p1;
wire   [0:0] icmp_ln37_1_fu_924_p2;
wire   [6:0] max_val_2_fu_929_p3;
wire   [7:0] zext_ln28_1_fu_935_p1;
wire   [0:0] icmp_ln37_2_fu_939_p2;
wire   [6:0] max_val_4_fu_944_p3;
wire   [7:0] val_3_fu_955_p11;
wire   [7:0] val_3_fu_955_p13;
wire   [7:0] zext_ln28_2_fu_951_p1;
wire   [0:0] icmp_ln37_3_fu_986_p2;
wire   [6:0] trunc_ln36_4_fu_982_p1;
reg    grp_fu_625_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [12:0] mul_ln24_fu_634_p00;
wire   [26:0] mul_ln36_1_fu_716_p00;
wire   [26:0] mul_ln36_2_fu_741_p00;
wire   [26:0] mul_ln36_3_fu_766_p00;
wire   [26:0] mul_ln36_fu_676_p00;
wire   [2:0] val_4_fu_806_p1;
wire   [2:0] val_4_fu_806_p3;
wire   [2:0] val_4_fu_806_p5;
wire   [2:0] val_4_fu_806_p7;
wire  signed [2:0] val_4_fu_806_p9;
wire  signed [2:0] val_fu_851_p1;
wire   [2:0] val_fu_851_p3;
wire   [2:0] val_fu_851_p5;
wire   [2:0] val_fu_851_p7;
wire   [2:0] val_fu_851_p9;
wire   [2:0] val_5_fu_882_p1;
wire   [2:0] val_5_fu_882_p3;
wire  signed [2:0] val_5_fu_882_p5;
wire   [2:0] val_5_fu_882_p7;
wire   [2:0] val_5_fu_882_p9;
wire   [2:0] val_3_fu_955_p1;
wire   [2:0] val_3_fu_955_p3;
wire   [2:0] val_3_fu_955_p5;
wire  signed [2:0] val_3_fu_955_p7;
wire   [2:0] val_3_fu_955_p9;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 w_fu_118 = 4'd0;
#0 h_fu_122 = 4'd0;
#0 indvar_flatten_fu_126 = 8'd0;
#0 co_fu_130 = 4'd0;
#0 indvar_flatten12_fu_134 = 11'd0;
#0 ap_done_reg = 1'b0;
end

top_urem_8ns_4ns_3_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 3 ))
urem_8ns_4ns_3_12_1_U254(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_625_p0),
    .din1(grp_fu_625_p1),
    .ce(grp_fu_625_ce),
    .dout(grp_fu_625_p2)
);

top_mul_4ns_11ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 13 ))
mul_4ns_11ns_13_1_1_U255(
    .din0(mul_ln24_fu_634_p0),
    .din1(mul_ln24_fu_634_p1),
    .dout(mul_ln24_fu_634_p2)
);

top_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U256(
    .din0(mul_ln36_fu_676_p0),
    .din1(mul_ln36_fu_676_p1),
    .dout(mul_ln36_fu_676_p2)
);

top_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U257(
    .din0(mul_ln36_1_fu_716_p0),
    .din1(mul_ln36_1_fu_716_p1),
    .dout(mul_ln36_1_fu_716_p2)
);

top_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U258(
    .din0(mul_ln36_2_fu_741_p0),
    .din1(mul_ln36_2_fu_741_p1),
    .dout(mul_ln36_2_fu_741_p2)
);

top_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U259(
    .din0(mul_ln36_3_fu_766_p0),
    .din1(mul_ln36_3_fu_766_p1),
    .dout(mul_ln36_3_fu_766_p2)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U260(
    .din0(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_q1),
    .din1(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_q1),
    .din2(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_q1),
    .din3(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_q1),
    .din4(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_q1),
    .def(val_4_fu_806_p11),
    .sel(trunc_ln36_reg_1110_pp0_iter14_reg),
    .dout(val_4_fu_806_p13)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h0 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h2 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h3 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U261(
    .din0(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_q1),
    .din1(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_q1),
    .din2(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_q1),
    .din3(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_q1),
    .din4(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_q1),
    .def(val_fu_851_p11),
    .sel(trunc_ln36_reg_1110_pp0_iter14_reg),
    .dout(val_fu_851_p13)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h2 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h3 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h4 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h1 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U262(
    .din0(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_q1),
    .din1(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_q1),
    .din2(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_q1),
    .din3(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_q1),
    .din4(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_q1),
    .def(val_5_fu_882_p11),
    .sel(trunc_ln36_reg_1110_pp0_iter14_reg),
    .dout(val_5_fu_882_p13)
);

(* dissolve_hierarchy = "yes" *) top_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h3 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h4 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h0 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U263(
    .din0(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_q0),
    .din1(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_q0),
    .din2(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_q0),
    .din3(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_q0),
    .din4(pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_q0),
    .def(val_3_fu_955_p11),
    .sel(trunc_ln36_reg_1110_pp0_iter15_reg),
    .dout(val_3_fu_955_p13)
);

top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter16_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            co_fu_130 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            co_fu_130 <= select_ln23_1_fu_452_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            h_fu_122 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            h_fu_122 <= select_ln24_fu_480_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln23_fu_385_p2 == 1'd0))) begin
            indvar_flatten12_fu_134 <= add_ln23_fu_391_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten12_fu_134 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_126 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            indvar_flatten_fu_126 <= select_ln24_1_fu_522_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_fu_118 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            w_fu_118 <= add_ln25_fu_510_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        add_ln34_1_reg_1072 <= add_ln34_1_fu_504_p2;
        select_ln23_1_reg_1054 <= select_ln23_1_fu_452_p3;
        select_ln24_reg_1065 <= select_ln24_fu_480_p3;
        w_mid2_reg_1059 <= w_mid2_fu_472_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln34_3_reg_1099 <= add_ln34_3_fu_658_p2;
        add_ln34_reg_1093 <= add_ln34_fu_643_p2;
        max_val_1_reg_1208 <= max_val_1_fu_843_p3;
        max_val_5_reg_1259 <= max_val_5_fu_992_p3;
        select_ln23_1_reg_1054_pp0_iter10_reg <= select_ln23_1_reg_1054_pp0_iter9_reg;
        select_ln23_1_reg_1054_pp0_iter11_reg <= select_ln23_1_reg_1054_pp0_iter10_reg;
        select_ln23_1_reg_1054_pp0_iter2_reg <= select_ln23_1_reg_1054;
        select_ln23_1_reg_1054_pp0_iter3_reg <= select_ln23_1_reg_1054_pp0_iter2_reg;
        select_ln23_1_reg_1054_pp0_iter4_reg <= select_ln23_1_reg_1054_pp0_iter3_reg;
        select_ln23_1_reg_1054_pp0_iter5_reg <= select_ln23_1_reg_1054_pp0_iter4_reg;
        select_ln23_1_reg_1054_pp0_iter6_reg <= select_ln23_1_reg_1054_pp0_iter5_reg;
        select_ln23_1_reg_1054_pp0_iter7_reg <= select_ln23_1_reg_1054_pp0_iter6_reg;
        select_ln23_1_reg_1054_pp0_iter8_reg <= select_ln23_1_reg_1054_pp0_iter7_reg;
        select_ln23_1_reg_1054_pp0_iter9_reg <= select_ln23_1_reg_1054_pp0_iter8_reg;
        shl_ln_reg_1083[4 : 1] <= shl_ln_fu_598_p3[4 : 1];
        shl_ln_reg_1083_pp0_iter10_reg[4 : 1] <= shl_ln_reg_1083_pp0_iter9_reg[4 : 1];
        shl_ln_reg_1083_pp0_iter11_reg[4 : 1] <= shl_ln_reg_1083_pp0_iter10_reg[4 : 1];
        shl_ln_reg_1083_pp0_iter12_reg[4 : 1] <= shl_ln_reg_1083_pp0_iter11_reg[4 : 1];
        shl_ln_reg_1083_pp0_iter3_reg[4 : 1] <= shl_ln_reg_1083[4 : 1];
        shl_ln_reg_1083_pp0_iter4_reg[4 : 1] <= shl_ln_reg_1083_pp0_iter3_reg[4 : 1];
        shl_ln_reg_1083_pp0_iter5_reg[4 : 1] <= shl_ln_reg_1083_pp0_iter4_reg[4 : 1];
        shl_ln_reg_1083_pp0_iter6_reg[4 : 1] <= shl_ln_reg_1083_pp0_iter5_reg[4 : 1];
        shl_ln_reg_1083_pp0_iter7_reg[4 : 1] <= shl_ln_reg_1083_pp0_iter6_reg[4 : 1];
        shl_ln_reg_1083_pp0_iter8_reg[4 : 1] <= shl_ln_reg_1083_pp0_iter7_reg[4 : 1];
        shl_ln_reg_1083_pp0_iter9_reg[4 : 1] <= shl_ln_reg_1083_pp0_iter8_reg[4 : 1];
        sub_ln34_1_reg_1077[9 : 3] <= sub_ln34_1_fu_592_p2[9 : 3];
        sub_ln34_1_reg_1077_pp0_iter10_reg[9 : 3] <= sub_ln34_1_reg_1077_pp0_iter9_reg[9 : 3];
        sub_ln34_1_reg_1077_pp0_iter11_reg[9 : 3] <= sub_ln34_1_reg_1077_pp0_iter10_reg[9 : 3];
        sub_ln34_1_reg_1077_pp0_iter3_reg[9 : 3] <= sub_ln34_1_reg_1077[9 : 3];
        sub_ln34_1_reg_1077_pp0_iter4_reg[9 : 3] <= sub_ln34_1_reg_1077_pp0_iter3_reg[9 : 3];
        sub_ln34_1_reg_1077_pp0_iter5_reg[9 : 3] <= sub_ln34_1_reg_1077_pp0_iter4_reg[9 : 3];
        sub_ln34_1_reg_1077_pp0_iter6_reg[9 : 3] <= sub_ln34_1_reg_1077_pp0_iter5_reg[9 : 3];
        sub_ln34_1_reg_1077_pp0_iter7_reg[9 : 3] <= sub_ln34_1_reg_1077_pp0_iter6_reg[9 : 3];
        sub_ln34_1_reg_1077_pp0_iter8_reg[9 : 3] <= sub_ln34_1_reg_1077_pp0_iter7_reg[9 : 3];
        sub_ln34_1_reg_1077_pp0_iter9_reg[9 : 3] <= sub_ln34_1_reg_1077_pp0_iter8_reg[9 : 3];
        tmp_1_reg_1105 <= {{mul_ln36_fu_676_p2[26:16]}};
        tmp_2_reg_1118 <= {{mul_ln36_1_fu_716_p2[26:16]}};
        tmp_3_reg_1123 <= {{mul_ln36_2_fu_741_p2[26:16]}};
        tmp_4_reg_1128 <= {{mul_ln36_3_fu_766_p2[26:16]}};
        tmp_4_reg_1128_pp0_iter14_reg <= tmp_4_reg_1128;
        trunc_ln36_2_reg_1219 <= trunc_ln36_2_fu_878_p1;
        trunc_ln36_3_reg_1229 <= trunc_ln36_3_fu_909_p1;
        trunc_ln36_reg_1110 <= trunc_ln36_fu_692_p1;
        trunc_ln36_reg_1110_pp0_iter14_reg <= trunc_ln36_reg_1110;
        trunc_ln36_reg_1110_pp0_iter15_reg <= trunc_ln36_reg_1110_pp0_iter14_reg;
        val_5_reg_1224 <= val_5_fu_882_p13;
        val_reg_1214 <= val_fu_851_p13;
        w_mid2_reg_1059_pp0_iter10_reg <= w_mid2_reg_1059_pp0_iter9_reg;
        w_mid2_reg_1059_pp0_iter11_reg <= w_mid2_reg_1059_pp0_iter10_reg;
        w_mid2_reg_1059_pp0_iter12_reg <= w_mid2_reg_1059_pp0_iter11_reg;
        w_mid2_reg_1059_pp0_iter2_reg <= w_mid2_reg_1059;
        w_mid2_reg_1059_pp0_iter3_reg <= w_mid2_reg_1059_pp0_iter2_reg;
        w_mid2_reg_1059_pp0_iter4_reg <= w_mid2_reg_1059_pp0_iter3_reg;
        w_mid2_reg_1059_pp0_iter5_reg <= w_mid2_reg_1059_pp0_iter4_reg;
        w_mid2_reg_1059_pp0_iter6_reg <= w_mid2_reg_1059_pp0_iter5_reg;
        w_mid2_reg_1059_pp0_iter7_reg <= w_mid2_reg_1059_pp0_iter6_reg;
        w_mid2_reg_1059_pp0_iter8_reg <= w_mid2_reg_1059_pp0_iter7_reg;
        w_mid2_reg_1059_pp0_iter9_reg <= w_mid2_reg_1059_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln23_fu_385_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter16_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten12_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten12_load = indvar_flatten12_fu_134;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem0_blk_n_W = m_axi_gmem0_0_WREADY;
    end else begin
        gmem0_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_625_ce = 1'b1;
    end else begin
        grp_fu_625_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem0_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem0_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        if ((trunc_ln36_reg_1110 == 3'd0)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_address1_local = zext_ln36_5_fu_798_p1;
        end else if ((trunc_ln36_reg_1110 == 3'd2)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_address1_local = zext_ln36_3_fu_790_p1;
        end else if ((trunc_ln36_reg_1110 == 3'd3)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_address1_local = zext_ln36_fu_782_p1;
        end else begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_address1_local = 'bx;
        end
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_ce0_local = 1'b1;
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1)))) begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_ce1_local = 1'b1;
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        if ((trunc_ln36_reg_1110 == 3'd4)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_address1_local = zext_ln36_5_fu_798_p1;
        end else if ((trunc_ln36_reg_1110 == 3'd1)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_address1_local = zext_ln36_3_fu_790_p1;
        end else if ((trunc_ln36_reg_1110 == 3'd2)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_address1_local = zext_ln36_fu_782_p1;
        end else begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_address1_local = 'bx;
        end
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_ce0_local = 1'b1;
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1)))) begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_ce1_local = 1'b1;
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        if ((trunc_ln36_reg_1110 == 3'd3)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_address1_local = zext_ln36_5_fu_798_p1;
        end else if ((trunc_ln36_reg_1110 == 3'd0)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_address1_local = zext_ln36_3_fu_790_p1;
        end else if ((trunc_ln36_reg_1110 == 3'd1)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_address1_local = zext_ln36_fu_782_p1;
        end else begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_address1_local = 'bx;
        end
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_ce0_local = 1'b1;
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1)))) begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_ce1_local = 1'b1;
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        if ((trunc_ln36_reg_1110 == 3'd2)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_address1_local = zext_ln36_5_fu_798_p1;
        end else if ((trunc_ln36_reg_1110 == 3'd4)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_address1_local = zext_ln36_3_fu_790_p1;
        end else if ((trunc_ln36_reg_1110 == 3'd0)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_address1_local = zext_ln36_fu_782_p1;
        end else begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_address1_local = 'bx;
        end
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_ce0_local = 1'b1;
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1)))) begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_ce1_local = 1'b1;
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        if ((trunc_ln36_reg_1110 == 3'd1)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_address1_local = zext_ln36_5_fu_798_p1;
        end else if ((trunc_ln36_reg_1110 == 3'd3)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_address1_local = zext_ln36_3_fu_790_p1;
        end else if ((trunc_ln36_reg_1110 == 3'd4)) begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_address1_local = zext_ln36_fu_782_p1;
        end else begin
            pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_address1_local = 'bx;
        end
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_ce0_local = 1'b1;
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln36_reg_1110 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1)))) begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_ce1_local = 1'b1;
    end else begin
        pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln23_1_fu_446_p2 = (co_fu_130 + 4'd1);

assign add_ln23_fu_391_p2 = (ap_sig_allocacmp_indvar_flatten12_load + 11'd1);

assign add_ln24_1_fu_516_p2 = (indvar_flatten_fu_126 + 8'd1);

assign add_ln24_fu_460_p2 = (select_ln23_fu_420_p3 + 4'd1);

assign add_ln25_fu_510_p2 = (w_mid2_fu_472_p3 + 4'd1);

assign add_ln34_1_fu_504_p2 = (p_shl1_fu_496_p3 + zext_ln34_fu_488_p1);

assign add_ln34_2_fu_649_p2 = (sub_ln34_1_reg_1077_pp0_iter11_reg + 10'd28);

assign add_ln34_3_fu_658_p2 = (zext_ln34_6_fu_654_p1 + mul_ln24_fu_634_p2);

assign add_ln34_4_fu_609_p2 = (zext_ln34_1_fu_550_p1 + zext_ln34_8_fu_605_p1);

assign add_ln34_6_fu_667_p2 = (zext_ln34_7_fu_664_p1 + add_ln34_reg_1093);

assign add_ln34_7_fu_707_p2 = (zext_ln34_10_fu_703_p1 + add_ln34_reg_1093);

assign add_ln34_8_fu_732_p2 = (zext_ln34_7_fu_664_p1 + add_ln34_3_reg_1099);

assign add_ln34_9_fu_757_p2 = (zext_ln34_10_fu_703_p1 + add_ln34_3_reg_1099);

assign add_ln34_fu_643_p2 = (zext_ln34_5_fu_640_p1 + mul_ln24_fu_634_p2);

assign and_ln23_fu_440_p2 = (xor_ln23_fu_428_p2 & icmp_ln25_fu_434_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem0_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_gmem0_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem0_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_466_p2 = (icmp_ln24_fu_414_p2 | and_ln23_fu_440_p2);

assign grp_fu_625_p0 = (zext_ln34_9_fu_615_p1 + zext_ln34_3_fu_577_p1);

assign grp_fu_625_p1 = 8'd5;

assign icmp_ln23_fu_385_p2 = ((ap_sig_allocacmp_indvar_flatten12_load == 11'd1568) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_414_p2 = ((indvar_flatten_fu_126 == 8'd196) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_434_p2 = ((w_fu_118 == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln37_1_fu_924_p2 = (($signed(val_reg_1214) > $signed(zext_ln28_fu_921_p1)) ? 1'b1 : 1'b0);

assign icmp_ln37_2_fu_939_p2 = (($signed(val_5_reg_1224) > $signed(zext_ln28_1_fu_935_p1)) ? 1'b1 : 1'b0);

assign icmp_ln37_3_fu_986_p2 = (($signed(val_3_fu_955_p13) > $signed(zext_ln28_2_fu_951_p1)) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_837_p2 = (($signed(val_4_fu_806_p13) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign m_axi_gmem0_0_ARADDR = 64'd0;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 32'd0;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_ARVALID = 1'b0;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_RREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = max_val_5_reg_1259;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 1'd1;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign max_val_1_fu_843_p3 = ((icmp_ln37_fu_837_p2[0:0] == 1'b1) ? trunc_ln36_1_fu_833_p1 : 7'd0);

assign max_val_2_fu_929_p3 = ((icmp_ln37_1_fu_924_p2[0:0] == 1'b1) ? trunc_ln36_2_reg_1219 : max_val_1_reg_1208);

assign max_val_4_fu_944_p3 = ((icmp_ln37_2_fu_939_p2[0:0] == 1'b1) ? trunc_ln36_3_reg_1229 : max_val_2_fu_929_p3);

assign max_val_5_fu_992_p3 = ((icmp_ln37_3_fu_986_p2[0:0] == 1'b1) ? trunc_ln36_4_fu_982_p1 : max_val_4_fu_944_p3);

assign mul_ln24_fu_634_p0 = mul_ln24_fu_634_p00;

assign mul_ln24_fu_634_p00 = select_ln23_1_reg_1054_pp0_iter11_reg;

assign mul_ln24_fu_634_p1 = 13'd784;

assign mul_ln36_1_fu_716_p0 = mul_ln36_1_fu_716_p00;

assign mul_ln36_1_fu_716_p00 = add_ln34_7_fu_707_p2;

assign mul_ln36_1_fu_716_p1 = 27'd13108;

assign mul_ln36_2_fu_741_p0 = mul_ln36_2_fu_741_p00;

assign mul_ln36_2_fu_741_p00 = add_ln34_8_fu_732_p2;

assign mul_ln36_2_fu_741_p1 = 27'd13108;

assign mul_ln36_3_fu_766_p0 = mul_ln36_3_fu_766_p00;

assign mul_ln36_3_fu_766_p00 = add_ln34_9_fu_757_p2;

assign mul_ln36_3_fu_766_p1 = 27'd13108;

assign mul_ln36_fu_676_p0 = mul_ln36_fu_676_p00;

assign mul_ln36_fu_676_p00 = add_ln34_6_fu_667_p2;

assign mul_ln36_fu_676_p1 = 27'd13108;

assign or_ln_fu_696_p3 = {{w_mid2_reg_1059_pp0_iter12_reg}, {1'd1}};

assign p_shl1_fu_496_p3 = {{trunc_ln34_fu_492_p1}, {3'd0}};

assign p_shl2_fu_553_p3 = {{select_ln24_reg_1065}, {3'd0}};

assign p_shl_fu_581_p3 = {{select_ln24_reg_1065}, {6'd0}};

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_address0 = zext_ln36_6_fu_913_p1;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_address1 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_address1_local;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_ce0 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_ce0_local;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_ce1 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_1_ce1_local;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_address0 = zext_ln36_6_fu_913_p1;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_address1 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_address1_local;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_ce0 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_ce0_local;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_ce1 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_2_ce1_local;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_address0 = zext_ln36_6_fu_913_p1;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_address1 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_address1_local;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_ce0 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_ce0_local;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_ce1 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_3_ce1_local;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_address0 = zext_ln36_6_fu_913_p1;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_address1 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_address1_local;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_ce0 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_ce0_local;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_ce1 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_4_ce1_local;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_address0 = zext_ln36_6_fu_913_p1;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_address1 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_address1_local;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_ce0 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_ce0_local;

assign pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_ce1 = pool_ap_fixed_ap_fixed_8_5_5_3_0_int_int_int_int_int_local_input_ce1_local;

assign select_ln23_1_fu_452_p3 = ((icmp_ln24_fu_414_p2[0:0] == 1'b1) ? add_ln23_1_fu_446_p2 : co_fu_130);

assign select_ln23_fu_420_p3 = ((icmp_ln24_fu_414_p2[0:0] == 1'b1) ? 4'd0 : h_fu_122);

assign select_ln24_1_fu_522_p3 = ((icmp_ln24_fu_414_p2[0:0] == 1'b1) ? 8'd1 : add_ln24_1_fu_516_p2);

assign select_ln24_fu_480_p3 = ((and_ln23_fu_440_p2[0:0] == 1'b1) ? add_ln24_fu_460_p2 : select_ln23_fu_420_p3);

assign shl_ln_fu_598_p3 = {{w_mid2_reg_1059}, {1'd0}};

assign sub_ln34_1_fu_592_p2 = (p_shl_fu_581_p3 - zext_ln34_4_fu_588_p1);

assign sub_ln34_fu_571_p2 = (p_shl2_fu_553_p3 - zext_ln34_2_fu_567_p1);

assign tmp_fu_560_p3 = {{select_ln24_reg_1065}, {1'd0}};

assign trunc_ln34_fu_492_p1 = select_ln23_1_fu_452_p3[2:0];

assign trunc_ln36_1_fu_833_p1 = val_4_fu_806_p13[6:0];

assign trunc_ln36_2_fu_878_p1 = val_fu_851_p13[6:0];

assign trunc_ln36_3_fu_909_p1 = val_5_fu_882_p13[6:0];

assign trunc_ln36_4_fu_982_p1 = val_3_fu_955_p13[6:0];

assign trunc_ln36_fu_692_p1 = grp_fu_625_p2[2:0];

assign val_3_fu_955_p11 = 'bx;

assign val_4_fu_806_p11 = 'bx;

assign val_5_fu_882_p11 = 'bx;

assign val_fu_851_p11 = 'bx;

assign w_mid2_fu_472_p3 = ((empty_fu_466_p2[0:0] == 1'b1) ? 4'd0 : w_fu_118);

assign xor_ln23_fu_428_p2 = (icmp_ln24_fu_414_p2 ^ 1'd1);

assign zext_ln28_1_fu_935_p1 = max_val_2_fu_929_p3;

assign zext_ln28_2_fu_951_p1 = max_val_4_fu_944_p3;

assign zext_ln28_fu_921_p1 = max_val_1_reg_1208;

assign zext_ln34_10_fu_703_p1 = or_ln_fu_696_p3;

assign zext_ln34_1_fu_550_p1 = add_ln34_1_reg_1072;

assign zext_ln34_2_fu_567_p1 = tmp_fu_560_p3;

assign zext_ln34_3_fu_577_p1 = sub_ln34_fu_571_p2;

assign zext_ln34_4_fu_588_p1 = p_shl2_fu_553_p3;

assign zext_ln34_5_fu_640_p1 = sub_ln34_1_reg_1077_pp0_iter11_reg;

assign zext_ln34_6_fu_654_p1 = add_ln34_2_fu_649_p2;

assign zext_ln34_7_fu_664_p1 = shl_ln_reg_1083_pp0_iter12_reg;

assign zext_ln34_8_fu_605_p1 = shl_ln_fu_598_p3;

assign zext_ln34_9_fu_615_p1 = add_ln34_4_fu_609_p2;

assign zext_ln34_fu_488_p1 = select_ln23_1_fu_452_p3;

assign zext_ln36_3_fu_790_p1 = tmp_2_reg_1118;

assign zext_ln36_5_fu_798_p1 = tmp_3_reg_1123;

assign zext_ln36_6_fu_913_p1 = tmp_4_reg_1128_pp0_iter14_reg;

assign zext_ln36_fu_782_p1 = tmp_1_reg_1105;

always @ (posedge ap_clk) begin
    sub_ln34_1_reg_1077[2:0] <= 3'b000;
    sub_ln34_1_reg_1077_pp0_iter3_reg[2:0] <= 3'b000;
    sub_ln34_1_reg_1077_pp0_iter4_reg[2:0] <= 3'b000;
    sub_ln34_1_reg_1077_pp0_iter5_reg[2:0] <= 3'b000;
    sub_ln34_1_reg_1077_pp0_iter6_reg[2:0] <= 3'b000;
    sub_ln34_1_reg_1077_pp0_iter7_reg[2:0] <= 3'b000;
    sub_ln34_1_reg_1077_pp0_iter8_reg[2:0] <= 3'b000;
    sub_ln34_1_reg_1077_pp0_iter9_reg[2:0] <= 3'b000;
    sub_ln34_1_reg_1077_pp0_iter10_reg[2:0] <= 3'b000;
    sub_ln34_1_reg_1077_pp0_iter11_reg[2:0] <= 3'b000;
    shl_ln_reg_1083[0] <= 1'b0;
    shl_ln_reg_1083_pp0_iter3_reg[0] <= 1'b0;
    shl_ln_reg_1083_pp0_iter4_reg[0] <= 1'b0;
    shl_ln_reg_1083_pp0_iter5_reg[0] <= 1'b0;
    shl_ln_reg_1083_pp0_iter6_reg[0] <= 1'b0;
    shl_ln_reg_1083_pp0_iter7_reg[0] <= 1'b0;
    shl_ln_reg_1083_pp0_iter8_reg[0] <= 1'b0;
    shl_ln_reg_1083_pp0_iter9_reg[0] <= 1'b0;
    shl_ln_reg_1083_pp0_iter10_reg[0] <= 1'b0;
    shl_ln_reg_1083_pp0_iter11_reg[0] <= 1'b0;
    shl_ln_reg_1083_pp0_iter12_reg[0] <= 1'b0;
end

endmodule //top_pool_Pipeline_CO_LOOP_H_LOOP_W_LOOP
