[hls]
relative_roots=/home/abdullah/Desktop/CNN-on-FPGA/hls_component
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=conv1/H_1  
syn.directive.loop_flatten=conv1/CO_1  
syn.directive.loop_flatten=conv2/VITIS_LOOP_95_2 off
syn.directive.loop_flatten=top/DENSE_OUTER  
syn.directive.array_partition=top/pool(ap_fixed<8, 5, (ap_q_mode)5, (ap_o_mode)3, 0>*, ap_fixed<8, 5, (ap_q_mode)5, (ap_o_mode)3, 0>*, int, int, int, int, int)::local_input dim=1 type=cyclic factor=5 variable=pool(ap_fixed<8, 5, (ap_q_mode)5, (ap_o_mode)3, 0>*, ap_fixed<8, 5, (ap_q_mode)5, (ap_o_mode)3, 0>*, int, int, int, int, int)::local_input
syn.directive.loop_flatten=pool.1/H_LOOP  
syn.directive.loop_flatten=pool.1/CO_LOOP  


